### ISSUE TITLE
Why is @Bean SamplerFunction<MessagingRequest> trySample never executed?

### ISSUE THREAD

**Issue by bastiat** [spring-cloud/spring-cloud-sleuth#1715] opened 2020-08-14 07:37 UTC
In project with spring-cloud-stream, rabbitmq and spring-cloud-sleuth my SamplerFunction<MessagingRequest>.trySample is never executed. Where can be a problem?
Bean is in a correct @Configuration class (other beans are created and work).

`spring.sleuth.sampler.probability: 0.001

    @Bean
    SamplerFunction<MessagingRequest> zipkinSampler() {
        return new Zipkin.ZipkinSampler();
    }

    public static class ZipkinSampler implements SamplerFunction<MessagingRequest> {

        private SamplerFunction<MessagingRequest> sampler = MessagingRuleSampler.newBuilder()
                .putRule(channelNameEquals("alertsNever"), Sampler.NEVER_SAMPLE)
                .putRule(channelNameEquals("rabbitChannel"), RateLimitingSampler.create(1))
                .putRule(Matchers.alwaysMatch(), RateLimitingSampler.create(100))
                .build();;

        @Override
        public Boolean trySample(final MessagingRequest request) {
            log.info("trySample {}, channelKind: {}, channelName: {}, operation: {}", request, request.channelKind(), request.channelName(), request.operation());

            return sampler.trySample(request);
        }
    }`

**Comment by marcingrzejszczak** [comment] 2020-08-18 16:39
Can you create a sample that replicates this problem?

**Comment by spring-issuemaster** [comment] 2020-08-25 16:39
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by gindex** [comment] 2020-08-26 16:12
I have the same issue. 

Dependencies:  spring-cloud-stream, spring-cloud-starter-stream-rabbit, spring-cloud-starter-zipkin

**Expected behaviour:** 
Exposed bean `@ConsumerSampler  @ProducerSampler SamplerFunction<MessagingRequest>` should be used to determine sampling rate for created and published RabbitMQ message. 

**Actual behaviour:** 
The provided `SamplerFunction` is ignored. Instead the default `RateLimitingSampler` bean provided via autoconfiguration is created and used to make a sampling decision for created and published messages. 

**Workaround**
Creating custom `Sampler` bean enables to extend and adjust the sampling behaviour.

**Comment by marcingrzejszczak** [comment] 2020-08-26 16:48
Can you create a sample that replicates this issue please?

**Comment by gindex** [comment] 2020-08-27 08:12
Here is a sample repository to reproduce the issue https://github.com/gindex/sleuth-rabbit-issue

**Comment by marcingrzejszczak** [comment] 2021-03-17 11:22
hey @gindex I'm trying to make the sample work with the latest Boot 2.4.x but I can't work around Kotlin issues. Would it be possible to rewrite it to Java and update to the latest version?

**Comment by spring-cloud-issues** [comment] 2021-03-24 11:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-03-31 11:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-03-31 11:23 UTC
Labels: feedback-reminder, waiting for feedback
