### ISSUE TITLE
spring-cloud-sleuth with RSocket

### ISSUE THREAD

**Issue by nikita111100** [spring-cloud/spring-cloud-sleuth#1980] opened 2021-06-18 15:29 UTC
does it support RSocket spring-cloud-sleuth?
i want to propagate headers (parent span id)  :)
if i use spring cloud sleuth i see it:  [rsocker, , ]

**Comment by marcingrzejszczak** [comment] 2021-06-18 15:40
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/pull/1929

**Closed by marcingrzejszczak** 2021-06-18 15:40 UTC
Labels: waiting-for-triage
