### ISSUE TITLE
zuul with numerous request and  sleuth generate duplicate traceid?

### ISSUE THREAD

**Issue by yugj** [spring-cloud/spring-cloud-sleuth#1159] opened 2018-12-13 03:02 UTC
hi,

i use slueth, hystrix,ribbon in my zuul proxy application

Spirngclond  version: Edgware.SR5

Springboot version:1.5.7.RELEASE

i see so many request with same traceid, and it have a same thread_name (my test envirement does not occurred, but my product envirement occurred)

Time 	HOSTNAME  	X-B3-TraceId  	thread_name  
December 13th 2018, 09:41:26.950	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:24.168	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:21.473	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:21.459	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:19.046	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:16.508	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:16.390	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:14.113	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:11.840	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
……..

i search the early issue :

https://github.com/spring-cloud/spring-cloud-sleuth/issues/634

https://github.com/spring-cloud/spring-cloud-sleuth/issues/728

https://github.com/spring-cloud/spring-cloud-sleuth/issues/849

i have upgrade springclound from Dalston.SR4 to Edgware.SR3; Edgware.SR3 to Edgware.SR5

And the duplicate traceid still occurred,i really need some help :)

this is the traceid:5536c838f82629e7 first occur

December 11th 2018, 13:22:26.093	FJXM-DM-Dmz-VM6-041	**Tried to close span but it is not the current span: [Trace: 5536c838f82629e7, Span: 5536c838f82629e7, Parent: null, exportable:false].  You may have forgotten to close or detach [Trace: 5536c838f82629e7, Span: 40471995be02b52c, Parent: 5536c838f82629e7, exportable:false]	http-nio-18001-exec-91**
December 11th 2018, 13:22:26.092	FJXM-DM-Dmz-VM6-041	sys error,http status:500,originUri:/client/sop	http-nio-18001-exec-91
December 11th 2018, 13:22:26.091	FJXM-DM-Dmz-VM6-041	Error during filtering	http-nio-18001-exec-91
December 11th 2018, 13:22:26.091	FJXM-DM-Dmz-VM6-041	**Premature end of chunk coded message body: closing chunk expected	http-nio-18001-exec-91**
December 11th 2018, 13:22:26.091	FJXM-DM-Dmz-VM6-041	AccessErrorFilter : Premature end of chunk coded message body: closing chunk expected	http-nio-18001-exec-91
December 11th 2018, 13:22:25.926	FJXM-DM-Dmz-VM6-041	zuul request xxx 

My kibana show the count of duplicate traceid,it happens in 2 node of my cluster,and have the same thread_name,i use md5sum to sum my jar files and it is the same (my zuul application deploy with jar file)

X-B3-TraceId.keyword: Descending 	Count 
97c56d437ede71e4	211,695
5536c838f82629e7	208,482
7996e6c16710481e  	12
0bb9d9e2441b8381	11
5c77a477721af529	11
a7f7884e47f4820b	11
c1942b6ed9e918e7	11
d704ec8994269237	11
f0bf7c3d20c8bdcb	11
06079d7a93fc1586	10

My application.yml (main properites)

```yaml
server:
  port: 18001
  tomcat:
    #default 10000
    max-connections: 10000
    #default 200
    max-threads: 2000

spring:
  profiles:
    active: @profile.id@
  application:
    name: ms-zuul
    # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enabled: true
    encoding.force: true
    multipart:
      max-file-size: 104857600

zuul:
  routes:
    sop:
      path: /sop/**
      strip-prefix: false
      serviceId: mg-sop
  max:
    host:
      connections: 60000
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 2000
    max-per-route-connections: 1000
    max-total-connections: 1000
  semaphore:
    max-semaphores: 2000
  groovyFiltersPath: /data/groovy/${spring.profiles.active}
hystrix:
  threadpool:
    default:
      coreSize: 500
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  MaxConnectionsPerHost: 500
  MaxTotalConnections: 2000
  ReadTimeout: 17000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 10000
  eureka:
    enabled: true

management:
  security:
    enabled: false
  health:
    rabbit:
      enabled: false

log:
  home: /data/logs/${spring.profiles.active}
eureka:
  client:
    healthcheck:
      enabled: true
```

clear  MDC code

```java
@Component
@RefreshScope
public class MDCCleanFilter extends AbstZuulFilter {

    private static final Logger log = LoggerFactory.getLogger(MDCCleanFilter.class);


    @Override
    public String filterType() {
        return FilterConstants.POST_TYPE;
    }

    @Override
    public int filterOrder() {
        return Integer.MAX_VALUE;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() throws ZuulException {

        if (log.isDebugEnabled()) {
            log.debug("clear mdc");
        }

        MDC.clear();

        return null;
    }
}
```

**i have two question:**

**1,**December 11th 2018, 13:22:26.093	FJXM-DM-Dmz-VM6-041	Tried to close span but it is not the current span: [Trace: 5536c838f82629e7, Span: 5536c838f82629e7, Parent: null, exportable:false].  You may have forgotten to close or detach [Trace: 5536c838f82629e7, Span: 40471995be02b52c, Parent: 5536c838f82629e7, exportable:false]	http-nio-18001-exec-91

Should i close the span manually ？

**2**,what shoud i do to prevent this problem happen again

**Comment by marcingrzejszczak** [comment] 2018-12-15 13:04
Can you upgrade to lastest Finchley release and see if the problem is still there?

**Comment by NearteamABE** [comment] 2018-12-17 11:16
We are facing the same problem. 

In our case, this occurs just after an Exception occurs at the Sleuth TraceFilter. The RuntimeException wrapping the  org.apache.http.ConnectionClosedException is processed in the finally block of doFilter() method but does not seem to close correctly the span. (I think in our case the request is successful but an error occured while closing the response stream).

This seems similar to the org.apache.catalina.connector.ClientAbortException which is ignored according the TraceWebAutoConfiguration.ClientAbortExceptionToIgnoreInTraceFilterConfig. clientAbortExceptionToIgnoreInTraceFilter() bean.

Hereunder our stack trace. I've detected duplicate TraceIds after this Exception.


at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	**at org.springframework.cloud.sleuth.instrument.web.TraceFilter.doFilter(TraceFilter.java:166)**
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Premature end of chunk coded message body: closing chunk expected
	at org.springframework.cloud.netflix.ribbon.apache.RibbonApacheHttpResponse.close(RibbonApacheHttpResponse.java:123)
	at org.springframework.cloud.netflix.ribbon.RibbonHttpResponse.close(RibbonHttpResponse.java:69)
	at org.springframework.cloud.netflix.zuul.filters.post.SendResponseFilter.writeResponse(SendResponseFilter.java:209)
	at org.springframework.cloud.netflix.zuul.filters.post.SendResponseFilter.run(SendResponseFilter.java:110)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
	... 104 common frames omitted
Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:213)
	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:315)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:140)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
	at org.springframework.cloud.netflix.ribbon.apache.RibbonApacheHttpResponse.close(RibbonApacheHttpResponse.java:120)

**Comment by yugj** [comment] 2018-12-18 12:33
> Can you upgrade to lastest Finchley release and see if the problem is still there?

My springboot an springcore version is too old ,i can not upgrade to Finchley.SR2 immediately

i wrote a filter PostSleuthFilter overwride TracePostZuulFilter whitch catch all Exception and close Span manually to prevent Span not bean closed, but I'm not sure if this is the cause

and i wrote a Filter before TraceFilter to clean not null span (my zuul application is the entry of my system ,it is ok to clean the span info )

my product envienment next upgrade window is 12.20, i will try this and upgrade later



```java
@Order(TraceFilter.ORDER -1)
public class PreSleuthFilter extends GenericFilterBean {

    private static final Logger log = LoggerFactory.getLogger(PreSleuthFilter.class);

    @Autowired
    private SleuthSupportService sleuthSupportService;


    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {


        sleuthSupportService.closeSupport();

        String currentMdcTraceId = MDC.get(Span.TRACE_ID_NAME);
        if (StringUtils.isNotBlank(currentMdcTraceId)) {
            log.warn("mdc data is dirty,clean mdc,dirty trace id :{}", currentMdcTraceId);
            MDC.clear();
        }

        chain.doFilter(request,response);
    }
}
```





```java
/**
 * @author yugj
 * @date 2018/12/18 5:21.
 */
@Component
public class PostSleuthFilter extends TracePostZuulFilter {

    @Autowired
    private SleuthSupportService sleuthSupportService;

    private static final Logger log = LoggerFactory.getLogger(PostSleuthFilter.class);

    public PostSleuthFilter(Tracer tracer, TraceKeys traceKeys) {
        super(tracer, traceKeys);
    }

    @Override
    public Object run() {

        try {

            return super.run();

        } catch (Exception e) {
            log.warn("sleuth post zuul filter error,close span manually", e);
            sleuthSupportService.closeSupport();
            return null;
        }
    }
}
```



```java
@Service
@RefreshScope
public class SleuthSupportService {

    @Value("${sys.sleuth.pre.forceClose:false}")
    private Boolean forceClose;

    private static final Logger log = LoggerFactory.getLogger(SleuthSupportService.class);

    @Autowired
    private Tracer tracer;

    /**
     * 
     */
    public void closeSupport() {

        Span span = tracer.getCurrentSpan();
        if (span == null) {
            return;
        }

        if (forceClose) {
            forceCloseCurrentSpan();
        } else {
            closeCurrentSpan();
        }
    }

    /**
     *
     */
    public void closeCurrentSpan() {

        Span span = tracer.getCurrentSpan();

        if (span != null) {
            tracer.close(span);
            log.info("close current span trace id :{}", span.traceIdString());
        }
    }

    /**
     * force close span,prevent sleuth span not bean closed?
     * 
     * @Deprecated will be deleted soon
     *
     */
    @Deprecated
    public void forceCloseCurrentSpan()  {

        log.info("force close current span");

        Class holder = null;
        Object obj = null;
        Constructor[] constructor;

        try {

            holder = Class.forName("org.springframework.cloud.sleuth.trace.SpanContextHolder");
            constructor = holder.getDeclaredConstructors();

            constructor[0].setAccessible(true);
            obj = constructor[0].newInstance();

            Method close = holder.getDeclaredMethod("close");

            close.setAccessible(true);
            close.invoke(obj);

        } catch (Exception e) {
            log.warn("force close current span error", e);
        }


    }
}
```

**Comment by marcingrzejszczak** [comment] 2018-12-18 13:14
@NearteamABE can you double check if the problem is still there with latest GA of Finchley?

**Comment by yugj** [comment] 2018-12-20 17:16
I close the span in the finally block if current span is not bean closed ,i can see some Exceptions like Connection reset,timed out cause sleuth  not close current span,

the detachOrCloseSpans method is so complicated, what if it closes directly in the finally?  

```java
public class MyTraceFilter extends TraceFilter {

    private static final Logger log = LoggerFactory.getLogger(MyTraceFilter.class);

    @Autowired
    private SleuthSupportService supportService;

    public MyTraceFilter(BeanFactory beanFactory) {
        super(beanFactory);
    }

    public MyTraceFilter(BeanFactory beanFactory, Pattern skipPattern) {
        super(beanFactory, skipPattern);
    }

    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {

        try {

            super.doFilter(servletRequest, servletResponse, filterChain);

        } finally {

            supportService.closeSupport();
        }

    }
}
```

**Comment by marcingrzejszczak** [comment] 2019-01-07 10:08
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-01-15 19:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Closed** 2019-01-21 10:10 UTC
