### ISSUE TITLE
X-B3-Sampled is set to 1 when the request was not sampled

### ISSUE THREAD

**Issue by dsatish** [spring-cloud/spring-cloud-sleuth#331] opened 2016-07-13 18:25 UTC
Steps to reproduce:

- Start Zipkin

```
wget -O zipkin.jar 'https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec'
java -jar zipkin.jar
```

- Check out https://github.com/adriancole/sleuth-webmvc-example
- Replace sampler in Frontend.java

```
/** Sleuth won't start a trace unless a sampler bean is configured */
  @Bean
  public Sampler defaultSampler() {
    //return new AlwaysSampler();
    return new NeverSampler();
  }
```

- Start both Frontend and Backend
- Issue a curl request to Frontend. 
- Expected header "X-B3-Sampled: 0"  --> the request wasn't sampled (sampler is NeverSampler)
- Actual header "X-B3-Sampled: 0"

```
curl -v http://localhost:8080
* Adding handle: conn: 0x7fc210803000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fc210803000) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 8080 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:8080
> Accept: */*
>
< HTTP/1.1 200 OK
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< X-B3-Sampled: 1
< X-B3-SpanId: c4adf4696a1334
< X-B3-TraceId: c4adf4696a1334
< X-Application-Context: frontend
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 28
< Date: Sat, 09 Jul 2016 13:04:41 GMT
<
* Connection #0 to host localhost left intact
Sat Jul 09 09:04:41 EDT 2016
```

**Comment by marcingrzejszczak** [comment] 2016-07-13 18:34
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/327

**Closed by marcingrzejszczak** 2016-07-13 18:34 UTC
