### ISSUE TITLE
Sleuth propagates HttpStatus exception on custom HTTP status

### ISSUE THREAD

**Issue by KJoyner** [spring-cloud/spring-cloud-sleuth#472] opened 2016-12-13 16:59 UTC
I am using Sleuth in a Zuul gateway. The request that is being proxied returns a custom value not in HttpStatus.Series. This causes an exception when sleuth calls HttpStatus.Series.valueOf(response.getStatus()) in the web TraceFilter. I believe Sleuth should not propagate that exception, particularly in this case when an external server may return a custom code. Perhaps Sleuth could catch it and look at the actual number and return success if in 200s and unsuccessful otherwise.

An example of a status code that is not in the HttpStatus.Series is 499 (an nginx custom code).

**Comment by spencergibb** [comment] 2016-12-13 17:01
Duplicate of #463?

**Comment by marcingrzejszczak** [comment] 2016-12-13 17:20
Yeah looks so. Can you yeah the latest snapshots please?

**Closed** 2016-12-20 17:23 UTC
Labels: duplicate
