### ISSUE TITLE
TraceId not propagated when consuming Spring Boot Service from Spring Integration application using outbound gateway

### ISSUE THREAD

**Issue by bsridhar123** [spring-cloud/spring-cloud-sleuth#632] opened 2017-07-10 05:03 UTC
I am invoking an endpoint in a Spring Boot Based Application from  a Spring Integration application.

I am using **Spring Boot 1.4.1 and Spring Cloud Camden Release.**

I have added **spring-cloud-starter-zipkin dependencies** to both the services

I also have a zipkin server started before starting the services , which I want to use to collect the traces.

When the request is sent I see a unique traceId in Spring Integration logs but also a unique traceId in the target Spring Boot Service.

It looks like the **traceId** is not getting propagated to Spring Boot based Service from Spring Integration Service.

The Spring Integration services uses outbound gateway to consume the Spring Boot Service. I have configured the integration flow using XML Configuration for this.

Is there any configuration we need to do to enable the **traceId** to be propagated so that it is reflected in the logs of the Spring Boot Service.

I also have added the below bean in both the applications.

```
@Bean
	public Sampler defaultSampler() {
		return new AlwaysSampler();
	}
```

I also tried using the **Dalston.Release** with **Spring Boot 1.5.4**  but I still did not see the traceId propagated.

In order to reproduce the issue, I have shared the codebase for this issue in the below repo,

https://github.com/bsridhar123/tracing-demo-repo

It includes the 

- the Spring Integration application ,
- the Spring Boot Service as well 
- the Zipkin Server which I have used to collect the traces.

Can you please let me know if this supported or not.

 If not can you please let me the know the correct approach for this.

**Comment by marcingrzejszczak** [comment] 2017-07-10 05:43
Can you turn on the DEBUG logging level for Sleuth (`logging.level.org.springframework.cloud.sleuth=DEBUG`) and upload the logs to this issue?

**Comment by bsridhar123** [comment] 2017-07-10 06:09
@marcingrzejszczak  Thanks for responding to my query.

I have uploaded the logs after enabling sleuth logs as below for both spring integration and spring boot services.

https://github.com/bsridhar123/tracing-demo-repo/blob/master/demo-service/demo-service.log
https://github.com/bsridhar123/tracing-demo-repo/blob/master/outbound-gateway-service/outbound-gateway.log

Let me know if you need any more details.

**Comment by bsridhar123** [comment] 2017-07-11 08:02
@marcingrzejszczak , I see that this has been tagged as a bug. But, can you please provide more details on if it is a bug only when using outbound gateway with Spring integration or is it a generic bug when using Spring Cloud Sleuth/Zipkin with Spring Integration or is it due to a specific version spring boot.

We have a set of spring integration apps consuming spring boot microservices and we want to use tracing to understand latency issues which we are currently experiencing.

Can you please let us know a timeline when we can expect the issue to be resolved.

**Comment by marcingrzejszczak** [comment] 2017-07-11 09:13
I've marked this as a bug cause it looks like it but I haven't yet confirmed it. I'll need to debug this but what bothers me is that in the logs I don't see any TraceChannelInterceptor doing its job. That's the component responsible for working with Channels in spring integration. I'll have to analyze why it's not working properly.

In the logs you can see that only the TraceFilter is present. It seems as if the http client in spring integration was not instrumented.

**Comment by marcingrzejszczak** [comment] 2017-07-11 09:53
Ok I had a chat with @dsyer and it seems that you have to register the `RestTemplate` as a bean and then inject it to your `outbound-gateway`.

```
<int-http:outbound-gateway rest-template="restTemplate" ...>
```

**Comment by bsridhar123** [comment] 2017-07-11 17:37
@marcingrzejszczak @dsyer Thanks for the solution. It works after I injected RestTemplate to my gateway.  I wasn't aware we can do so.  Is this documented somewhere in docs?

**Comment by marcingrzejszczak** [comment] 2017-07-11 17:39
I'm pretty sure that we document that rest template

**Comment by marcingrzejszczak** [comment] 2017-07-11 17:40
Must always be a bean http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_http_client_integration. We don't provide an explicit documentation for integration. Does it make sense?

**Comment by bsridhar123** [comment] 2017-07-11 17:45
Yes.  It makes sense.

**Closed** 2017-07-11 18:03 UTC
Labels: bug

**Comment by ritesh-signity** [comment] 2018-12-19 08:08
Guys i need to trace all details(url hit, api hit, method call etc. ) in a micro service with global id.  how can i do that with sleuth?
