### ISSUE TITLE
MDC  question

### ISSUE THREAD

**Issue by zywei** [spring-cloud/spring-cloud-sleuth#248] opened 2016-04-11 08:41 UTC
i have some question about below code:

```
   	@Override
	public void logStoppedSpan(Span parent, Span span) {
		log("Stopped span|{}", span);
		if (parent != null) {
			MDC.put(Span.SPAN_ID_NAME, Span.idToHex(parent.getSpanId()));
			MDC.put(Span.SPAN_EXPORT_NAME, String.valueOf(parent.isExportable()));
		}
		else {
			MDC.remove(Span.SPAN_ID_NAME);
			MDC.remove(Span.SPAN_EXPORT_NAME);
			MDC.remove(Span.TRACE_ID_NAME);
		}
	}
```

when SERVICE_A call SERVICE_B, SERVICE_B always run to "if(parent != null)",but the request is over.

**Comment by marcingrzejszczak** [comment] 2016-04-15 10:22
Hey @zywei - can you elaborate more on this cause actually I don't understand what the problem is. Can you show the sample code?

**Comment by zywei** [comment] 2016-04-18 02:54
i mean that when SERVICE_A call SERVICE_B, SERVICE_A create a span named span_ab as a bridge between SERVICE_A  and SERVICE_B, then SERVICE_B has a parent span named span_ab and a local span span_b. when the request is over , SERVICE_B record the last log at methed below : 
@Override
	public void logStoppedSpan(Span parent, Span span) {
		log("Stopped span|{}", span);
		if (parent != null) {
			MDC.put(Span.SPAN_ID_NAME, Span.idToHex(parent.getSpanId()));
			MDC.put(Span.SPAN_EXPORT_NAME, String.valueOf(parent.isExportable()));
		}
		else {
			MDC.remove(Span.SPAN_ID_NAME);
			MDC.remove(Span.SPAN_EXPORT_NAME);
			MDC.remove(Span.TRACE_ID_NAME);
		}
	}
Because span_b has a parent span sanp_ab,it always goes to the branch 'if (parent != null) {',and MDC remain it until gc.yet ,it does't matter at most time,but i think  it will be better if we can clear MDC by hand.it's just my advise.

**Comment by marcingrzejszczak** [comment] 2016-04-21 15:07
@zywei - thanks for pointing it out - it should be fixed. If you can we'd be more than happy to hear some feedback from you if the problem is gone with the current version in master.

**Closed** 2016-04-21 15:06 UTC
Labels: in progress, question
