### ISSUE TITLE
Issue with the sleuth Baggage for setting local fields using property "spring.sleuth.baggage.local-fields"

### ISSUE THREAD

**Issue by bharatvarshney2022** [spring-cloud/spring-cloud-sleuth#2138] opened 2022-03-29 03:39 UTC
**Describe the bug**
Issue with the sleuth Baggage for setting local fields using property "**spring.sleuth.baggage.local-fields"**, "**spring.sleuth.bagdgage.correlation-fields**", understanding is that if we set this property with specified property then local fields(which are not supposed to travel over wire) will be setup and injected in the MDC map. 
Which is not happening currently!!

Whereas if "spring.sleuth.baggage.remote-fields" and "spring.sleuth.bagdgage.correlation-fields" properties are set then its working as expected, values are transferred to MDC automatically and injected in the headers which can be transferred over wire automatically.
Which is working as expected.

**Sample**

E.g 

Version
---------------------------------------------------------------------------
Pom.xml
----------------------------------------------------------------------------
    <spring-boot.version>2.3.7.RELEASE</spring-boot.version>
    <sleuth.version>2.2.6.RELEASE</sleuth.version>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zipkin</artifactId>
      <version>${sleuth.version}</version>
    </dependency>

--------------------------------------------------------------------------------------
application.properties
spring.sleuth.bagdgage.correlation-fields=user_name
spring.sleuth.baggage.local-fields=user_name
-------------------------------------------------------------------------------------
Controller classes if we access like MDC.get("user_name")
**Not able to get the value over here!!!**

-------------------------------------------------------------------------------------
Value of the "user_name" is passed as the header value in the REST API call.
user_name:testing_header

**Comment by marcingrzejszczak** [comment] 2022-03-29 07:14
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

Also please update to the latest version of cloud and boot and please tell us if the problem persists.

**Comment by bharatvarshney2022** [comment] 2022-03-31 08:01
Thanks @marcingrzejszczak for the suggestions. Checked with the latest version, still not worked. 
Will upload the sample code base shortly.

**Comment by tarunlalwani** [comment] 2022-04-06 03:22
@bharatvarshney2022 , please update the latest sample code

**Comment by spring-cloud-issues** [comment] 2022-04-18 13:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-04-25 13:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by norbertwnuk** [comment] 2022-05-27 19:33
I would like ask to re-open this defect, observe exactly the same behavior for `MDC` and `BaggageField.getAllValues()`, when the header is not added to `remote-fields`. At least for `BaggageField.getAllValues()` is seems to be related to `MAP_STRING_STRING_BUILDER` logic. This behavior is inconsistent with what [documentation ](https://docs.spring.io/spring-cloud-sleuth/docs/current-SNAPSHOT/reference/html/project-features.html#features-baggage) says about BaggageField and MDC when combined with local fields.

```
spring:
  sleuth:
    baggage:
      remote-fields:
        - x-request-id
      local-fields:
        - x-request-id-2
      correlation-fields:
        - x-request-id
        - x-request-id-2
      tag-fields:
        - x-request-id
        - x-request-id-2
```

![image](https://user-images.githubusercontent.com/70071/170777282-b94a3138-2439-445d-a2ec-be9712815414.png)

![image](https://user-images.githubusercontent.com/70071/170778217-68394869-70cb-4486-aeab-13f8eb27c020.png)

**Comment by marcingrzejszczak** [comment] 2022-05-30 09:08
Have you configured the BaggageFields to flush on update? Maybe that's why you don't see it yet. Do you have a sample that I could play around with?

**Comment by norbertwnuk** [comment] 2022-05-30 12:09
@marcingrzejszczak  - from what i see flush on update does not change the behavior, the sample code is [here](https://github.com/norbertwnuk/spring-cloud-sleuth-2138).

**Comment by norbertwnuk** [comment] 2022-10-06 12:15
@marcingrzejszczak - can we re-open this issue / should I create a new one - since the failing example has been attached above.

**Comment by grassehh** [comment] 2023-07-11 14:44
Hello, it seems this issue is still present with Spring Boot 3 / Micrometer. I have created an [issue](https://github.com/openzipkin/brave/issues/1376) to Brave because after some analysis it seems to be an implementatiion behavior (Seems to have something to do with the way the correlation fields are stored in `TraceContext.extraList` property).

**Comment by marcingrzejszczak** [comment] 2024-02-09 13:44
The issue seems to be there in Brave

**Closed as not planned by marcingrzejszczak** 2024-02-09 13:44 UTC
Labels: in progress
