### ISSUE TITLE
New span not created when a message is sent to a channel with spring integration

### ISSUE THREAD

**Issue by RanjaniGuru1** [spring-cloud/spring-cloud-sleuth#1118] opened 2018-11-01 07:54 UTC
I am using spring integration and messages are sent across different message channels after processing and I would like to log the spanId and traceId everytime a message is successfully sent to the next channel. I am using a ChannelInterceptorAdapter for this purpose. Tried to log the spanId and spanTraceId available in the message headers and noticed that they are the same across channels. Please let me where I have gone wrong.

Attaching the sample project:
[ChannelInterceptorExample.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2537646/ChannelInterceptorExample.zip)

**Comment by marcingrzejszczak** [comment] 2018-11-02 10:37
Can you please upload this sample to GitHub? Also can you provide the information about the versions used? Are the channels `DirectChannel`s ?

**Comment by RanjaniGuru1** [comment] 2018-11-08 05:52
I have already uploaded the sample with the issue. Attaching again for your reference. And yes, the channels are direct channels.

[ChannelInterceptorExample (1).zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2560466/ChannelInterceptorExample.1.zip)

Also, when I am facing the same issue when there is a REST service call followed by a SOAP service call. I am trying to log the span Id in the interceptor for the SOAP call and the span Id is the same as that logged in the REST service Filter. I am using CXF JAX WS to call the SOAP service.

**Comment by marcingrzejszczak** [comment] 2018-11-14 10:39
I'm sorry your example is extremely complex. You're using Spring Boot with a plugin but you're setting all versions manually. Please go to `start.spring.io`, generate a proper project and try again to see if the problem is still there

**Comment by RanjaniGuru1** [comment] 2018-11-16 18:07
I have generated a project from start.spring.io. Added only the below dependency , as I am using <jms:message-driven-channel-adapter> to listen to the messages.

compile("org.springframework.integration:spring-integration-jms") {
    	exclude group: "org.springframework", module: "spring-jms"
    }

I am still facing the same issue- span id is the same across channels. Please let me know if I have missed something.
Attached the sample project.

[ChannelInterceptorExample2.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2590384/ChannelInterceptorExample2.zip)

**Comment by RanjaniGuru1** [comment] 2018-12-12 09:09
Can you please help me resolve this issue?

**Comment by marcingrzejszczak** [comment] 2019-01-06 15:50
I don't know how to replicate your issue. I can see the sample but what should I do next?

BTW have you checked if the problem is still there with the latest `Finchley` release train version?

**Comment by spring-issuemaster** [comment] 2019-01-15 19:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-01-28 17:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by RanjaniGuru1** [comment] 2019-02-04 09:46
Below are the steps I did to run the sample.
- Downloaded and installed Activemq server.
-  Ran the Activemq server locally.
-  Created a queue named TEST_QUEUE_1  and sent a sample message to this queue. 
-  Did a gradle build of the sample attached and ran the sample as a Spring Boot App.

Attaching the sample again for your reference.
[ChannelInterceptorExample2.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2827293/ChannelInterceptorExample2.zip)

**Comment by TYsewyn** [comment] 2019-07-22 10:24
I tried the provided example with the latest version of Spring Boot 1 (1.5.21.RELEASE) and the latest compatible Spring Cloud release (Edgware.SR6) and I can't replicate the issue within Spring Cloud.
If you remove the custom interceptor, custom logging setup and set the log level of `org.springframework.cloud.sleuth` to debug you can clearly see 2 different spans.

I got following as an example:
```
2019-07-22 12:11:20.038 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Processing message before sending it to the channel
2019-07-22 12:11:20.043 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Parent span is null
2019-07-22 12:11:20.043 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Name of the span will be [message:testQueue1Channel]
2019-07-22 12:11:20.045 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with client send
2019-07-22 12:11:20.049 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Continuing span [Trace: ddcb32f6e28b2efb, Span: ddcb32f6e28b2efb, Parent: null, exportable:true] before handling message
2019-07-22 12:11:20.049 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with server received
2019-07-22 12:11:20.049 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Span [Trace: ddcb32f6e28b2efb, Span: ddcb32f6e28b2efb, Parent: null, exportable:true] successfully continued
2019-07-22 12:11:20.062 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Continuing span [Trace: ddcb32f6e28b2efb, Span: ddcb32f6e28b2efb, Parent: null, exportable:true] after message handled
2019-07-22 12:11:20.062 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with server send
2019-07-22 12:11:20.062 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Completed sending and current span is [Trace: ddcb32f6e28b2efb, Span: ddcb32f6e28b2efb, Parent: null, exportable:true]
2019-07-22 12:11:20.062 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with client received
2019-07-22 12:11:20.063 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,ddcb32f6e28b2efb,true] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Closing messaging span [Trace: ddcb32f6e28b2efb, Span: ddcb32f6e28b2efb, Parent: null, exportable:true]
2019-07-22 12:11:20.063 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-1] o.s.c.s.i.m.TraceChannelInterceptor      : Messaging span [Trace: ddcb32f6e28b2efb, Span: ddcb32f6e28b2efb, Parent: null, exportable:true] successfully closed
2019-07-22 12:11:20.071 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Processing message before sending it to the channel
2019-07-22 12:11:20.071 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Parent span is [Trace: ddcb32f6e28b2efb, Span: ddcb32f6e28b2efb, Parent: null, exportable:true]
2019-07-22 12:11:20.072 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Name of the span will be [message:testQueue2Channel]
2019-07-22 12:11:20.072 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with server received
2019-07-22 12:11:20.072 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Continuing span [Trace: ddcb32f6e28b2efb, Span: 69cbb2efcaa5cf9a, Parent: ddcb32f6e28b2efb, exportable:true] before handling message
2019-07-22 12:11:20.072 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with server received
2019-07-22 12:11:20.073 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Span [Trace: ddcb32f6e28b2efb, Span: 69cbb2efcaa5cf9a, Parent: ddcb32f6e28b2efb, exportable:true] successfully continued
2019-07-22 12:11:20.076 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Continuing span [Trace: ddcb32f6e28b2efb, Span: 69cbb2efcaa5cf9a, Parent: ddcb32f6e28b2efb, exportable:true] after message handled
2019-07-22 12:11:20.076 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with server send
2019-07-22 12:11:20.076 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Completed sending and current span is [Trace: ddcb32f6e28b2efb, Span: 69cbb2efcaa5cf9a, Parent: ddcb32f6e28b2efb, exportable:true]
2019-07-22 12:11:20.076 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Marking span with client received
2019-07-22 12:11:20.076 DEBUG [channel-interceptor-example,ddcb32f6e28b2efb,69cbb2efcaa5cf9a,true] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Closing messaging span [Trace: ddcb32f6e28b2efb, Span: 69cbb2efcaa5cf9a, Parent: ddcb32f6e28b2efb, exportable:true]
2019-07-22 12:11:20.077 DEBUG [channel-interceptor-example,,,] 907 --- [MDB.container-4] o.s.c.s.i.m.TraceChannelInterceptor      : Messaging span [Trace: ddcb32f6e28b2efb, Span: 69cbb2efcaa5cf9a, Parent: ddcb32f6e28b2efb, exportable:true] successfully closed
```

This gives me reason to believe the custom `ChannelInterceptorAdapter` needs to have some changes in order to capture the correct trace and its spans.

**Comment by spring-issuemaster** [comment] 2019-07-29 10:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-08-05 10:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-08-05 10:29 UTC
Labels: feedback-reminder, waiting for feedback
