### ISSUE TITLE
How can i trace RabbitMQ Message in one Trace?

### ISSUE THREAD

**Issue by MrGlaucus** [spring-cloud/spring-cloud-sleuth#801] opened 2017-12-04 06:17 UTC
I tried to trace rabbitmq producer and consumer, but they were separate into two traces in zipkin-ui. What should i do to make them one?

**Comment by marcingrzejszczak** [comment] 2017-12-18 15:46
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/792

**Closed by marcingrzejszczak** 2017-12-18 15:46 UTC
