### ISSUE TITLE
Trace context lost after mongo call

### ISSUE THREAD

**Issue by beltram** [spring-cloud/spring-cloud-sleuth#1204] opened 2019-02-01 16:43 UTC
Bug report
Hi, using latest Spring versions (2.1.2.RELEASE and Cloud Greenwich.RELEASE) it looks like after calling mongo with reactive operators trace context is resetted (ie one cannot get back traceId). If mongo is not called it works as expected.
It looks like this:  
```
tracer.spanId() // has a value
    .flatMap { repo.insert(Person(it)) }
    .flatMap { tracer.spanId() } // is null
```
Reproducer is [here](https://github.com/beltram/sleuth-data-reproducer)
Thank you 😄

**Comment by jntakpe** [comment] 2019-02-04 11:12
Is it related to https://github.com/reactor/reactor-core/pull/1481/files ?

**Comment by jntakpe** [comment] 2019-02-04 13:22
@bsideup Thoughts ?

**Comment by bsideup** [comment] 2019-02-04 13:24
@jntakpe no, not related (the PR you linked is not integrated yet).

Looks more like a duplicate of #1203 and #1199

**Comment by jntakpe** [comment] 2019-02-04 13:54
We have experienced the #1199. We solved it by retrieving trace information from request.

**Comment by beltram** [comment] 2019-02-05 16:23
For information issue appeared on spring-cloud-sleuth-core:2.1.0.M2

**Comment by marcingrzejszczak** [comment] 2019-02-12 15:42
@beltram should I just clone https://github.com/beltram/sleuth-data-reproducer and run `./gradlew clean build` to replicate the problem?

**Comment by beltram** [comment] 2019-02-12 17:36
@marcingrzejszczak sorry missed the readme on this one. Run ```./gradlew clean test``` instead all logic is in test classes

**Comment by jntakpe** [comment] 2019-02-14 08:40
@marcingrzejszczak any issues regarding this issue ?

**Closed** 2019-02-21 12:37 UTC
Labels: feedback-provided

**Comment by hsk3mis** [comment] 2019-05-15 12:14
@beltram Hi. Did you manage to solve your issue?
If yes, did you manage to log traceId's from the Mongo driver logs? Eg.
`org.mongodb.driver.protocol.command      : Sending command '{ "find" : "deliveryMethods", "batchSize" : 2147483647 }'`
