### ISSUE TITLE
Missing traceId in Kafka listener when consuming in batches

### ISSUE THREAD

**Issue by edetorresf** [spring-cloud/spring-cloud-sleuth#1721] opened 2020-08-28 10:35 UTC
Trace info is lost and current span is null when consuming in batches from a KafkaListener.

I'm working with

- Spring Boot 2.3.3
- Spring Kafka 2.5.5
- Spring Cloud Starter Sleuth 2.4.4

I have a listener like
```
@KafkaListener(topics = "topic")
public void receiveMessage(List<String> messages) {
        messages.forEach(log::info);
}
```
And following property in application.yml:
`spring.kafka.listener.type: batch`

If I remove the property then traceId is back

**Comment by marcingrzejszczak** [comment] 2020-09-10 11:21
Can you create a small sample that replicates this problem?

**Comment by spring-issuemaster** [comment] 2020-09-17 11:25
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-09-24 11:25
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by KostasD21** [comment] 2021-01-26 15:34
Same issue for me with the following versions:

* Spring boot 2.4.1
* Spring kafka 2.6.4
* Spring Cloud Starter Sleuth 3.0.0

A sample project for this case is below:

https://github.com/KostasD21/SleuthAndKafkaPoc

The property spring.kafka.listener.type: batch seems to break the things.

I would appreaciate if you could advise me for some workaround.

**Comment by jonatan-ivanov** [comment] 2021-01-28 22:50
@KostasD21 I was able to repro this issue using your sample project, thanks for that (btw [here's some help for local Kafka](https://github.com/jonatan-ivanov/local-services/blob/main/kafka/docker-compose.yml)).

As I was debugging it, I found that the batch and the non-batch scenarios are handled differently (see: [KafkaMessageListenerContainer](https://github.com/spring-projects/spring-kafka/blob/f2f54cadcc333d93818efa9cabff2b3d57112e56/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1538-L1545)). This is so different that there are two different components that are calling your `@KafkaListener`.

The root cause is that the non-batch listener is decorated by Sleuth, while the batch listener is not. If you stop the execution in `KafkaMessageListenerContainer` where the `listener` or the `batchListener` is used you will see that one of them is proxied, the other one is not (by `MessageListenerMethodInterceptor`):

```
org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter$$EnhancerBySpringCGLIB$$2296d4d9
org.springframework.kafka.listener.adapter.BatchMessagingMessageListenerAdapter
```

This explains why batch does not have traceIds so I looked into where the proxy is set-up:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/6b0ceb7ede2a8e3d842be72350c728628d199407/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/instrument/messaging/SleuthKafkaAspect.java#L105-L109

Unfortunately this scenario is not supported which does make some sense since if there are 10 incoming messages with different traceIDs, which traceId would you pick to propagate to the consumer?
If you would like this feature to be implemented, could you please open a new issue as a feature request (please reference this one)?

**Closed by jonatan-ivanov** 2021-01-28 22:50 UTC
Labels: for: team-attention

**Comment by Johny-Ch** [comment] 2022-05-25 21:33
Is this fixed in recent versions?

**Comment by jonatan-ivanov** [comment] 2022-05-25 21:47
@Johny-Ch No, currently this is not supported. If there are 10 incoming messages with different traceIDs, which traceId would you pick to propagate to the consumer?

**Comment by andreas-ajaib** [comment] 2024-04-10 15:54
I'd would appreciate that this feature is implemented.

Regarding, this question
> Unfortunately this scenario is not supported which does make some sense since if there are 10 incoming messages with different traceIDs, which traceId would you pick to propagate to the consumer?

How if we just give new/start new tracing. Any tracing (as long as it's consistent) is better than no tracing at all. I am having difficulties debugging my app because the log is scattered and it has no tracing at all.

**Comment by jonatan-ivanov** [comment] 2024-04-14 04:40
Sleuth reached the [end of its OSS support](https://spring.io/projects/spring-cloud-sleuth#support) timeline. We encourage to migrate to Micrometer Tracing that fixes issues that Sleuth had.

**Comment by rajshreeee** [comment] 2025-05-28 06:48
Facing the same issue in micrometer too

**Comment by jonatan-ivanov** [comment] 2025-05-30 18:51
@rajshreeee I understand that but that but this is the issue tracker of Sleuth: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1721#issuecomment-2053898941

Also, please see this comment: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1721#issuecomment-769451083
I think the big question is still:
>Unfortunately this scenario is not supported which does make some sense since if there are 10 incoming messages with different traceIDs, which traceId would you pick to propagate to the consumer?

If you have any suggestions about how to implement this, please open a new issue for Spring Kafka where this instrumentation lives.
