### ISSUE TITLE
Loss of current trace when encountering an hystrix timeout with a FeignClient

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-sleuth#680] opened 2017-08-16 08:32 UTC
If there is a  timeout for a FeignClient, with hystrix enabled and using RX Java, then the traceId is lost in doOnError or the following maps. This is quite inconvenient, because if you mitigate the error and then want to do some other processing in the following maps (ie calling other services), you've lost the trace.

OK this is quite complicated to explain in english, I have a working repro here : https://github.com/snussbaumer/sleuth-hystrix-traceid-loss-repro

It's self contained in a single test that should IMHO pass, but fails as of today : 

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = ReproApplication.class, webEnvironment = WebEnvironment.DEFINED_PORT, properties = {
        "server.port=9009", "feign.hystrix.enabled=true" })
@Slf4j
public class ReproApplicationTests {

    @Inject
    private ReproClient reproClient;

    @Inject
    private Tracer tracer;

    @ToString
    private static class TraceIds {
        String testTraceId;
        String inDoOnErrorTraceId;
        String inMapTraceId;
    }

    @Test
    public void test() {
        TraceIds traceIds = new TraceIds();
        traceIds.testTraceId = idToHex(tracer.createSpan("test").getTraceId());
        log.info("Starting test");
        String result = reproClient.repro() //
                .doOnError(throwable -> {
                    log.error("In doOnError with error {}", throwable.getMessage());
                    traceIds.inDoOnErrorTraceId = idToHex(tracer.getCurrentSpan().getTraceId());
                }) //
                .onErrorReturn(throwable -> new ReproApplication.ReproDto("there was an error")) //
                .map(reproDto -> {
                    log.error("In map");
                    traceIds.inMapTraceId = idToHex(tracer.getCurrentSpan().getTraceId());
                    return reproDto.getMessage();
                }) //
                .toBlocking().first();

        log.info("{}", traceIds);
        assertThat(result).isEqualTo("there was an error");
        // This is what I get : testTraceIds != inDoOnErrorTraceId and inDoOnErrorTraceId == inMapTraceId
        // But I rather expect the following which fails as of today :
        assertThat(traceIds.testTraceId) //
                .isEqualTo(traceIds.inDoOnErrorTraceId) //
                .isEqualTo(traceIds.inMapTraceId);
    }

    @SpringBootApplication
    @RestController("/repro")
    @EnableFeignClients
    public static class ReproApplication {

        @Data
        @AllArgsConstructor
        public static class ReproDto {
            private String message;
        }

        @FeignClient(name = "repro", url = "127.0.0.1:9009")
        public interface ReproClient {
            @RequestMapping(method = RequestMethod.GET, value = "/repro")
            Observable<ReproDto> repro();
        }

        @GetMapping
        public ReproDto repro() throws InterruptedException {
            Thread.sleep(1000);
            return new ReproDto("pheeeew this was long");
        }

        public static void main(String[] args) {
            SpringApplication.run(ReproApplication.class, args);
        }
    }

}
```

**Comment by marcingrzejszczak** [comment] 2017-08-18 11:03
Thanks for filing this issue - it's really interesting...

I've turned on the debug logs and I got this:

```
2017-08-18 12:59:23.000 DEBUG [bootstrap,,,] 31753 --- [nio-9009-exec-1] o.s.c.sleuth.instrument.web.TraceFilter  : Found a parent span [Trace: 1e9a0ff5d25e16c6, Span: a7f718c881006425, Parent: 1e9a0ff5d25e16c6, exportable:false] in the request
2017-08-18 12:59:23.001 DEBUG [bootstrap,1e9a0ff5d25e16c6,a7f718c881006425,false] 31753 --- [nio-9009-exec-1] o.s.c.sleuth.instrument.web.TraceFilter  : Parent span is [Trace: 1e9a0ff5d25e16c6, Span: a7f718c881006425, Parent: 1e9a0ff5d25e16c6, exportable:false]
2017-08-18 12:59:23.011 DEBUG [bootstrap,1e9a0ff5d25e16c6,a7f718c881006425,false] 31753 --- [nio-9009-exec-1] o.s.c.s.i.web.TraceHandlerInterceptor    : Handling span [Trace: 1e9a0ff5d25e16c6, Span: a7f718c881006425, Parent: 1e9a0ff5d25e16c6, exportable:false]
2017-08-18 12:59:23.011 DEBUG [bootstrap,1e9a0ff5d25e16c6,a7f718c881006425,false] 31753 --- [nio-9009-exec-1] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a method tag with value [repro] to a span [Trace: 1e9a0ff5d25e16c6, Span: a7f718c881006425, Parent: 1e9a0ff5d25e16c6, exportable:false]
2017-08-18 12:59:23.011 DEBUG [bootstrap,1e9a0ff5d25e16c6,a7f718c881006425,false] 31753 --- [nio-9009-exec-1] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a class tag with value [ReproApplication] to a span [Trace: 1e9a0ff5d25e16c6, Span: a7f718c881006425, Parent: 1e9a0ff5d25e16c6, exportable:false]
2017-08-18 12:59:23.870 DEBUG [bootstrap,4afb90a3ac2958a6,4afb90a3ac2958a6,false] 31753 --- [ HystrixTimer-1] ConcurrencyStrategy$HystrixTraceCallable : Creating new span [Trace: 4afb90a3ac2958a6, Span: 4afb90a3ac2958a6, Parent: null, exportable:false]
2017-08-18 12:59:23.877 ERROR [bootstrap,4afb90a3ac2958a6,4afb90a3ac2958a6,false] 31753 --- [ HystrixTimer-1] com.example.repro.ReproApplicationTests  : In doOnError with error ReproClient#repro() timed-out and no fallback available.
2017-08-18 12:59:23.879 ERROR [bootstrap,4afb90a3ac2958a6,4afb90a3ac2958a6,false] 31753 --- [ HystrixTimer-1] com.example.repro.ReproApplicationTests  : In map
2017-08-18 12:59:23.881 DEBUG [bootstrap,4afb90a3ac2958a6,4afb90a3ac2958a6,false] 31753 --- [ HystrixTimer-1] ConcurrencyStrategy$HystrixTraceCallable : Closing span since it was created[Trace: 4afb90a3ac2958a6, Span: 4afb90a3ac2958a6, Parent: null, exportable:false]
2017-08-18 12:59:23.881  INFO [bootstrap,1e9a0ff5d25e16c6,1e9a0ff5d25e16c6,false] 31753 --- [           main] com.example.repro.ReproApplicationTests  : ReproApplicationTests.TraceIds(testTraceId=1e9a0ff5d25e16c6, inDoOnErrorTraceId=4afb90a3ac2958a6, inMapTraceId=4afb90a3ac2958a6)

org.junit.ComparisonFailure: 
Expected :"4afb90a3ac2958a6"
Actual   :"1e9a0ff5d25e16c6"
 <Click to see difference>
```

Note these lines:

```
2017-08-18 12:59:23.011 DEBUG [bootstrap,1e9a0ff5d25e16c6,a7f718c881006425,false] 31753 --- [nio-9009-exec-1] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a class tag with value [ReproApplication] to a span [Trace: 1e9a0ff5d25e16c6, Span: a7f718c881006425, Parent: 1e9a0ff5d25e16c6, exportable:false]
2017-08-18 12:59:23.870 DEBUG [bootstrap,4afb90a3ac2958a6,4afb90a3ac2958a6,false] 31753 --- [ HystrixTimer-1] ConcurrencyStrategy$HystrixTraceCallable : Creating new span [Trace: 4afb90a3ac2958a6, Span: 4afb90a3ac2958a6, Parent: null, exportable:false]
```

When `doOnError` is executed - it gets executed in a separate `HystrixTimer-1` thread. For some reason the span over there is not passed properly from the previous thread, that's why it's creating a new one. The funny thing is that my IDE can't break in that thread which is very interesting. The problem is not with Feign but with Hystrix + RxJava + Sleuth integration. I'll debug this further on and give it a thought but wanted you to know how things are going :)

**Comment by marcingrzejszczak** [comment] 2017-08-18 12:00
I've made a PR with an approach that works but is terrible (I need to access packaged scope fields of the `HystrixTimer`(https://github.com/snussbaumer/sleuth-hystrix-traceid-loss-repro/pull/1#pullrequestreview-57181208) . You can use it as a workaround for now but I'll try to think in the meantime how to make this look less insane... Although I don't have much hope ATM ;)

**Comment by snussbaumer** [comment] 2017-08-18 12:35
Allright, thanks a lot ! Yes I saw that with the HystrixTimer, I should've mentioned it, sorry :roll_eyes: 

Thanks for the workaround ... in the meantime I think I'm just going to increase the timeouts in my specific case (not a user facing API, just a backend background process, so it's allright), but I think it's quite important to fix for other as well, and maybe for me later also. 

In fact what's most "fun" is when you use `flatMap(feignClient::method)`, as calls to the feignClient are made in parallel, you can have some of the subsequent call that have the right trace, and some who've a new trace (if a timeout occured), so you get a mix of the two in parallel, just great :smile:

**Comment by marcingrzejszczak** [comment] 2017-09-04 10:34
Let's close this issue until sth happens here - https://github.com/Netflix/Hystrix/issues/1671

**Closed by marcingrzejszczak** 2017-09-04 10:34 UTC
Labels: backlog, discussion, help wanted
