### ISSUE TITLE
Project startup suspension problem

### ISSUE THREAD

**Issue by LoulanGithub** [spring-cloud/spring-cloud-sleuth#1682] opened 2020-07-09 07:12 UTC
## Problem
if spring-session-data-Redis and Spring-cloud-starter-zipkin run in a Maven project, it causes a startup pause.

(springboot 2.2.8.RELEASE ; spring-cloud Hoxton.SR6 )

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>
```

**Comment by marcingrzejszczak** [comment] 2020-07-09 07:52
It rings a bell... Can you check the latest 2.2.x snapshots and see if the problem persists?

**Comment by LoulanGithub** [comment] 2020-07-10 07:51
2.2.9 It hasn't been officially released yet, so I'll stick with the stable old version for now

**Comment by marcingrzejszczak** [comment] 2020-07-10 12:23
Yes, my question is, can you try to use Sleuth's snapshots to see if the problem is still there. Cause if not then I'll close this issue cause the problem has already been resolved?

**Comment by spring-issuemaster** [comment] 2020-07-17 12:27
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-07-24 12:27
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-07-24 12:27 UTC
Labels: feedback-reminder, waiting for feedback
