### ISSUE TITLE
Improper order of 

### ISSUE THREAD

**Issue by czujnik81** [spring-cloud/spring-cloud-sleuth#913] opened 2018-03-23 07:41 UTC
Sleuth  v Finchley.M9
While processing request between Spring Cloud Gateway and final service Sleuth improperly ordered events. Please see attached screenshot.
![screen shot 2018-03-23 at 08 18 19](https://user-images.githubusercontent.com/13945903/37816989-61f31dfa-2e75-11e8-933d-01e9773cbc5a.png)

To reproduce:
Use: https://github.com/czujnik81/api-gateway.git and https://github.com/czujnik81/final-service.git
Define ZIPKIN_URL env variable to point working ZIPKIN server (eg. `http://localhost:9411`) if api-gateway and final-service are running on different servers for gateway define also HOST env variable eg. `localhost:9411`. To run service url to eg. `http://localhost:8080/contract/abc/file`
Also notice improper client address on screenshot

**Comment by adriancole** [comment] 2018-03-23 09:21
I looked at this and what you are seeing is likely explained by where measurements occur from. So, it isn't out-of-order, rather this is literally when the frameworks thought they were done.

On the client side, it is low-level netty bubbling up through reactor. The server is being measured from the servlet api. This is why you see the client think it is done a bit before the server did.

My guess is this isn't going to happen as much in practice as usually you will have different machines (which can likely wash out the 100us you are seeing here from client server on the same host).

While there are probably some things to slightly adjust in the servlet side, I wanted to give you an early answer that this isn't going to be handled with priority. If we get a lot of reports, we might, but right now it is explainable.

Hope this helps

**Comment by czujnik81** [comment] 2018-03-23 09:27
I understand the reason, but the thing is that in the same runtime environment sometimes it's look like mentioned and sometimes it's properly ordered.
It's not high priority, but it's kind of deficiency.

**Comment by adriancole** [comment] 2018-03-23 09:32
anyway I will have a look, just wanted to warn you it might not resolve
today :P

**Comment by adriancole** [comment] 2018-03-23 09:33
PS thanks for the report. you did a good job

**Comment by adriancole** [comment] 2018-03-23 09:41
so the idea isn't lost.. one way to handle this it to move the server span lower on the stack, ex to netty for example. There would be some gotchas to handle (ex how to share http.route with netty), but it is possible (especially as brave has a netty filter already)

**Comment by adriancole** [comment] 2018-03-23 09:42
even if we don't recommend something like this routinely, it could make sense for gateways. cc @jkschneider

**Comment by guanyalei** [comment] 2018-05-21 11:54
I ran into similar issue in testing environment with Finchley.BUILD-SNAPSHOT. Client side requests REST service, which is deployed on the same machine with client, by RestTemplate.getForObject(). And I see CR happens before SS.
![image](https://user-images.githubusercontent.com/17233789/40305863-f8b1948c-5d2e-11e8-95f5-eb4e381aa0b6.png)
However, sequence of SS and CR of feign client(@FeignClient) looks correct in the same scenario.

**Comment by marcingrzejszczak** [comment] 2018-05-21 12:11
Any chance for a sample? Also does is always end like this for every request?

**Comment by guanyalei** [comment] 2018-05-22 02:26
Yes, always the same for every request. Attached service-ribbon and service-hi project in my previous screenshot for your reference. Zipkin server jar file is the latest zipkin-server-2.8.3-exec.jar.
[spring-cloud-client.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2024712/spring-cloud-client.zip)
[spring-cloud-service-ribbon.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2024713/spring-cloud-service-ribbon.zip)

**Comment by marcingrzejszczak** [comment] 2018-05-23 10:05
Works on my machine ;)

<img width="901" alt="screen shot 2018-05-23 at 12 04 04" src="https://user-images.githubusercontent.com/3297437/40418060-9f7c8f1c-5e81-11e8-9457-5467da8e7afc.png">

**Comment by marcingrzejszczak** [comment] 2018-05-23 10:06
I just unpacked and ran your examples. Should I do sth else to replicate the issue?

**Comment by guanyalei** [comment] 2018-05-23 13:30
It is an extremely simple demo to help me learn spring cloud basic. I don't have any special configuration for eureka server and zipkin server.

**Comment by guanyalei** [comment] 2018-05-23 13:42
My host OS is a windows 10 pro, and I launched these demo services from eclipse Mars version. Does that make difference with your test?

**Comment by marcingrzejszczak** [comment] 2018-05-23 14:06
I have a mac and I've ran the apps from Intellij. I don't really know how to help you with this one since I can't replicate it :| Maybe if someone else has the same problem it will be easier to reproduce it.

**Comment by guanyalei** [comment] 2018-05-23 14:39
Thanks all the same for your help. Maybe I will figure it out myself after deeper understanding of spring cloud :)

**Comment by marcingrzejszczak** [comment] 2020-01-16 08:12
Is this still a problem?

**Comment by marcingrzejszczak** [comment] 2020-01-16 08:25
Ok then, let's close it. We'll reopen it if someone confirms that the issue is back.

**Closed by marcingrzejszczak** 2020-01-16 08:25 UTC
Labels: bug, feedback-provided, icebox
