### ISSUE TITLE
DispatcherServlet on throwing the exception is not having tracer/span of the request that caused this error

### ISSUE THREAD

**Issue by aj070** [spring-cloud/spring-cloud-sleuth#579] opened 2017-04-28 11:46 UTC
Scenario:

@RequestMapping(value = "/test", method = RequestMethod.GET)
    public void om3() {
         String k=null;
        System.out.println(k.toLowerCase());
    }

On enabling DispatcherServlet to DEBUG, I can see tracer/span in the incoming request. But as in the example scenario the output will throw null pointer exception. In the exception I'm getting
 ERROR [bootstrap,,,]
where there is no tracerId or spanId.. Is this the desired behaviour? If so, what is the work around. It is actually difficult to correlate if an error happens.

**Comment by shakuzen** [comment] 2017-04-28 11:52
I believe this is a duplicate of #542

**Comment by marcingrzejszczak** [comment] 2017-04-28 11:54
Yeah that's a duplicate of #542 . @aj070 can you try to apply the suggested practice of using for example https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-error-handling ?

**Closed by marcingrzejszczak** 2017-04-28 11:54 UTC
Labels: duplicate

**Comment by aj070** [comment] 2017-04-28 15:31
My bad that I didn't do proper research before raising the issue. Anyways thanks
