### ISSUE TITLE
Trace context not available with WebFlux

### ISSUE THREAD

**Issue by jumal** [spring-cloud/spring-cloud-sleuth#1143] opened 2018-11-24 09:07 UTC
Bug report

The trace context is not always available with WebFlux.

* Spring Boot version: 2.1.0
* Spring Cloud version: Greenwich M3. Same issue with Greenwich M2. No issue with Greenwich M1
* Sample project: https://github.com/jumal/sleuth-webflux-no-trace-context-issue 

Trying to access propagated extra fields fails due to the unavailability of the trace context in Webflux.

The following code, that used to work with Spring Cloud Finchley and Greenwich M1, does not work anymore with Spring Cloud Greenwich M2 and M3:

* application.properties
```
spring.sleuth.propagation-keys=X-Field2
```

* Test
```
    webClient
                .post().uri("/test")
                .contentType(APPLICATION_JSON)
                .accept(APPLICATION_JSON)
                .header("X-Field2", "field2")
                .body(just(entity), TestEntity.class)
                .exchange();
```

* Handler
```
    Mono<ServerResponse> save(ServerRequest request) {
        return request.bodyToMono(TestEntity.class)
                .map(TestEntity::setContext)
                .flatMap(repository::save)
                .flatMap(entity -> ok().build());
    }
```

* TestEntity
```
    TestEntity setContext() {
        field2 = ExtraFieldPropagation.get("X-Field2");
        return this;
    }
```

ExtraFieldPropagation.get("X-Field2") returns null because the trace context is not available.

**Comment by jumal** [comment] 2018-11-24 09:19
Added sample project to reproduce the issue:https://github.com/jumal/sleuth-webflux-no-trace-context-issue

**Comment by riba2101** [comment] 2019-01-15 11:37
Hi there,

I've found a similar issue when used in a ReactiveAuthenticationManager with ExtraFieldPropagation.set on a client the context is null and on the server side, ExtraFieldPropagation.get returns null.

ReactiveAuthenticationManager.authenticate calls server and tries to set some fields that should be logged/used on the server side

**Comment by anatoliy-balakirev** [comment] 2019-01-28 15:59
Not exactly the same, but seems to be similar:
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1199

**Comment by marcingrzejszczak** [comment] 2019-01-28 16:00
Absolutely. I had a chat with @bsideup and he mentioned that there's a bug in Reactor.

**Comment by bsideup** [comment] 2019-01-28 16:02
@marcingrzejszczak just to clarify:
This is not a bug in Reactor, rather in Sleuth's Reactor integration, but we're working on native trac(k)ing support in Reactor Core (to be used by Sleuth) where the bug should be fixed:
https://github.com/reactor/reactor-core/pull/1481

**Comment by marcingrzejszczak** [comment] 2019-01-28 16:03
Ah thanks for the clarification @bsideup. I must have misunderstood you.

**Closed** 2019-02-21 12:37 UTC
Labels: bug, in progress
