### ISSUE TITLE
Upgrade to 2.2.7 appears to be causing unexplained RedisCommandTimeoutException with Reactive Redis

### ISSUE THREAD

**Issue by chadlwilson** [spring-cloud/spring-cloud-sleuth#1849] opened 2021-02-15 14:44 UTC
**Describe the bug**

We recently bumped from `2.2.6` to `2.2.7` (`Hoxton.SR10`), after which our `ReactiveStringRedisTemplate` usage seemed to eventually lock up and all commands get stuck/time out. 

Apologies for the vague report; as I haven't really dug into it in depth at this stage, however since 
* this lib upgrade was the only related thing we changed
* there did not appear to be any transitive dependency changes in our case
* there appear to be some changes related to Redis usage/auto-configuration (#1756) in [the diff](https://github.com/spring-cloud/spring-cloud-sleuth/compare/v2.2.6.RELEASE...v2.2.7.RELEASE)

I thought I'd try and ask here first before we dig deeper. Is it possible there was some unintended negative impact for Reactive Redis usage in certain cases? Not quite sure how to debug further, as Redis command tracing has generally "just worked" for us.

**Versions**
Spring Boot: `2.3.8`
Spring: `5.2.12`
Spring Data Redis: `2.3.6`
Lettuce: `5.3.6`

**Comment by jonatan-ivanov** [comment] 2021-02-22 20:52
@chadlwilson Do you use `spring-cloud-dependencies` and updated that to `Hoxton.SR10` or did you update just the Sleuth dependencies?
Could you please create a minimal sample that reproduces the issue?

**Comment by chadlwilson** [comment] 2021-02-23 12:08
Thanks for your reply @jonatan-ivanov .

Currently we just depend on Spring Cloud via non dependency-managed direct versions rather than the release trains. We use the Spring dependency-management gradle plugin for other dependencies which is where the versions above are coming from (via `spring-boot-starter-*`) but we had just never figured out how to apply that to the Spring Cloud release train versions.

```groovy
    implementation ('org.springframework.cloud:spring-cloud-starter-zipkin:2.2.7.RELEASE') {
        exclude module: 'spring-security-crypto'
        exclude module: 'zipkin-sender-kafka'
        exclude module: 'zipkin-sender-activemq-client'
        exclude module: 'zipkin-sender-amqp-client'
    }
```

If you think that could be relevant somehow regarding transitive dependency versions being screwed up, I could switch to dependency management off `Hoxton.SR10` and see if the resolved versions change for anything relevant.

It's not easy to create a minimal sample, so was hoping there might be some pointers about where the problem might be given some more context about the changes in `2.2.7` regarding Sleuth and Redis, but if not (and no-one else has seen a problem) I guess we'll need to go down that road.

**Comment by jonatan-ivanov** [comment] 2021-02-24 23:41
This should do the trick: `implementation  platform('org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR10')`
As I read the original description, I had two ideas:
1. With the update, the issue is related to some dependencies (reactor, redis, data) and not related to Sleuth
2. There was a change in the reactive/redis instrumentation and this is a bug in sleuth

I would definitely try two things:
1. Do you experience the issue if you disable sleuth instrumentation
 - overall: `spring.sleuth.enabled`
 - for redis: `spring.sleuth.redis.enabled`
 - for reactor: `spring.sleuth.reactor.enabled`
2. Try to use `spring-cloud-dependencies`, also there is `org.springframework.data:spring-data-bom`

I'm not very familiar with the changes around reactive/redis instrumentation, @marcingrzejszczak might have more info/ideas.

**Comment by spring-cloud-issues** [comment] 2021-03-24 11:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-03-31 11:18
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-03-31 11:18 UTC
Labels: feedback-reminder, waiting for feedback
