### ISSUE TITLE
Version 3.1.7 stopped working with spring-session-data-redis

### ISSUE THREAD

**Issue by tpaan** [spring-cloud/spring-cloud-sleuth#2265] opened 2023-02-27 11:04 UTC
My project has the following dependencies among others:
- spring-cloud-dependencies 2021.0.6
- spring-boot-starter-data-redis 2.7.9
- spring-session-data-redis 2.7.0
- spring-cloud-starter-sleuth 3.1.7

Updating `spring-cloud-dependencies` from 2021.0.5 to 2021.0.6 updated `spring-cloud-sleuth` from 3.1.5 to 3.1.7. Now the application does not work anymore. Application starts but all requests cause an `IllegalStateException`. My guess is it is because [this commit](https://github.com/spring-cloud/spring-cloud-sleuth/commit/07ff40a5aaafde2aba539e7292cfe4c32a1945aa) in 3.1.7 and `spring-session-data-redis` 2.7.0 don't work together. 

If I remove `spring-session-data-redis` dependency everything works.

If I downgrade `spring-cloud-sleuth` to 3.1.6 by using `ext['spring-cloud-sleuth.version'] = '3.1.6'` everything works.

Here is the stack trace:
```
java.lang.IllegalStateException: Could not access method or field: class org.springframework.util.ReflectionUtils cannot access a member of class org.springframework.cloud.sleuth.instrument.session.TraceReactiveSessionRepository with modifiers "public"
	at org.springframework.util.ReflectionUtils.handleReflectionException(ReflectionUtils.java:107)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.ui.LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.ui.LoginPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.oauth2.client.web.server.authentication.OAuth2LoginAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.oauth2.client.web.server.OAuth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.util.ReflectionUtils.handleReflectionException(ReflectionUtils.java:107)
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:285)
		at org.springframework.cloud.sleuth.instrument.session.TraceSessionRepositoryAspect.callMethodOnWrappedObject(TraceSessionRepositoryAspect.java:82)
		at org.springframework.cloud.sleuth.instrument.session.TraceSessionRepositoryAspect.wrapReactiveSessionRepository(TraceSessionRepositoryAspect.java:98)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
		at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
		at org.springframework.session.data.redis.ReactiveRedisSessionRepository$$EnhancerBySpringCGLIB$$ba7fd00e.createSession(<generated>)
		at org.springframework.session.web.server.session.SpringSessionWebSessionStore.createWebSession(SpringSessionWebSessionStore.java:81)
		at org.springframework.web.server.session.DefaultWebSessionManager.createWebSession(DefaultWebSessionManager.java:92)
		at org.springframework.web.server.session.DefaultWebSessionManager.lambda$getSession$2(DefaultWebSessionManager.java:87)
```

**Comment by marcingrzejszczak** [comment] 2023-03-07 12:14
Do you set any project versions manually? This seems like a problem with versions

**Comment by tpaan** [comment] 2023-03-07 12:35
> Do you set any project versions manually? This seems like a problem with versions

I have only set `org.springframework.boot` version to `2.7.9` and `spring-cloud-dependencies` version to `2021.0.6`. Spring Boot `2.7.9` uses version `2.7.0` of `spring-session-data-redis` which is what I get when I add `org.springframework.session:spring-session-data-redis` dependency.

**Comment by marcingrzejszczak** [comment] 2023-03-07 12:51
Can you create a small java maven project that replicates this? I'm surprised that we get such an exception. Sth maybe changed in the internals of Spring and aop related code works in a different way :thinking:

**Comment by SabareeshGC** [comment] 2023-03-10 16:28
seems it is happening with spring-boot 2.7.8 as well on spring cloud 2021.0.6

**Comment by marcingrzejszczak** [comment] 2023-03-10 16:35
Fixed via https://github.com/spring-cloud/spring-cloud-sleuth/commit/5cedfb4cb3b63ab94d7f0e68c3c87738c29d0fa4

**Comment by marcingrzejszczak** [comment] 2023-03-10 16:36
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/2267

**Closed as completed by marcingrzejszczak** 2023-03-10 16:35 UTC
Labels: status: duplicate
