### ISSUE TITLE
Scheduled methods do not log trace id when they throw

### ISSUE THREAD

**Issue by MariellHoversholm-Paf** [spring-cloud/spring-cloud-sleuth#2085] opened 2021-12-21 08:05 UTC
**Describe the bug**
When throwing an exception in a `@Scheduled` method, Sleuth does not log a trace id.

**Sample**
The following code should do it:

```java
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class SchedulingService {
  @Scheduled(fixedRate = 10_000L)
  public void scheduledException() {
    throw new RuntimeException("Scheduled exception");
  }
}
```

I have created a minimal project here: https://github.com/MariellHoversholm-Paf/sleuth-exception-no-traceid

There is a controller that also proves it _does_ work as it logs the trace id through REST requests. See the test output here: https://github.com/MariellHoversholm-Paf/sleuth-exception-no-traceid/runs/4592123878?check_suite_focus=true#step:4:10835

This is done with the `spring-cloud-dependencies` version of `2021.0.0`, which specifies Sleuth [v3.1.0](https://github.com/spring-cloud/spring-cloud-sleuth/tree/v3.1.0).

**Comment by MariellHoversholm-Paf** [comment] 2021-12-28 12:55
I noticed today when checking on the issue that I had made a private repository. I apologise for this; it has been publicised.

Happy new year's!

**Comment by jonatan-ivanov** [comment] 2022-01-05 20:48
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/1729 that was superseded by https://github.com/spring-projects/spring-framework/issues/26533

**Closed by jonatan-ivanov** 2022-01-05 20:48 UTC
Labels: waiting-for-triage

**Comment by MariellHoversholm-Paf** [comment] 2022-01-06 05:41
> I'm closing this since it seems to be a duplicate of #1729 that was superseded by [spring-projects/spring-framework#26533](https://github.com/spring-projects/spring-framework/issues/26533)
> 
> Please let us know if this is a different issue and we should reopen.

This is the same issue! Thanks a lot, I appreciate the time spent on triage.
