### ISSUE TITLE
Regression: servlet context path and management.endpoints.web.base-path=/

### ISSUE THREAD

**Issue by ask4gilles** [spring-cloud/spring-cloud-sleuth#1195] opened 2019-01-27 09:29 UTC
Hi,
As discussed with @marcingrzejszczak  on Gitter.
Given an application with a servlet-context path and a the base actuator path set to /

```
server.servlet.context-path=/app
management.endpoints.web.base-path=/
```
Then the export flag is set to **false**
```
INFO [appName,89c28383facaa413,89c28383facaa413,false]
```
See sample project here:
https://github.com/ask4gilles/sleuthzipkinissue/tree/master/demo

I think a regression was introduced by https://github.com/spring-cloud/spring-cloud-sleuth/pull/1150
in:
```
static Optional<Pattern> getPatternForServerProperties(ServerProperties serverProperties,
				WebEndpointProperties webEndpointProperties) {
			String contextPath = serverProperties.getServlet().getContextPath();
			if (StringUtils.hasText(contextPath)) {
				return Optional.of(Pattern.compile(
						contextPath + webEndpointProperties.getBasePath() + ".*"));
			}
	return Optional.empty();
}
```

In this case, the skip pattern is:

```
/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|.*\.png|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream|/application/.*|/actuator.*|/cloudfoundryapplication|/app.*
```
so everything is skipped because: **/app.***

------
Proposed by @marcingrzejszczak :
* Override skip-pattern:
I tried for example spring.sleuth.web.skip-pattern=/app/info but the /app.* is still added as a skip pattern.
* Define own skipPatternProvider:
```
  @Bean
  public SkipPatternProvider skipPatternProvider() {
    return () -> Pattern.compile("app/info|app/health");
  }
```
It works but it's cumbersome when you have a lot of applications and endpoints.
* "your management path should be app then it wouldn't skip anything else" :
Unfortunately, you can't: management.endpoints.web.base-path has to start with a / so it would be management.endpoints.web.base-path=/app
which resolve to: http://localhost:8080/app/app/info instead of http://localhost:8080/app/info ... :/
-----
The problematic bits is that `webEndpointProperties.getBasePath() ` resolves to an empty string when you define `management.endpoints.web.base-path=/` so you end up skipping your complete servlet-path.
IMO, a way to circumvent this would be, instead of defining a static list of possible endpoints, to retrieve all the exposed endpoints and add them to the base-path.
In this case, this would result in: /app/info, /app/health, etc where app is the servlet-context path and the endpoint name was added to an empty string.

**Comment by marcingrzejszczak** [comment] 2019-01-27 12:00
It's not a regression, we always skip management endpoints (related issue is the one that you mentioned).

You've just defined those endpoints at the root so no wonder that they get skipped. It's enough for you to provide the skip patten manually then and is will work.

**Comment by marcingrzejszczak** [comment] 2019-01-27 13:31
@shakuzen WDYT?

**Comment by shakuzen** [comment] 2019-01-28 06:15
> IMO, a way to circumvent this would be, instead of defining a static list of possible endpoints, to retrieve all the exposed endpoints and add them to the base-path.

I agree, but I don't think Spring Boot provides a programmatic way to retrieve the path for all the exposed Actuator endpoints (I thought there was an issue for it but I can't find it quickly). Also, there are things in the skip pattern that are not Actuator endpoints but may be affected by the possible combinations of servlet context path and management context path.

We should probably do something to fix the current behavior since the configuration (of context/management path) mentioned is allowed by Spring Boot. Though at least there are workarounds available.

**Comment by adriancole** [comment] 2019-01-28 06:46
fyi I had to do some related hacking and noticed a couple suppliers of interest "WebEndpointsSupplier" and "ControllerEndpointsSupplier" which together join to make the link based index on the path /actuator (or whatever the basepath is). While usage is implementation specific (especially noting things like jersey which don't use MVC to implement the actuator), someone following bread-crumbs could poke in this area.

**Comment by ask4gilles** [comment] 2019-01-28 09:37
Could be an option, but as @adriancole pointed, I'd prefer a solution where the `WebEndpointsSupplier` used for example in `WebEndpointDiscoverer` gives you access to `org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer#getEndpoints` which stores the endpoints with their root path already resolved.

**Comment by marcingrzejszczak** [comment] 2019-01-28 15:40
> Could be an option

That would be the ultimate overriding option ;)

> 'd prefer a solution where the WebEndpointsSupplier used for example in WebEndpointDiscoverer gives you access to org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer#getEndpoints which stores the endpoints with their root path already resolved.

Makes sense

**Comment by ask4gilles** [comment] 2019-01-28 15:48
> That would be the ultimate overriding option ;)

`spring.sleuth.web.decline-any-responsibility-skip-pattern` ? :D

**Comment by ask4gilles** [comment] 2019-01-29 15:27
I gave it a quick shot here... https://github.com/spring-cloud/spring-cloud-sleuth/pull/1201

**Comment by marcingrzejszczak** [comment] 2019-02-05 14:54
fixed via https://github.com/spring-cloud/spring-cloud-sleuth/pull/1201#issuecomment-460665940

**Closed by marcingrzejszczak** 2019-02-05 14:54 UTC
Labels: bug
