### ISSUE TITLE
TraceFeignClientAutoConfiguration did not math for no bean named "braveTracer"

### ISSUE THREAD

**Issue by limng06** [spring-cloud/spring-cloud-sleuth#2005] opened 2021-08-06 09:12 UTC
TraceFeignClientAutoConfiguration:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.cloud.sleuth.Tracer; SearchStrategy: all) did not find any beans of type org.springframework.cloud.sleuth.Tracer (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required classes 'feign.Client', 'org.springframework.cloud.openfeign.FeignContext' (OnClassCondition)
         - @ConditionalOnProperty (spring.sleuth.feign.enabled) matched (OnPropertyCondition)

but

-------------
021-08-06 17:05:42,920 [,,,] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory:225 [main] - Creating shared instance of singleton bean 'org.springframework.cloud.sleuth.autoconfig.instrument.messaging.TraceFunctionAutoConfiguration'
2021-08-06 17:05:42,924 [,,,] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory:225 [main] - Creating shared instance of singleton bean 'braveTracer'
2021-08-06 17:05:42,925 [,,,] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory:225 [main] - Creating shared instance of singleton bean 'tracer'

--------------

i dont know how do deal with it.   i can not control the bean launch order

**Comment by marcingrzejszczak** [comment] 2021-08-09 08:39
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2021-08-16 08:44
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-08-23 08:44
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-08-23 08:44 UTC
Labels: waiting for feedback, feedback-reminder
