### ISSUE TITLE
Support for Additional MDC Values

### ISSUE THREAD

**Issue by matthewjmason** [spring-cloud/spring-cloud-sleuth#1015] opened 2018-06-21 20:40 UTC
I would like to add some additional values to the log's MDC. For example:
```
        Span requestSpan = tracer.newTrace().name("request").tag("myTxId", "abc456").start(); 
```
It would be convenient if https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jCurrentTraceContext.java took a set of properties to pull from a Span's tags to add to MDC. I would then able to correlate on my custom tag attributes. In the interim, I looked at extending this class to add the functionality but it is marked as final.

**Comment by marcingrzejszczak** [comment] 2018-06-21 21:02
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/1003

**Closed by marcingrzejszczak** 2018-06-21 21:02 UTC

**Comment by matthewjmason** [comment] 2018-06-22 12:14
apologies for the dup
