### ISSUE TITLE
sleuth use the failing zipkin service

### ISSUE THREAD

**Issue by LittleShrimp1987** [spring-cloud/spring-cloud-sleuth#753] opened 2017-10-19 11:05 UTC
I register zipkin server in consul and my app user consul client to discover zipkin server, in consul there are two zipkin service, one failing, one up, but the app always send message to the failing zipkin service.

**Comment by marcingrzejszczak** [comment] 2017-10-19 11:40
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/pull/743

**Closed by marcingrzejszczak** 2017-10-19 11:40 UTC
Labels: duplicate

**Comment by LittleShrimp1987** [comment] 2017-10-19 11:46
i wonder if it is possible to exclude the failing instance.

**Comment by marcingrzejszczak** [comment] 2017-10-19 11:47
You can read how Ribbon works - http://cloud.spring.io/spring-cloud-netflix/single/spring-cloud-netflix.html#spring-cloud-ribbon . With the PR that I'm doing you'll be able to use it

**Comment by LittleShrimp1987** [comment] 2017-10-19 11:48
ok, thanks.
