### ISSUE TITLE
BeanNotOfRequiredTypeException with activeMQ

### ISSUE THREAD

**Issue by krzyhooarrow** [spring-cloud/spring-cloud-sleuth#2149] opened 2022-04-19 13:10 UTC
Hi. I've faced problem:

Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'activeMQConnectionFactory' is expected to be of type 'org.apache.activemq.ActiveMQConnectionFactory' but was actually of type 'org.springframework.cloud.sleuth.brave.instrument.messaging.LazyTopicConnectionFactory'

Disabling messaging doesn't help
spring.sleuth.messaging.enabled: false

**Comment by marcingrzejszczak** [comment] 2022-04-19 13:39
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-04-26 13:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-05-03 13:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed as completed by spring-cloud-issues** 2022-05-03 13:40 UTC
