### ISSUE TITLE
Spring integration and sleuth causing misalignment in span?

### ISSUE THREAD

**Issue by charliecloud** [spring-cloud/spring-cloud-sleuth#1349] opened 2019-05-09 14:47 UTC
I am trying to get some help with an issue after upgrading from Finchley to Greenwich.SR1. I have posted on StackOverflow with no responses and some downvotes with no comments. As far as I can tell we are not using Sleuth directly in our project, spring integration is using it which makes me think there is an issue there? From what I have read so far maybe it is an issue with try/catch blocks in the spring integration code causing mismatches in spans? All the details are in the StackOverflow question

https://stackoverflow.com/questions/56044627/misalignment-scoped-span-current-span-noopspan-after-upgrading-spring-cloud

**Comment by ryanjbaxter** [comment] 2019-05-13 14:36
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-05-20 14:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-05-27 14:41
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-27 14:41 UTC
Labels: feedback-reminder, waiting for feedback
