### ISSUE TITLE
When gateway kind is CLIENT, http.path: is "/", Why is that?

### ISSUE THREAD

**Issue by songwenh** [spring-cloud/spring-cloud-sleuth#1429] opened 2019-08-21 14:39 UTC
This is the version I am currently using.
Spring Cloud Greenwich SR2
Spring Boot 2.1.6

Show-how
![image](https://user-images.githubusercontent.com/31386856/63441479-0fa8b880-c464-11e9-8a19-e794fdb63c07.png)
![image](https://user-images.githubusercontent.com/31386856/63441451-061f5080-c464-11e9-8ef0-c1fead9f1d5f.png)

```json
[
  {
    "traceId": "08290396225596a4",
    "parentId": "08290396225596a4",
    "id": "35b9081f0d5a5103",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1566398118206713,
    "duration": 29485,
    "localEndpoint": {
      "serviceName": "gateway-server",
      "ipv4": "192.168.5.9"
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/demo/test/zipkin"
    }
  },
  {
    "traceId": "08290396225596a4",
    "id": "08290396225596a4",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1566398118213550,
    "duration": 23587,
    "localEndpoint": {
      "serviceName": "gateway-server",
      "ipv4": "192.168.5.9"
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/"
    }
  },
  {
    "traceId": "08290396225596a4",
    "parentId": "08290396225596a4",
    "id": "35b9081f0d5a5103",
    "kind": "SERVER",
    "name": "get /demo/test/zipkin",
    "timestamp": 1566398118222129,
    "duration": 14853,
    "localEndpoint": {
      "serviceName": "demo",
      "ipv4": "192.168.5.9"
    },
    "remoteEndpoint": {
      "ipv6": "::1"
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/demo/test/zipkin",
      "mvc.controller.class": "DemoApplication",
      "mvc.controller.method": "testZipkin"
    },
    "shared": true
  }
]
```

End
Sample URL：https://github.com/songwenh/test-sample

I hope to answer my questions. Thank you.

**Comment by skybluehhx** [comment] 2019-08-25 05:45
I ran your project and I got different results from you 
![Uploading image.png…](https://github.com/skybluehhx/Myimages/blob/master/zipkin.png)
You can start another idea window to run the demo project, and you'll get the right results

**Comment by songwenh** [comment] 2019-08-25 05:52
> 我运行你的项目，我得到了不同的结果 你可以启动另一个想法窗口来运行演示项目，你会得到正确的结果
> ![正在上传image.png ......](https://github.com/skybluehhx/Myimages/blob/master/zipkin.png)

Your project still ends up without an /api/demo/.....

**Comment by marcingrzejszczak** [comment] 2019-08-26 14:42
I'm sorry but I don't understand anything. Can you please explain what you are doing, how you're doing that and what exactly the problem is and what do you think that should take place instead?

**Comment by songwenh** [comment] 2019-08-26 15:05
> I'm sorry but I don't understand anything. Can you please explain what you are doing, how you're doing that and what exactly the problem is and what do you think that should take place instead?

Use my case, the path of the request to the gateway, originally is localhost: 9999/api/demo/test/zipkin, show the http:path= /,  The gateway does not display the full request path

**Comment by marcingrzejszczak** [comment] 2019-11-13 13:27
Can you check the latest snapshots? I've added some fixes for the gateway integration.

**Comment by spring-issuemaster** [comment] 2019-11-20 13:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-11-27 13:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-11-27 13:32 UTC
Labels: feedback-reminder, waiting for feedback
