### ISSUE TITLE
2.0.0.M2 sleuth does not work with Spring Boot 2.0.0.M4

### ISSUE THREAD

**Issue by ltcoleman** [spring-cloud/spring-cloud-sleuth#706] opened 2017-09-21 14:47 UTC
We have been upgrading to Spring Boot 2.0.0.M3. This issue (https://github.com/spring-projects/spring-boot/issues/10047) had me update to 2.0.0.M4. 

After updating to M4, Spring Cloud Sleuth starts throwing errors from the TraceHandlerInterceptor.java. The ErrorController is no longer resolvable from this import: 
import org.springframework.boot.autoconfigure.web.servlet.error.ErrorController;

So in M3, ErrorController resolves and Sleuth works. In M4, ErrorController does not resolve which breaks the Spring Boot application.

**Comment by marcingrzejszczak** [comment] 2017-09-21 14:47
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/700

**Closed by marcingrzejszczak** 2017-09-21 14:47 UTC
Labels: duplicate
