### ISSUE TITLE
Not able to identify a span with http.method for every incoming http request

### ISSUE THREAD

**Issue by lsteigerwald** [spring-cloud/spring-cloud-sleuth#655] opened 2017-07-24 13:59 UTC
As of our communication on gitter here is the issue for tracking.

![Screenshot of conversation](https://user-images.githubusercontent.com/3952213/28526767-ce0438d6-7088-11e7-9d35-81364f89a02f.png)

And the example environment is at branch anomaly_detection/develop - https://github.com/ga52can/Microservice_Playground/tree/anomaly_detection/develop

**Comment by padjon** [comment] 2017-07-27 17:35
In my mind the same issue as #662

**Comment by marcingrzejszczak** [comment] 2017-08-17 12:48
Related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/668 and https://github.com/spring-cloud/spring-cloud-sleuth/issues/662

**Comment by marcingrzejszczak** [comment] 2017-08-17 15:50
Duplicate of #668

**Closed by marcingrzejszczak** 2017-08-17 15:50 UTC
Labels: duplicate
