### ISSUE TITLE
Dependency Issue With Samples

### ISSUE THREAD

**Issue by anixan** [spring-cloud/spring-cloud-sleuth#498] opened 2017-01-19 14:21 UTC
Hi All,

I am currently trying to run the samples this project and I am getting the following problem which seems to be related to Spring Boot itself and I wanted to see if anyone can help with this:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.springframework.cloud:spring-cloud-sleuth-sample:[unknown-version], /Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml, line 52, column 12
[ERROR] Non-resolvable import POM: Failure to find org.springframework.data:spring-data-releasetrain:pom:${spring-data-releasetrain.version} in https://repo.spring.io/release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:1.5.0.BUILD-SNAPSHOT, /Users/anix/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.5.0.BUILD-SNAPSHOT/spring-boot-dependencies-1.5.0.BUILD-SNAPSHOT.pom, line 2081, column 16
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ org.springframework.cloud:spring-cloud-sleuth-sample:[unknown-version], /Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml, line 63, column 15
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-aop:jar is missing. @ org.springframework.cloud:spring-cloud-sleuth-sample:[unknown-version], /Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml, line 71, column 15
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ org.springframework.cloud:spring-cloud-sleuth-sample:[unknown-version], /Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml, line 75, column 15
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.springframework.cloud:spring-cloud-sleuth-sample:1.2.0.BUILD-SNAPSHOT (/Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml) has 4 errors
[ERROR]     Non-resolvable import POM: Failure to find org.springframework.data:spring-data-releasetrain:pom:${spring-data-releasetrain.version} in https://repo.spring.io/release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:1.5.0.BUILD-SNAPSHOT, /Users/anix/.m2/repository/org/springframework/boot/spring-boot-dependencies/1.5.0.BUILD-SNAPSHOT/spring-boot-dependencies-1.5.0.BUILD-SNAPSHOT.pom, line 2081, column 16 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @ org.springframework.cloud:spring-cloud-sleuth-sample:[unknown-version], /Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml, line 63, column 15
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-aop:jar is missing. @ org.springframework.cloud:spring-cloud-sleuth-sample:[unknown-version], /Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml, line 71, column 15
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-test:jar is missing. @ org.springframework.cloud:spring-cloud-sleuth-sample:[unknown-version], /Users/anix/App Dev/spring-cloud-sleuth-master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml, line 75, column 15
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException`
```

Thanks

**Comment by marcingrzejszczak** [comment] 2017-01-19 14:23
Maybe try these instead - https://github.com/spring-cloud-samples/sleuth-documentation-apps ?

**Comment by anixan** [comment] 2017-01-19 14:49
Hi @marcingrzejszczak ,

Thanks for the help, I appear to be getting the same error when trying to run the samples in the spring-cloud-contract project too.

So not sure if this is an issue with Spring 1.5.0 or more likely a local issue.

Thanks

**Comment by marcingrzejszczak** [comment] 2017-01-19 14:58
It's building fine on CircleCI 

- https://circleci.com/gh/spring-cloud-samples/spring-cloud-contract-samples/91 (it's failing due to timeout reason not due to building)
- https://circleci.com/gh/spring-cloud-samples/spring-cloud-contract-samples/90

**Comment by marcingrzejszczak** [comment] 2017-02-01 10:01
ping?

**Comment by zxkane** [comment] 2017-02-21 03:18
I also met few issues to make samples work.

I always got class not found error when running `mvn spring-boot:run` to run samples(such as **spring-cloud-sleuth-sample**) in CLI,

> [WARNING] Error injecting: org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo
> java.lang.NoClassDefFoundError: com/puppycrawl/tools/checkstyle/api/CheckstyleException
> 	at java.lang.Class.getDeclaredConstructors0(Native Method)

The sample application exited without error if running it in IDE(Intellij IDEA),

> 2017-02-21 11:14:39.566  INFO [testSleuthApp,,,] 12305 --- [           main] sample.SampleSleuthApplication           : Starting SampleSleuthApplication on kane-air with PID 12305 (/Users/kane/git/spring/spring-cloud-sleuth/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/target/classes started by kane in /Users/kane/git/spring/spring-cloud-sleuth/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample)
> 2017-02-21 11:14:39.575  INFO [testSleuthApp,,,] 12305 --- [           main] sample.SampleSleuthApplication           : No active profile set, falling back to default profiles: default
> 2017-02-21 11:14:39.774  INFO [testSleuthApp,,,] 12305 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6193932a: startup date [Tue Feb 21 11:14:39 CST 2017]; root of context hierarchy
> 2017-02-21 11:14:40.615  INFO [testSleuthApp,,,] 12305 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'sampleController' with a different definition: replacing [Generic bean: class [sample.SampleController]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [/Users/kane/git/spring/spring-cloud-sleuth/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/target/classes/sample/SampleController.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=sampleSleuthApplication; factoryMethodName=sampleController; initMethodName=null; destroyMethodName=(inferred); defined in sample.SampleSleuthApplication]
> 2017-02-21 11:14:41.015  INFO [testSleuthApp,,,] 12305 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.sleuth.instrument.async.AsyncDefaultAutoConfiguration$DefaultAsyncConfigurerSupport' of type [class org.springframework.cloud.sleuth.instrument.async.AsyncDefaultAutoConfiguration$DefaultAsyncConfigurerSupport$$EnhancerBySpringCGLIB$$32ece1f8] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2017-02-21 11:14:41.134  INFO [testSleuthApp,,,] 12305 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration' of type [class org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2017-02-21 11:14:41.294  INFO [testSleuthApp,,,] 12305 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'validator' of type [class org.springframework.validation.beanvalidation.LocalValidatorFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2017-02-21 11:14:44.284  INFO [testSleuthApp,,,] 12305 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 
> 2017-02-21 11:14:44.418  INFO [testSleuthApp,,,] 12305 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
> 2017-02-21 11:14:44.443  INFO [testSleuthApp,,,] 12305 --- [           main] sample.SampleSleuthApplication           : Started SampleSleuthApplication in 5.927 seconds (JVM running for 6.965)
> 2017-02-21 11:14:44.444  INFO [testSleuthApp,,,] 12305 --- [       Thread-3] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6193932a: startup date [Tue Feb 21 11:14:39 CST 2017]; root of context hierarchy
> 2017-02-21 11:14:44.446  INFO [testSleuthApp,,,] 12305 --- [       Thread-3] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

The behaviors are same using either latest code(master branch) or latest release(tag v1.1.2.RELEASE).

Any suggestion to make samples work.

**Comment by zxkane** [comment] 2017-02-21 03:55
I made the sample build successfully after completely removing checkstyle configuration in the parent pom of this repo. I tried using vm argument `-Dcheckstyle.skip=true` to disable checkstyle, but it doesn't work. I suspect the missing configuration file `checkstyle.xml` in this repo to cause the error. Looks like the build of sleuth is broken by checkstyle configuration in a clean environment.

The second issue, it's caused by a broken tomcat-embed-core jar downloaded by maven. Removed the broken one then redownload it to fix the launching issue.

**Comment by zxkane** [comment] 2017-02-21 07:01
I'm suffering another issue to make samples working. Some samples are depending on artifact `spring-cloud-sleuth-sample-test-core` for running test cases. I did successfully install `spring-cloud-sleuth-sample-test-core` via `mvn install` to local maven repo. And I can find artifact `spring-cloud-sleuth-sample-test-core` in local repo(`~/.m2/repository`).

However the build of samples(such as **spring-cloud-sleuth-sample-zipkin-stream**) still always failed on resolving dependency `spring-cloud-sleuth-sample-test-core`.

> [ERROR] Failed to execute goal on project spring-cloud-sleuth-sample-zipkin-stream: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-sleuth-sample-zipkin-stream:jar:1.2.0.BUILD-SNAPSHOT: Failed to collect dependencies at org.springframework.cloud:spring-cloud-sleuth-sample-test-core:jar:1.2.0.BUILD-SNAPSHOT: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-sleuth-sample-test-core:jar:1.2.0.BUILD-SNAPSHOT: Failure to find org.springframework.cloud:spring-cloud-sleuth-samples:pom:1.2.0.BUILD-SNAPSHOT in https://repo.spring.io/libs-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 1]

How can I make sleuth samples running locally? Any suggestion is appreciated.

**Comment by marcingrzejszczak** [comment] 2017-02-21 07:19
Most likely there was some issue with our `repo.spring.io.`. Try removing the `~/.m2/repository/org/springframework/cloud/sleuth/` jars and try again. There's also another example you might want to run - https://github.com/openzipkin/sleuth-webmvc-example

**Comment by marcingrzejszczak** [comment] 2017-02-21 17:41
You can also try running a sample like this `./mvnw spring-boot:run -pl :spring-cloud-sleuth-sample-feign` - I've just managed to run this.

**Comment by zxkane** [comment] 2017-02-23 03:42
@marcingrzejszczak Thanks for your reply. 

I did run `sample-feign` using above command, though I had to remove checkstyle configuration in parent pom firstly.

But running the command `./mvnw spring-boot:run -pl :spring-cloud-sleuth-sample-zipkin` still failed on resolving dependency **spring-cloud-sleuth-sample-test-core**.

**Comment by marcingrzejszczak** [comment] 2017-02-23 07:00
So try running `./mvnw spring-boot:run -pl :spring-cloud-sleuth-sample-zipkin --also-make-dependents` . Cause `-pl` means run a project but you need it's dependant modules. You can also do `./mvnw clean install -DskipTests -T 8 && ./mvnw spring-boot:run -pl :spring-cloud-sleuth-sample-zipkin`

**Closed** 2017-02-23 09:31 UTC
Labels: question
