### ISSUE TITLE
All class implemented EnvironmentPostProcessor fire twice, and caused by EnvironmentPostProcessor

### ISSUE THREAD

**Issue by RaymondZheng** [spring-cloud/spring-cloud-sleuth#858] opened 2018-02-14 09:21 UTC
My project integrated with sleuth, and the pom file is as follow:
`		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-rabbit</artifactId>
		</dependency>
`

All functions are working fine, except for one point: all class implemented with EnvironmentPostProcessor fire twice. For instance,  one simple class just likes:
public class PanguEnvironmentPostProcessor implements EnvironmentPostProcessor, Ordered {
    @Override
    public void postProcessEnvironment(ConfigurableEnvironment configurableEnvironment, SpringApplication springApplication) {
        System.out.println("*start base: " + this.getClass().toString());
    }

    @Override
    public int getOrder() {
        //return ConfigFileApplicationListener.DEFAULT_ORDER + 100000;
        return Ordered.LOWEST_PRECEDENCE;
    }
}
and no matter what the order returning. 

Looking forward your help, thx.

**Comment by marcingrzejszczak** [comment] 2018-02-14 10:01
What does it have to do with Sleuth?

**Comment by brenuart** [comment] 2018-02-14 15:50
I suspect this is caused by SpringCloud's bootstrap mechanism.

**Comment by marcingrzejszczak** [comment] 2018-02-14 15:50
That's exactly what I suspected but I wanted to hear some input from @RaymondZheng before closing the issue

**Comment by marcingrzejszczak** [comment] 2018-02-14 17:14
@RaymondZheng what @brenuart said is true. There is an additional bootstrapping mechanism for Cloud projects.

**Closed by marcingrzejszczak** 2018-02-14 17:14 UTC
Labels: waiting for feedback
