### ISSUE TITLE
Sleuth HeaderBasedMessagingInjector not getting called when zuul.routes configured in gateway

### ISSUE THREAD

**Issue by sbogadhi** [spring-cloud/spring-cloud-sleuth#1113] opened 2018-10-25 03:47 UTC
I have configured the Custom class implementing the HeaderBasedMessagingInjector to customize the span to include username & proxying specific URL matching requests to external service.

public class CustomSpanInjector extends HeaderBasedMessagingInjector {
@override
public void inject(Span span, SpanTextMap carrier) {
// Customize the span object
}
}
The problem is custom HeaderBasedMessagingInjector is not getting called before the request is forwared to zuul filter.

Spring boot version - 1.5.9.RELEASE
spring-cloud-dependencies - Edgware.SR2

**Comment by marcingrzejszczak** [comment] 2018-10-25 05:31
Can you please upgrade to the latest version and see if the problem is still there

**Comment by spring-issuemaster** [comment] 2018-11-21 10:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-11-28 10:34
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-11-28 10:34 UTC
Labels: feedback-reminder, waiting for feedback
