### ISSUE TITLE
nested exception is com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 14

### ISSUE THREAD

**Issue by renpengben** [spring-cloud/spring-cloud-sleuth#366] opened 2016-08-04 16:12 UTC
When I use spring-cloud-sleuth-zipkin-stream and spring-cloud-starter-stream-rabbit, when I visit feign client ,Zipkin stream server appears 
` Retries exhausted for message (Body:'[B@31dfeb72(byte[858])'MessageProperties [headers={spanTraceId=d7adc9d0c0e36862, spanId=d7adc9d0c0e36862, X-B3-SpanId=d7adc9d0c0e36862, currentSpan=[Trace: d7adc9d0c0e36862, Span: d7adc9d0c0e36862, Parent: null, exportable:false], X-B3-Sampled=0, X-Message-Sent=true, X-B3-TraceId=d7adc9d0c0e36862, messageSent=true, X-Current-Span=[Trace: d7adc9d0c0e36862, Span: d7adc9d0c0e36862, Parent: null, exportable:false], spanSampled=0, contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans}, timestamp=null, messageId=null, userId=null, appId=null, clusterId=null, type=null, correlationId=null, replyTo=null, contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans, contentEncoding=null, contentLength=0, deliveryMode=null, expiration=null, priority=0, redelivered=false, receivedExchange=sleuth, receivedRoutingKey=sleuth, deliveryTag=1, messageCount=0])`

`Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [sleuth.sleuth.convert.bridge]; nested exception is com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 14`

**Comment by marcingrzejszczak** [comment] 2016-08-04 16:28
I think it's a duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/357 . I saw this Kyro there too

**Closed by marcingrzejszczak** 2016-08-04 16:28 UTC

**Comment by marcingrzejszczak** [comment] 2016-08-04 16:32
But maybe you could share a sample?

**Comment by renpengben** [comment] 2016-08-04 16:42
My program order is ‘Service1->Service2’

ZipkinStreamServer Config:
`server.port=9967
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.url=jdbc:mysql://127.0.0.1/zipkin-demo
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.schema=classpath:/mysql.sql
zipkin.storage.storage=mysql
spring.rabbitmq.host=localhost
server.sleuth.enabled=false`


Service1 Config:
`spring.application.name=compute-provide-service
server.port=5645
spring.rabbitmq.host=localhost
spring.sleuth.sampler.percentage=1.0
spring.sleuth.stream.enabled=true
spring.zipkin.baseUrl=http://localhost:9967
spring.zipkin.enabled=true
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:1111/eureka/`

Service2 Config:
`spring.application.name=feign-consumer
server.port=4444
spring.rabbitmq.host=localhost
spring.sleuth.sampler.percentage=1.0
spring.sleuth.hystrix.strategy.enabled=true
spring.sleuth.stream.enabled=true
spring.zipkin.baseUrl=http://localhost:9967
spring.zipkin.enabled=true
sample.zipkin.emabled=true
eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/`

**Comment by marcingrzejszczak** [comment] 2016-08-04 16:43
Could you post the code? :)

**Comment by renpengben** [comment] 2016-08-05 04:03
hi @marcingrzejszczak  this is the code 
https://github.com/renpengben/spring-cloud-study-demo
```
Zipkin Service
http://localhost:9999/add?a=1&b=2

service-1
http://localhost:6868/add?a=1&b=2

service-2
http://localhost:7777/add?a=1&b=2

when request  http://localhost:7777/add?a=1&b=2 ,Zipkin Service error
```

**Comment by renpengben** [comment] 2016-08-07 14:57
Spring boot 1.4.0.RELEASE No problem ！
