### ISSUE TITLE
2020.0.5 causes IllegalArgumentException for TaskExecutor bean providers

### ISSUE THREAD

**Issue by vy** [spring-cloud/spring-cloud-sleuth#2109] opened 2022-02-02 10:37 UTC
**Describe the bug**

After upgrading from 2020.0.4 to 2020.0.5, configurations providing `TaskExecutor` beans started throwing `IllegalArgumentException: object is not an instance of declaring class` exceptions.

**Sample**

The following configuration used to work in Spring Cloud 2020.0.4:

```
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.task.SimpleAsyncTaskExecutor;
import org.springframework.core.task.TaskExecutor;
import org.springframework.scheduling.annotation.AsyncConfigurer;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;

@Configuration
@EnableAsync
@EnableScheduling
public class AsyncConfiguration implements AsyncConfigurer {

    @Bean
    public TaskExecutor dogTaskExecutor() {
        return new SimpleAsyncTaskExecutor();
    }

   // ...

}
```

After upgrading to Spring Cloud 2020.0.5, it causes the following exception:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.core.task.TaskExecutor]: Illegal arguments to factory method 'dogTaskExecutor'; args: ; nested exception is java.lang.IllegalArgumentException: object is not an instance of declaring class
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:172)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 73 more
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 74 more
```

See the following breakpoint screenshot just before the exception throw: 

![image](https://user-images.githubusercontent.com/72137/152137689-6450e225-9850-41c3-a470-f0cbc9f5f5fc.png)

Here `factoryBean` is a `LazyTraceAsyncCustomizer` delegating to our `AsyncConfiguration`. In 2020.0.4, `factoryBean` is `AsyncConfiguration`, that is, no `LazyTraceAsyncCustomizer` wrapping.

Excluding `org.springframework.cloud:spring-cloud-starter-sleuth` dependency solves the problem. I suspect the issue to be caused by #2033.

**Comment by marcingrzejszczak** [comment] 2022-02-02 12:14
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/2100

**Closed by marcingrzejszczak** 2022-02-02 12:14 UTC
