### ISSUE TITLE
ThreadContextCurrentTraceContextScope doesnt remove custom MDC tags on close

### ISSUE THREAD

**Issue by Guchman** [spring-cloud/spring-cloud-sleuth#1361] opened 2019-05-27 10:12 UTC
Hi,
It's seems to be a bug, but maybe I've misunderstood correct behaviour.

1) We have userId custom MDC tag.
2) First span created. No tags exists in MDC. Slf4jScopeDecorator.decorateScope will remember previousMdc to variable as empty map.
3) We add userId to MDC. So now there is "userId -> "1" in MDC
4) Close current span. ThreadContextCurrentTraceContextScope.close will replace all values to  previous mdc. 

Expected to have empty MDC after span close.
But there is "userId" -> "1".

It's seem to be a bug on step 2, cause previousMdc try to remember only tags with value. But it's must to remember all of them and remove entries that not exists before span created, isnt it?

**Comment by marcingrzejszczak** [comment] 2019-06-11 15:01
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2019-06-18 15:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-25 15:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-25 15:03 UTC
Labels: feedback-reminder, waiting for feedback
