### ISSUE TITLE
New scope in Reactor in inner subscription

### ISSUE THREAD

**Issue by jonathannaguin** [spring-cloud/spring-cloud-sleuth#2118] opened 2022-02-19 14:41 UTC
Hello,

I am using SQS for sending and receiving messages using the new async AWS SDK.
When sending messages, I am setting the tracing attributes into the message and when I receive them I would like to update the trace context with those.
This is more or less the polling logic:
```
Span pollSpan = tracer.newTrace()
  .name("poll");

try (Tracer.SpanInScope span = tracer.withSpanInScope(pollSpan.start())) {
  Flux < Message > flux = Flux.create(sink -> sink.onRequest(num -> receiveMessages(sink)));

  flux
    .flatMap(message -> {
      var mono = deserialize(message, MyObjectWithTracing.class);
      var traceId = message.messageAttributes().get("traceId").stringValue();
      var spanId = message.messageAttributes().get("spanId").stringValue();

      var newContext = TraceContext.newBuilder()
        .traceId(Long.parseLong(traceId))
        .spanId(Long.parseLong(spanId))
        .build();

      return mono.flatMap(myObject -> {
          // process object
          try (Tracer.SpanInScope ws = tracer.withSpanInScope(tracer.toSpan(newContext)
            .start())) {
            logger.info("Do something"); // wrong tracing information in the logs
          }
        })
        .contextWrite(Context.of(Span.class, tracer.toSpan(newContext).start(), TraceContext.class, newContext));
    })
    .subscribeOn(Schedulers.boundedElastic())
    .subscribe();
}
```

In the above code, I constantly poll for messages, for each of them, I retrieve the tracing info and I would like to use them in a new span as part of its processing. The problem I am facing is that the log always have the same traceId and spainId, the outer SpanInScope.

**Comment by marcingrzejszczak** [comment] 2022-02-19 17:20
Have you tried setting the reactor instrumentation mode to manual and doing things manually? Most likely we're instrumenting too much there and we're polluting a thread that we never clear or sth like that

**Comment by jonathannaguin** [comment] 2022-02-20 14:43
@marcingrzejszczak  I tried with 'decorate_queues' and same problem. I can't use 'manual' as I need the automatic instrumentation on the service, it's a webflux application that also does webClient calls. Is there a way to enforce the Reactor context? I saw some code samples using `contextWrite` but not sure if I am missing something. Thanks!

**Comment by marcingrzejszczak** [comment] 2022-02-21 08:19
Can you create a sample that replicates this problem? BTW We will be revisiting how we do instrumentation with Reactor in Spring Framework 6 and Boot 3.

**Comment by jonathannaguin** [comment] 2022-02-21 10:00
@marcingrzejszczak  actually, I don't think the problem is with the Reactor instrumentation. 
While creating the sample project I realised that bit was working fine, the problem seems to be with the Async AWS SDK 2.0.
On my app, inside the flatMap, I am making a call to DynamoDB:

```
 var table = dynamoDbEnhancedAsyncClient.table("MyTable", TableSchema.fromClass(Item.class));
 var request = GetItemEnhancedRequest.builder()
                                            .key(Key.builder()
                                                    .partitionValue("MyKeyId")
                                                    .build())
                                            .build();
 Mono.fromFuture(table.getItem(request));
```

It appears the response creates a new context always.
I am setting a Spring `ExecutorService` to the SDK which Sleuth injects as a `TraceableExecutorService`:
```
  @Bean
    public ThreadPoolExecutor awsSdkExecutor()
    {
        ThreadPoolExecutor executor = new ThreadPoolExecutor(10,
                                                             500,
                                                             10,
                                                             TimeUnit.SECONDS,
                                                             new LinkedBlockingQueue<>(),
                                                             new ThreadFactoryBuilder().threadNamePrefix("sdk-async-response")
                                                                                       .build());
        executor.allowCoreThreadTimeOut(true);
        return executor;
    }


 @Bean
    public DynamoDbAsyncClient dynamoDbAsyncClient(
                                                   ExecutorService awsSdkExecutor)
    {
        return DynamoDbAsyncClient.builder()
                                  .asyncConfiguration(b -> b.advancedOption(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR, awsSdkExecutor))
                                  .build();
    }
```

@marcingrzejszczak  let me know if you would prefer to have a different issue or if we can use this thread for this. Thanks for your help and support.

**Comment by marcingrzejszczak** [comment] 2022-02-21 10:05
Isn't this related to this https://github.com/spring-cloud/spring-cloud-sleuth/issues/2014 ?

**Comment by jonathannaguin** [comment] 2022-02-21 10:46
I can see trace/spans on the CompletableFuture response which I subscribe to using `Mono.fromFuture`, so the instrumentation works however it always create a new context.

**Comment by marcingrzejszczak** [comment] 2022-02-21 11:48
You are using Brave API directly from what I see. What you can do is use the `Propagator` API from Sleuth that allows you to inject and extract headers. The propagator will create a `SpanBuilder` for you from the headers and it will create a proper span out of the headers.

**Comment by jonathannaguin** [comment] 2022-02-21 12:40
I don't know how the `Propagator` API will help.
I was able to create a small webflux application that reproduces the problem here: https://github.com/jonathannaguin/sleuth-issue-future
The source of the problem seems to be CompletableFuture:
```
return Mono.fromFuture(() -> {
                                               return CompletableFuture.completedFuture(myObject);
                                           });
```
Is there a way I can force the trace context after the `fromFuture`?

**Comment by jonathannaguin** [comment] 2022-03-22 19:32
Hey @marcingrzejszczak, did you have a chance to review the sample project? Thanks!

**Comment by marcingrzejszczak** [comment] 2022-03-23 08:11
Hi! Sorry, not yet. I have it on my radar and will try to look into it ASAP.

**Comment by jonathannaguin** [comment] 2022-06-13 12:17
Hey @marcingrzejszczak, I was able to get this working by upgrading Sleuth to its latest version and making use of the utility `ReactorSleuth#putSpanInScope`, example:
```
Mono.defer(() -> blahblah)
                                              .flatMap(obj -> {

                                              })
                                              .contextWrite(context -> ReactorSleuth.putSpanInScope(tracer,
                                                                                                    context,
                                                                                                    builderFrom(newContext).start()));
```

**Comment by marcingrzejszczak** [comment] 2022-06-13 12:30
Sorry for not having done this yet... That method should help, the problem is that it's bug-prone cause it's putting stuff in thread local. The whole way we're instrumenting Reactor at this point can lead to such bugs but we'll try to address those in Spring Observability by rethinking the whole Observability & Reactor instrumentaion (and maybe do some patching in Sleuth).

**Comment by jonathannaguin** [comment] 2022-06-14 17:02
I noticed the effort is going to those new libraries, as long as I have a similar utlity, I should be able to move out of Sleuth. Thanks

**Comment by marcingrzejszczak** [comment] 2022-06-15 08:03
I'll close this since we have a manual solution to this. If we make the Reactor & Sleuth interop more stable then the manual work might not be necessary

**Closed** 2022-06-15 08:04 UTC
Labels: feedback-provided
