### ISSUE TITLE
Clients should not propagate all spans

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#157] opened 2016-02-11 10:44 UTC
Right now rest templates etc. are propagating all headers. The headers that are propagated should be configurable (like with `HttpTraceKeys`)

**Comment by dsyer** [comment] 2016-02-11 13:13
Sort of a duplicate of #19

**Comment by marcingrzejszczak** [comment] 2016-02-18 10:33
hmm quite frankly that's not the case (that we propagate all headers). We're not propagating any :P https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/AbstractTraceHttpRequestInterceptor.java#L51 

We're propagating only the essential ones. Disregarding the https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/TraceKeys.java#L157

**Comment by dsyer** [comment] 2016-02-18 11:04
I think there is some confusion between "propagate" and "tag". We do create some tags as well, right? And it seems from #161 that we aren't entirely consistent about it. Maybe close this one in favour of #161?

**Closed by dsyer** 2016-02-18 11:04 UTC
Labels: backlog, enhancement
