### ISSUE TITLE
Wrong TraceContext in fallback methods on timeout

### ISSUE THREAD

**Issue by bvoss** [spring-cloud/spring-cloud-sleuth#1073] opened 2018-08-24 11:53 UTC
Hi,

I encounter a problem  using the spring-cloud-sleuth with hystrix, when using fallback methods.

I would expect the same traceId for logs in  ServiceA calling ServiceB via @HystrixCommand and the corresponding fallback method to be the same.
But that's not always the case.

Attached a sample project and stripped log output from the test.
In the test output you can see different traceId in for some (not all) fallback methods.

Versions:
Spring Boot: 2.0.4.RELEASE
Spring Cloud: Finchley.SR1
Spring Cloud Starter Sleuth: 2.0.1.RELEASE
Hystrix: 1.5.12

For any other dependency, please have a look in the pom of the sample app in the attached zip.

[sleuth-bug.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/2318207/sleuth-bug.zip)
[sleut-bug-stripped-test-output.txt](https://github.com/spring-cloud/spring-cloud-sleuth/files/2318210/sleut-bug-stripped-test-output.txt)

**Comment by marcingrzejszczak** [comment] 2018-08-24 11:54
Can you provide information about which version of Sleuth are you using?

**Comment by bvoss** [comment] 2018-08-24 12:01
@marcingrzejszczak you were faster in asking for versions the me in adding them to the issue description.
Do you need any more information?

**Comment by marcingrzejszczak** [comment] 2018-08-24 12:02
No - that seems to be all, thanks. I'll try to take a look at it.

**Comment by bvoss** [comment] 2018-09-01 11:58
@marcingrzejszczak Do you had the time to take a look into it?

**Comment by marcingrzejszczak** [comment] 2018-09-01 13:07
Not yet

**Comment by marcingrzejszczak** [comment] 2018-09-05 08:45
I've added an option to pass tracing context around for fallback methods if you use `TraceCommand` (https://github.com/spring-cloud/spring-cloud-sleuth/issues/1084). In Javanica it's extremely difficult to make that work because there are no hooks that I can see that can be used to add some customization. I'll put this issue to icebox for now.

**Comment by bvoss** [comment] 2018-09-05 10:10
@marcingrzejszczak Thanks!
So, I will implement my on basic aspect and use TraceCommand in it.
It might be a good idea to add a hint/warning in the documentation. What do you think?

**Comment by marcingrzejszczak** [comment] 2018-09-05 10:51
Great idea. Care for a PR?

**Comment by bvoss** [comment] 2018-09-05 12:59
Yes, sure.
But currently I'm preparing a test project for spring-cloud-netflix, because I'm afraid there is a similar problem with handing over the Spring-SecurityContext to the fallback method. And the [example there](http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.1.RELEASE/single/spring-cloud-netflix.html#_how_to_include_hystrix) uses Javanica.
So afterwards I'll have a lokk at the documentation.

**Comment by marcingrzejszczak** [comment] 2018-11-14 10:30
Hey @bvoss how is the PR going? :)

**Comment by davidg-idealo** [comment] 2018-11-15 11:59
This article is a good summarize regarding this problem.
https://medium.com/@kristine.jetzke_11938/wrong-sleuth-trace-ids-for-hystrix-timeouts-a61f00780462
We decided to downgrade to Hystrix 1.5.11 to get the origin traceIds within the fallback.

**Comment by tinexw** [comment] 2018-11-19 08:41
Hystrix 1.5.11 was re-released as 1.5.18. Thus, the issue is also fixed in this version.

**Comment by marcingrzejszczak** [comment] 2018-11-19 08:51
Ok so I guess I'm closing the issue

**Closed by marcingrzejszczak** 2018-11-19 08:51 UTC
Labels: documentation, feedback-provided, icebox
