### ISSUE TITLE
TraceId and SpanId are unavailable in Spring Kafka Error Handlers

### ISSUE THREAD

**Issue by m-grzesiak** [spring-cloud/spring-cloud-sleuth#1659] opened 2020-06-01 12:50 UTC
I'm using Spring Kafka 2.3.4 and spring-cloud-starter-sleuth with 2.2.0 version. The problem is that it looks like the traceId and spanId are shown in logs during event processing which has been consumed via `@KafkaListener`, but when something went wrong and an exception has been thrown, span is cleared out (?) and unavailable (spanId and traceId are not showing up in the logs). It looks like those ids are clearing out somehow when SeekToCurrentErrorHandler enters the game. I'm using a default Spring Cloud Sleuth configuration, with a proper logback logging pattern.

```
@Bean
public ConcurrentKafkaListenerContainerFactory<String, Object> kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, Object> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.setConcurrency(1);
        factory.setErrorHandler(new SeekToCurrentErrorHandler());
        return factory;
}

private ConsumerFactory<String, Object> consumerFactory() {
        DefaultKafkaConsumerFactory<String, Object> consumerFactory = new DefaultKafkaConsumerFactory<>(kafkaProperties.buildConsumerProperties());
        consumerFactory.setValueDeserializer(jsonValueDeserializer());
        return consumerFactory;
}
```

The question is does it work as designed or is this an unexpected behavior? It is possible to do something to print those ids in logs when the Kafka exception handler has been invoked?

**Comment by marcingrzejszczak** [comment] 2020-06-01 12:51
Can you first try with the latest available GA version (2.2.3.RELEASE)?

**Comment by m-grzesiak** [comment] 2020-06-01 14:05
I just tried - still the same.

**Comment by jonatan-ivanov** [comment] 2020-12-23 00:57
I took a quick look at this as well and as it was kind of expected, it seems this is caused by the same thing, the error happening happens after the Span is closed, I created a sample project for it using the Kafka Sample 1 app: https://github.com/jonatan-ivanov/sleuth-gh-1659

This is where the tracing instrumentation happens: [MessageListenerMethodInterceptor.java#L56-L59](https://github.com/spring-cloud/spring-cloud-sleuth/blob/ca2e15fc769ef4ce9988ac4c1142d4aa44b28f0f/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/instrument/messaging/MessageListenerMethodInterceptor.java#L56-L59) 
And this is where the error handling takes place: [KafkaMessageListenerContainer.java#L1992-L2003](https://github.com/spring-projects/spring-kafka/blob/043090d0a647b468bc21ca2f2190972f6d450b57/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L1992-L2003)

**Comment by jonatan-ivanov** [comment] 2021-02-09 22:08
Closing this in favor of https://github.com/spring-projects/spring-kafka/issues/1704

**Closed by jonatan-ivanov** 2021-02-09 22:08 UTC
Labels: bug

**Comment by MaksimMyshkin** [comment] 2021-12-12 10:47
In issue https://github.com/spring-projects/spring-kafka/issues/1704 was implemented additional hook for batch and record interceptors that triggering **after** error handling. I think Spring Sleuth can use this hooks to implement logic that will not clear tracing context before error handling.

Can we reopen the issue to consider this or I must open a new issue?
