### ISSUE TITLE
Remove the STOMP workaround

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-sleuth#1325] opened 2019-04-02 12:11 UTC
Remove the STOMP workaround introduced by https://github.com/spring-cloud/spring-cloud-sleuth/pull/1323

**Comment by Johannes-Rost** [comment] 2021-01-27 10:22
We have encountered an error with spring-cloud-sleuth-instrumentation-3.0.0 and spring-messaging-5.3.3, that leads us to the workaround, introduced by #1323 in MessageHeaderPropagatorSetter.ensureNativeHeadersAreMutable(...). It looks like the assumbtions made for this workaround are no longer valid.

It seems to happen with general messages such as CONNECT, DISCONNECT and HEARTBEAT.
We are seeing this error only on Endpoints with `@SubscribeMapping`

```
Exception in thread "clientInboundChannel-1" org.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=byte[0], headers={simpMessageType=CONNECT, stompCommand=CONNECT, nativeHeaders={}, simpSessionAttributes={}, simpHeartbeat=[J@3c231a73, simpUser=JwtAuthenticationToken [Principal=org.springframework.security.oauth2.jwt.Jwt@aa643256, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=127.0.0.1, SessionId=null], Granted Authorities=[XXX, XXX]], simpSessionId=29ec859d-4810-81b3-1f6f-1cc388edba15}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@32e4e387 in WebSocketAnnotationMethodMessageHandler[prefixes=[/topics/]]; nested exception is java.lang.IllegalStateException: Already immutable, failedMessage=GenericMessage [payload=byte[0], headers={simpMessageType=CONNECT, stompCommand=CONNECT, nativeHeaders={}, simpSessionAttributes={}, simpHeartbeat=[J@3c231a73, simpUser=JwtAuthenticationToken [Principal=org.springframework.security.oauth2.jwt.Jwt@aa643256, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=127.0.0.1, SessionId=null], Granted Authorities=[XXX, XXX]], simpSessionId=29ec859d-4810-81b3-1f6f-1cc388edba15}]
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:153)
at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: Already immutable
at org.springframework.util.Assert.state(Assert.java:76)
at org.springframework.messaging.support.MessageHeaderAccessor$MutableMessageHeaders.getRawHeaders(MessageHeaderAccessor.java:649)
at org.springframework.messaging.support.MessageHeaderAccessor.setHeader(MessageHeaderAccessor.java:304)
at org.springframework.messaging.support.MessageHeaderAccessor.removeHeader(MessageHeaderAccessor.java:336)
at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.ensureNativeHeadersAreMutable(MessageHeaderPropagatorSetter.java:88)
at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.removeAnyTraceHeaders(MessageHeaderPropagatorSetter.java:62)
at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.beforeHandle(TracingChannelInterceptor.java:324)
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.applyBeforeHandle(ExecutorSubscribableChannel.java:167)
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:140)
... 4 more
```

Here is a second instance with a slightly different stack trace:

```
Exception in thread "clientInboundChannel-689" org.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=byte[1], headers={simpMessageType=HEARTBEAT, nativeHeaders={}, simpSessionAttributes={}, simpHeartbeat=[J@6f854a97, simpUser=JwtAuthenticationToken [Principal=org.springframework.security.oauth2.jwt.Jwt@46bc1d1d, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=127.0.0.1, SessionId=null], Granted Authorities=[...]], simpSessionId=803f9a33-12fc-9937-f2b0-c5a265331eb0}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@6142a917 in SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@168229e3]; nested exception is java.lang.IllegalStateException: Already immutable, failedMessage=GenericMessage [payload=byte[1], headers={simpMessageType=HEARTBEAT, nativeHeaders={}, simpSessionAttributes={}, simpHeartbeat=[J@6f854a97, simpUser=JwtAuthenticationToken [Principal=org.springframework.security.oauth2.jwt.Jwt@46bc1d1d, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=127.0.0.1, SessionId=null], Granted Authorities=[XXX, XXX]], simpSessionId=803f9a33-12fc-9937-f2b0-c5a265331eb0}]
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:153)
at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: Already immutable
at org.springframework.util.Assert.state(Assert.java:76)
at org.springframework.messaging.support.NativeMessageHeaderAccessor.removeNativeHeader(NativeMessageHeaderAccessor.java:277)
at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.removeAnyTraceHeaders(MessageHeaderPropagatorSetter.java:62)
at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.beforeHandle(TracingChannelInterceptor.java:324)
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.applyBeforeHandle(ExecutorSubscribableChannel.java:167)
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:140)
... 4 more
```

Do you think it will be fixed with this issue?

**Comment by marcingrzejszczak** [comment] 2021-02-01 12:30
We'll need to sit down with @jonatan-ivanov and @rstoyanchev to ensure that the whole Sleuth & messaging (including STOMP) integration works fine...

In the meantime can you provide us with a sample that replicates this issue?

**Comment by Johannes-Rost** [comment] 2021-02-08 09:44
Unfortunately, we could not isolate an example that reproduces the error.

**Comment by foal** [comment] 2021-04-12 06:54
Any progress on this issue?

**Comment by marcingrzejszczak** [comment] 2021-04-12 06:55
No, because we can't isolate it. Do you have a sample that we can work on?

**Comment by foal** [comment] 2021-04-12 07:07
I have it in my production system, but it very hard to isolate it (same case). The issue appears after upgrade to SpringBoot 2.4.2 from 2.2.12

**Comment by Johannes-Rost** [comment] 2021-04-12 14:35
Since we moved back from Spring Boot 2.4.x/Spring Cloud 2020.0.x to Spring Boot 2.3.x/Spring Cloud Hoxton.SRx the Error disappeared.

**Comment by sunbro5** [comment] 2021-05-03 00:43
Hi, we have same problem in production (also after upgrade springboot to 2.4.2).

During investigation found out that we have in ExecutorSubscribableChannel 3 _handlers_ : 
WebSocketAnnotationMethodMessageHandler[prefixes=[/app/]], 
SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@cd925b1], 
UserDestinationMessageHandler[DefaultUserDestinationResolver[prefix=/user/]]
and in _executorInterceptors_ TracingChannelInterceptor.

TracingChannelInterceptor is checking mutable headers and setting header to immutable from message which he get in ExecutorSubscribableChannel.
So when 3 threads are runned for 3 handlers with one message sometimes one thread set immutable headers also for another thread which just called isMutable() in MessageHeaderPropagatorSetter#removeAnyTraceHeaders and  exception occured.
ExecutorSubscribableChannel#sendInternal



```
Exception in thread "clientInboundChannel-17" org.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE, nativeHeaders={id=[ws-sub-sports-counters], destination=[/topic/counters]}, simpSessionAttributes={}, simpHeartbeat=[J@71e71c2f, simpSubscriptionId=ws-sub-sports-counters, simpSessionId=uo0khipa, simpDestination=/topic/counters}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@46e27b4f in WebSocketAnnotationMethodMessageHandler[prefixes=[/app/]]; nested exception is java.lang.IllegalStateException: Already immutable, failedMessage=GenericMessage [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE, nativeHeaders={id=[ws-sub-sports-counters], destination=[/topic/counters]}, simpSessionAttributes={}, simpHeartbeat=[J@71e71c2f, simpSubscriptionId=ws-sub-sports-counters, simpSessionId=uo0khipa, simpDestination=/topic/counters}]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:153)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:63)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:63)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Already immutable
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.messaging.support.MessageHeaderAccessor$MutableMessageHeaders.getRawHeaders(MessageHeaderAccessor.java:649)
	at org.springframework.messaging.support.MessageHeaderAccessor.setHeader(MessageHeaderAccessor.java:304)
	at org.springframework.messaging.support.MessageHeaderAccessor.removeHeader(MessageHeaderAccessor.java:336)
	at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.ensureNativeHeadersAreMutable(MessageHeaderPropagatorSetter.java:94)
	at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.removeAnyTraceHeaders(MessageHeaderPropagatorSetter.java:68)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.beforeHandle(TracingChannelInterceptor.java:324)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.applyBeforeHandle(ExecutorSubscribableChannel.java:167)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:140)
	... 5 more
	
```
	
	
`2021-05-03 02:17:19,630 b56788ab54fc25a3 [clientInboundChannel-17] DEBUG o.s.c.s.i.m.TracingChannelInterceptor - Received a message in before handle GenericMessage [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE, nativeHeaders={id=[ws-sub-sports-counters], destination=[/topic/counters], b3=[b56788ab54fc25a3-b56788ab54fc25a3-0]}, b3=b56788ab54fc25a3-b56788ab54fc25a3-0, simpSessionAttributes={}, simpHeartbeat=[J@71e71c2f, simpSubscriptionId=ws-sub-sports-counters, simpSessionId=uo0khipa, simpDestination=/topic/counters}]`
`2021-05-03 02:17:19,630 b56788ab54fc25a3 [clientInboundChannel-16] DEBUG o.s.c.s.i.m.TracingChannelInterceptor - Received a message in before handle GenericMessage [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE, nativeHeaders={id=[ws-sub-sports-counters], destination=[/topic/counters], b3=[b56788ab54fc25a3-b56788ab54fc25a3-0]}, b3=b56788ab54fc25a3-b56788ab54fc25a3-0, simpSessionAttributes={}, simpHeartbeat=[J@71e71c2f, simpSubscriptionId=ws-sub-sports-counters, simpSessionId=uo0khipa, simpDestination=/topic/counters}]`
`2021-05-03 02:17:19,630 b56788ab54fc25a3 [clientInboundChannel-15] DEBUG o.s.c.s.i.m.TracingChannelInterceptor - Received a message in before handle GenericMessage [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE, nativeHeaders={id=[ws-sub-sports-counters], destination=[/topic/counters], b3=[b56788ab54fc25a3-b56788ab54fc25a3-0]}, b3=b56788ab54fc25a3-b56788ab54fc25a3-0, simpSessionAttributes={}, simpHeartbeat=[J@71e71c2f, simpSubscriptionId=ws-sub-sports-counters, simpSessionId=uo0khipa, simpDestination=/topic/counters}]`

Could this help with fix?

**Comment by marcingrzejszczak** [comment] 2021-05-05 06:50
cc @rstoyanchev - this can be helpful for your `TracingChannelInterceptor` analysis

**Comment by Ulya0302** [comment] 2021-07-05 15:40
On our project we have same issue, include next errors:
1)

```
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:751)
	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:749)
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:507)
	at java.base/java.util.LinkedHashMap.<init>(LinkedHashMap.java:384)
	at org.springframework.util.LinkedMultiValueMap.<init>(LinkedMultiValueMap.java:72)
	at org.springframework.messaging.support.NativeMessageHeaderAccessor.toNativeHeaderMap(NativeMessageHeaderAccessor.java:100)
	at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.ensureNativeHeadersAreMutable(MessageHeaderPropagatorSetter.java:85)
	at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.removeAnyTraceHeaders(MessageHeaderPropagatorSetter.java:62)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.beforeHandle(TracingChannelInterceptor.java:324)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.applyBeforeHandle(ExecutorSubscribableChannel.java:167)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:140)
```
2)
```
Caused by: java.lang.IllegalStateException: Already immutable
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.messaging.support.NativeMessageHeaderAccessor.removeNativeHeader(NativeMessageHeaderAccessor.java:277)
	at org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagatorSetter.removeAnyTraceHeaders(MessageHeaderPropagatorSetter.java:62)
	at org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor.beforeHandle(TracingChannelInterceptor.java:324)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.applyBeforeHandle(ExecutorSubscribableChannel.java:167)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:140)
```
Errors fail on different actions: CONNECT, UNSUBSCRIBE, DISCONNECT 
It start happens after upgrading to Spring Boot Version 2.5.2, Spring cloud 2020.0.3 from spring boot 2.1.15 and spring cloud greenwich.sr6

**Comment by marcingrzejszczak** [comment] 2021-07-12 10:08
Is there an option for anyone to provide a sample that we can work with?

**Comment by skolorz** [comment] 2021-12-16 13:43
@marcingrzejszczak @jonatan-ivanov @rstoyanchev 
Are still looking for a sample to reproduce this issue?

**Comment by marcingrzejszczak** [comment] 2021-12-16 14:07
Yes please

**Comment by skolorz** [comment] 2021-12-21 07:18
@marcingrzejszczak 

https://github.com/skolorz/sample-app

try mvn test

**Comment by xenomorthious** [comment] 2022-01-13 13:11
Hi, I'm facing the same issue as well. Any news?

**Comment by marcingrzejszczak** [comment] 2022-01-20 08:35
No news for now

**Comment by kalaider** [comment] 2022-01-26 15:50
Same issue in our setup with spring-websocket and stomp message broker configured.

In our case ExecutorSubscribableChannel bound to incoming websocket has 3 subscribers (WebSocketAnnotationMethodMessageHandler, UserDestinationMessageHandler and StompBrokerRelayMessageHandler). The problematic scenario is as follows:
* After being processed by StompSubProtocolHandler and wrapped to `org.springframework.messaging.Message`, incoming message is passed to ExecutorSubscribableChannel where it is processed by preSend interceptors, including TracingChannelInterceptor, that runs last.
* `TracingChannelInterceptor#preSend` leaves headers mutable by issuing `setLeaveMutable(true)` on them.
* ExecutorSubscribableChannel then spawns SendTask per each subscriber, where beforeHandle interceptors are applied to the message prior to passing it to the actual subscriber.
* `TracingChannelInterceptor#beforeHandle` tries to reuse mutable headers if possible. Provided that SendTasks run in a thread pool, mutation of headers leads to race condition when ExecutorSubscribableChannel has multiple subscribers.

The problem was introduced in 354549035b559fa691814c02eb81362eb06bcf11.

https://github.com/spring-cloud/spring-cloud-sleuth/blob/354549035b559fa691814c02eb81362eb06bcf11/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java#L195-L208

Line 197 changed from `MessageHeaderAccessor.getMutableAccessor(originalMessage);` to `mutableHeaderAccessor(originalMessage);`. The latter internally calls `setLeaveMutable(true)` on the result of `MessageHeaderAccessor#getMutableAccessor()`.

The current workaround is to install ImmutableMessageChannelInterceptor after TracingChannelInterceptor:
```java
@Bean
@ConditionalOnProperty("spring.sleuth.enabled")
public GlobalChannelInterceptorWrapper afterSleuthImmutableMessageChannelInterceptor(
    SleuthIntegrationMessagingProperties properties  // or SleuthMessagingProperties.Integration in 2.x.x
) {
    var interceptor = new GlobalChannelInterceptorWrapper(new ImmutableMessageChannelInterceptor());
    interceptor.setOrder(Ordered.LOWEST_PRECEDENCE);
    interceptor.setPatterns(properties.getPatterns());
    return interceptor;
}
```

**Closed** 2022-01-27 11:30 UTC
Labels: icebox, feedback-provided

**Comment by marcingrzejszczak** [comment] 2022-01-27 11:31
The Spring Integration & Websocket instrumentation needs some serious refactoring. What I did is I applied the workaround and double checked that the provided sample now works fine. We will rewrite the whole instrumentation from scratch for Spring Framework 6 & Spring Boot 3.
