### ISSUE TITLE
Tracing issues when mixing @FeignClient (with Eureka) clients and clients built manually with Feign.Builder

### ISSUE THREAD

**Issue by yngwietiger** [spring-cloud/spring-cloud-sleuth#835] opened 2018-01-24 02:03 UTC
Hi, 

We're trying to enable Sleuth tracing in a Spring Boot project that has several Feign clients. 

(BTW, this is related to: https://stackoverflow.com/questions/48211360/how-to-implement-sleuth-tracing-with-feign-builder)

Out of the box, the @FeignClient beans work fine. I see the B3 headers getting propagated to downstream services. Note that these downstream services are registered with Eureka.

However, the clients built with the builder do not have tracing (as expected, since they're not instrumented). 

But what is the best approach for this?

I tried to enable tracing by declaring a Spring Bean of type Client, and letting it get instrumented at creation time...

```
@Configuration
@Component
public class FeignClientProducer {

    private static final Logger LOGGER = LoggerFactory.getLogger(FeignClientProducer.class);

    @Bean
    @Scope("prototype")
    public Client getFeignClient() {
        Client client = new feign.okhttp.OkHttpClient();
        LOGGER.info("getFeignClient: {}", client);
        return client;
    }
}
```

```
@Component
public class FeignTargetBuilder {

    @Autowired
    private FeignClientProducer feignClientProducer;

    /**
     * Get a new Feign Client bean.
     * With Sleuth enabled, this will be wrapped by a tracer client.
     * @return
     */
    @Override
    public Client getFeignClient() {
        Client client = feignClientProducer.getFeignClient();
        LOGGER.info("getFeignClient: {}", client);
        return client;
    }
}
```

And that works to enable tracing for the manually built Clients. I can see the Client getting wrapped by its tracing implementation...

```
20:24:07.144 [RMI TCP Connection(2)-127.0.0.1]  INFO [fweb,,,] p.i.feign.FeignClientProducer - getFeignClient: feign.okhttp.OkHttpClient@38c76411 (FeignClientProducer.java:29) 
20:24:07.145 [RMI TCP Connection(2)-127.0.0.1]  INFO [fweb,,,] p.i.feign.FeignTargetBuilder - getFeignClient: org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient@24aeb8db (FeignTargetBuilder.java:51) 
```

But after that, the @FeignClients stop working. In the logs, you see an UnknownHostException when trying to connect to a Eureka-registered downstream service....

```
Caused by: feign.RetryableException: screenshot executing GET http://screenshot/screenshot/render?url=http%3A%2F%2Fwww.cnn.com&width=800&height=600
	at feign.FeignException.errorExecuting(FeignException.java:67)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:102)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy436.render(Unknown Source)
	at XXXXX.ScreenshotService.buildRequestUrlAndGetRenderedUrlImageInputStream(ScreenshotService.java:46)
	at XXXXX.handleRequest(BaseScreenshotService.java:61)
	... 219 common frames omitted
Caused by: java.net.UnknownHostException: screenshot
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at okhttp3.Dns$1.lookup(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:170)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:136)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:81)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:153)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient.execute(TraceFeignClient.java:92)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient$$FastClassBySpringCGLIB$$6ff9a9a7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignAspect.feignClientWasCalled(TraceFeignAspect.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient$$EnhancerBySpringCGLIB$$6b0b17f5.execute(<generated>)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	... 224 common frames omitted
```

Seems the Client bean is getting automatically picked up and injected into the @FeignClient beans, causing the issue above?

Is there a better way to handle tracing for manually (non-@FeignClient) built Clients?

Should I just try to add some type of request interceptor to inject the B3 headers into the request? (although, this seems like a hack)

In the meantime, I'm starting down the path of converting these to @FeignClient beans.

Just wanted to know if there's a better approach for something like this.

Thanks in advance,

yngwietiger

**Comment by marcingrzejszczak** [comment] 2018-03-01 08:40
Can you create a sample that reproduces this problem?

**Comment by yngwietiger** [comment] 2018-03-01 11:27
I actually got everything working, by switching the Feign Core clients to Spring Cloud @FeignClient beans. 

I'm not even sure if what we were doing before is a common scenario (i.e. mixing Feign Core clients and Spring Boot @FeignClient beans in the same application + enabling Sleuth). 

Thanks.

**Comment by marcingrzejszczak** [comment] 2018-03-01 11:28
Ok then, I'm closing this issue for now, and if there's someone else with a similar problem then we'll think of addressing it. Thanks!

**Closed by marcingrzejszczak** 2018-03-01 11:28 UTC
Labels: waiting for feedback

**Comment by caoyangfan** [comment] 2018-04-10 03:14
Hi 
    I want use the raw feign not the spring cloud feign and with spring cloud sleuth in project.
   The custom feignClient like the code.
```
@Component
@Import(FeignClientsConfiguration.class)
public class ServiceHiImpl implements ServiceHi {

    private ServiceHiClient serviceHiClient;

    @Autowired
    private void buildUpHttpClient(Client client, Encoder feignEncoder, Contract feignContract) {
        this.serviceHiClient = Feign.builder().client(client).encoder(feignEncoder).contract(feignContract)
                .options(new Options((int) SECONDS.toMillis(10), (int) SECONDS.toMillis(10000))).logger(new Logger.ErrorLogger())
                .logLevel(Logger.Level.FULL).target(ServiceHiClient.class, "http://localhost:8090");
    }

    @Override
    public String createInstance(RequestData requestData) throws Exception {
        return serviceHiClient.createInstance(requestData);
    }

}

@Configuration
public class DemoClientConfiguration {
    @Bean
    public OkHttpClient okHttpClient() {
        return new OkHttpClient();
    }
}
```
but it throws the exception
`[2m2018-04-10 11:13:44.767[0;39m [32m[demo-client,4dfb58bbf2c90862,11eb1b0b5a7d0437,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mcom.example.demo.MessageListener        [0;39m [2m:[0;39m Get message with body: 'hello'
[ServiceHiClient#createInstance] ---> POST http://localhost:8090/createInstance HTTP/1.1
[ServiceHiClient#createInstance] Content-Type: application/json;charset=UTF-8
[ServiceHiClient#createInstance] Content-Length: 37
[ServiceHiClient#createInstance] 
[ServiceHiClient#createInstance] {"data":"message received!: 'hello'"}
[ServiceHiClient#createInstance] ---> END HTTP (37-byte body)
[2m2018-04-10 11:13:44.886[0;39m [32m[demo-client,4dfb58bbf2c90862,9b7e70cc3aa4d715,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36ms.c.a.AnnotationConfigApplicationContext[0;39m [2m:[0;39m Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@82f3de4: startup date [Tue Apr 10 11:13:44 CST 2018]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1e63d216
[2m2018-04-10 11:13:44.978[0;39m [32m[demo-client,4dfb58bbf2c90862,9b7e70cc3aa4d715,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mf.a.AutowiredAnnotationBeanPostProcessor[0;39m [2m:[0;39m JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[2m2018-04-10 11:13:45.197[0;39m [32m[demo-client,4dfb58bbf2c90862,9b7e70cc3aa4d715,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mc.netflix.config.ChainedDynamicProperty [0;39m [2m:[0;39m Flipping property: localhost.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
[2m2018-04-10 11:13:45.266[0;39m [32m[demo-client,4dfb58bbf2c90862,9b7e70cc3aa4d715,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mc.n.u.concurrent.ShutdownEnabledTimer   [0;39m [2m:[0;39m Shutdown hook installed for: NFLoadBalancer-PingTimer-localhost
[2m2018-04-10 11:13:45.383[0;39m [32m[demo-client,4dfb58bbf2c90862,9b7e70cc3aa4d715,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mc.netflix.loadbalancer.BaseLoadBalancer [0;39m [2m:[0;39m Client: localhost instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=localhost,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
[2m2018-04-10 11:13:45.417[0;39m [32m[demo-client,4dfb58bbf2c90862,9b7e70cc3aa4d715,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mc.n.l.DynamicServerListLoadBalancer     [0;39m [2m:[0;39m Using serverListUpdater PollingServerListUpdater
[2m2018-04-10 11:13:45.451[0;39m [32m[demo-client,4dfb58bbf2c90862,9b7e70cc3aa4d715,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mc.n.l.DynamicServerListLoadBalancer     [0;39m [2m:[0;39m DynamicServerListLoadBalancer for client localhost initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=localhost,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:ConsulServerList{serviceId='localhost', tag=null}
[2m2018-04-10 11:13:46.544[0;39m [31m[demo-client,4dfb58bbf2c90862,11eb1b0b5a7d0437,true][0;39m [35m3696[0;39m [2m---[0;39m [2m[       Thread-4][0;39m [36mcom.example.demo.MessageListener        [0;39m [2m:[0;39m error while exectue http server:

java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: localhost
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:71)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClient.execute(TraceFeignClient.java:92)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignAspect.feignClientWasCalled(TraceFeignAspect.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient$$EnhancerBySpringCGLIB$$6e9132e5.execute(<generated>)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy85.createInstance(Unknown Source)
	at com.example.demo.feign.ServiceHiImpl.createInstance(ServiceHiImpl.java:32)
	at com.example.demo.MessageListener.send(MessageListener.java:90)
	at com.example.demo.MessageListener.message(MessageListener.java:71)
	at com.hi3project.vineyard.comm.stomp.gozirraws.Stomp.receive(Stomp.java:541)
	at com.hi3project.vineyard.comm.stomp.gozirraws.Receiver.receive(Receiver.java:76)
	at com.hi3project.vineyard.comm.stomp.gozirraws.Receiver.run(Receiver.java:102)
Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: localhost
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable.unsafeSubscribe(Observable.java:10211)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10307)
	at rx.Observable.subscribe(Observable.java:10274)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:342)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:117)
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63)
	... 24 common frames omitted`
