### ISSUE TITLE
spring-cloud-sleuth-dependencies modules use xml-maven-plugin to generate flattened-pom

### ISSUE THREAD

**Issue by ruansheng8** [spring-cloud/spring-cloud-sleuth#2238] opened 2022-12-01 01:22 UTC
**Is your feature request related to a problem? Please describe.**
I saw `spring-cloud-sleuth-dependencies` module has `.flattened-pom.xml` file , it's an automatically generated based on the `flatten-maven-plugin` . Was `.flattened-pom.xml` committed to the remote repository because of the version of pom.xml is not automatically generated ? If so , Maybe we can use `xml-maven-plugin` to solve it .

**Describe the solution you'd like**
Use `xml-maven-plugin` to solve it .

**Comment by marcingrzejszczak** [comment] 2022-12-01 08:07
I'm sorry but I don't understand the problem. Can you elaborate on what the problem is exactly and how the plugin would solve it?

**Comment by ruansheng8** [comment] 2022-12-01 08:35
> I'm sorry but I don't understand the problem. Can you elaborate on what the problem is exactly and how the plugin would solve it?
1. `.flattened-pom.xml` is redundant file, it should be removed , i guess this file was commited by mistake .
2. `spring-cloud-sleuth`  project defines a version ( like `3.1.6-SNAPSHOT` )  in every module , i think it should only be defined once on the parent node ( /spring-cloud-sleuth/pom.xml ) , refer to `spring boot` ( https://github.com/spring-projects/spring-boot/tree/2.2.x ) , child module use `revision` like
 ```	
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-parent</artifactId>
		<version>${revision}</version>
		<relativePath>../spring-boot-parent</relativePath>
	</parent>
```
During the version upgrade, you only need to change the version number of the parent node.
Incidentally, this has no effect on the functionality of the project, other than optimizing project version-dependency management

**Comment by marcingrzejszczak** [comment] 2022-12-01 10:03
Yeah, so we committed that by mistake. Feel free to file a PR to remove it.

As for versions - we update them automatically with our releasing tools so that's not a problem. 

I will close the issue for now.

**Closed as completed by marcingrzejszczak** 2022-12-01 10:03 UTC
Labels: question
