### ISSUE TITLE
Anyway to support ApplicationRunner or CommandLineRunner?

### ISSUE THREAD

**Issue by abccbaandy** [spring-cloud/spring-cloud-sleuth#1960] opened 2021-05-31 10:50 UTC
As title

I have an `ApplicationRunner` to call some http request, but seems sleuth doesn't generate trace id for me.

Now it's too hard to debug those http request log, because they are all have different trace id in those api service log.

**Comment by marcingrzejszczak** [comment] 2021-05-31 11:02
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/1903

**Closed** 2021-05-31 11:02 UTC
