### ISSUE TITLE
binaryAnnotations value is unknown

### ISSUE THREAD

**Issue by 358235737** [spring-cloud/spring-cloud-sleuth#819] opened 2017-12-29 07:43 UTC
HI Sir :
  while I use sleuth & zipkin and has DiscoveryClient, but the report always has the unkown value as below :

```
[
  {
    "traceId": "722205ac2639b2a2",
    "id": "722205ac2639b2a2",
    "name": "http:/test/test",
    "timestamp": 1514533084054000,
    "duration": 55258,
    "annotations": [
      {
        "timestamp": 1514533084054000,
        "value": "sr",
        "endpoint": {
          "serviceName": "openapi-gateway-core",
          "ipv4": "10.243.245.97",
          "port": 8780
        }
      },
      {
        "timestamp": 1514533084088000,
        "value": "ss",
        "endpoint": {
          "serviceName": "openapi-gateway-core",
          "ipv4": "10.243.245.97",
          "port": 8780
        }
      }
    ],
    "binaryAnnotations": [
      {
        "key": "spring.instance_id",
        "value": "SQSZ-L1751.paicdom.local:openapi-gateway-core:8780",
        "endpoint": {
          "serviceName": "openapi-gateway-core",
          "ipv4": "10.243.245.97",
          "port": 8780
        }
      }
    ]
  },
  {
    "traceId": "722205ac2639b2a2",
    "id": "8bca7be7b3b7fb58",
    "name": "http:/test/test",
    "parentId": "722205ac2639b2a2",
    "timestamp": 1514533084091000,
    "duration": 97,
    "binaryAnnotations": [
      {
        "key": "lc",
        "value": "unknown",
        "endpoint": {
          "serviceName": "openapi-gateway-core",
          "ipv4": "10.243.245.97",
          "port": 8780
        }
      }
    ]
  }
]
```

and the application.properties is :

```
spring.cloud.zookeeper.connectString=10.25.174.28:21800
#spring.cloud.zookeeper.connectString=10.25.174.36:2181
spring.cloud.zookeeper.discovery.register=true
#spring.cloud.zookeeper.discovery.instanceHost=10.25.174.28
spring.cloud.zookeeper.discovery.instanceHost=SQSZ-L1751
spring.cloud.zookeeper.discovery.instancePort=${server.port}
spring.zipkin.base-url=http://10.25.174.28:38006
spring.zipkin.locator.discovery.enabled = true
spring.sleuth.scheduled.enabled=false
spring.sleuth.enabled=true
spring.cloud.loadbalancer.retry.enabled=false
spring.sleuth.sampler.percentage=1
```

**Comment by marcingrzejszczak** [comment] 2018-01-04 09:29
When you create an issue there's this default text filled out

```

Bug report

Please provide details of the problem, including the version of Spring Cloud that you
are using. If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.
```

Could you please update this issue according to our policy of filing issues? Thanks a lot!

**Comment by 358235737** [comment] 2018-01-15 07:55
org.springframework.boot:spring-boot-starter-parent:1.5.3.RELEASE
org.springframework.cloud:spring-cloud-dependencies:Dalston.SR3

package com.pa.springcloud;

import com.pa.core.SpringCloudIntializeContext;
import com.pa.core.SpringCloudXmlAnnotationContext;
import java.util.HashSet;
import java.util.Set;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration;
import org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration;
import org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration;
import org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration;
import org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration;
import org.springframework.cloud.client.circuitbreaker.EnableCircuitBreaker;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.netflix.hystrix.dashboard.EnableHystrixDashboard;
import org.springframework.web.WebApplicationInitializer;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

@EnableWebMvc
@SpringBootApplication(exclude={DataSourceAutoConfiguration.class, HibernateJpaAutoConfiguration.class, JpaRepositoriesAutoConfiguration.class, DispatcherServletAutoConfiguration.class, EmbeddedServletContainerAutoConfiguration.class, ErrorMvcAutoConfiguration.class, JmxAutoConfiguration.class, WebMvcAutoConfiguration.class, WebSocketAutoConfiguration.class})
@EnableDiscoveryClient
@EnableCircuitBreaker
@EnableHystrixDashboard
public class SpringCloudApplicationOnStartup
  implements WebApplicationInitializer
{
  public static final String CONTEXT_INITIALIZER_CLASSES_PARAM = "contextInitializerClasses";
  public static final String CONTEXT_CLASS_PARAM = "contextClass";

  public void onStartup(ServletContext servletContext)
    throws ServletException
  {
    try
    {
      String clazzName = SpringCloudIntializeContext.class.getName();
      String className = servletContext.getInitParameter("contextInitializerClasses");
      if ((className != null) && (className != ""))
        className = className + "," + clazzName;
      else {
        className = clazzName;
      }
      servletContext.setInitParameter("contextInitializerClasses", className);

      servletContext.setInitParameter("contextClass", SpringCloudXmlAnnotationContext.class.getName());
    }
    catch (Throwable ex) {
      throw new IllegalStateException(ex);
    }
  }

  static
  {
    Set names = new HashSet();
    names.add("servletContextInitParams");
    names.add("servletConfigInitParams");
    names.add("jndiProperties");
  }
}

**Comment by marcingrzejszczak** [comment] 2018-01-15 09:10
I will close this issue cause I don't understand anything that you're pasting. The code is not formatted and the problem is not described properly.

I can suggest you upgrade to recent `Edgware` release and see if the problem persists. If not, please invest time in improving the quality of the filed issue because currently I'm unable to help you.

**Closed by marcingrzejszczak** 2018-01-15 09:10 UTC
Labels: waiting for feedback
