### ISSUE TITLE
Getting HTTP-Headers for span with not instrumented client

### ISSUE THREAD

**Issue by padjon** [spring-cloud/spring-cloud-sleuth#662] opened 2017-07-27 17:22 UTC
Hello,
i have a microservice architecture with a gateway-microservice which routes all of the requests to the microservices. The Client, which sends the initial requests to the microservice architecture is not instrumented.

I would like to know the headers(path, method) of the requests which are sent to the gateway. But the gateway is the first instrumented service and the rest-API calls towards the gateway are done by the browser, so there is no CS; CR;HTTP-annotations for the first span, only the SR;SS annotations.

Is there a way to configure the server, to add the HTTP-annotations to the first span (no parrent) of the server?

Background: Im working on an architecture discovery system for which i need to know the method of the request which was made by the user. I need that information for the mapping of business activities.

My suggestion would be to add the http-headers to the span created by the server if there is no trace-id in the request => its the first instrumented host

**Comment by marcingrzejszczak** [comment] 2017-08-17 15:51
Duplicate of #668

**Closed by marcingrzejszczak** 2017-08-17 15:51 UTC
Labels: duplicate
