### ISSUE TITLE
sleuth with flowable not working

### ISSUE THREAD

**Issue by DekateSainath** [spring-cloud/spring-cloud-sleuth#1833] opened 2021-01-25 14:54 UTC
I have tried to integrate the sleuth with flowable but its not working.
As observer the trace details are not available in api request called using flowable.

**Comment by jonatan-ivanov** [comment] 2021-01-27 22:48
@DekateSainath Could you please provide a minimal sample project that reproduces the issue?

**Comment by spring-cloud-issues** [comment] 2021-02-03 23:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-02-10 23:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-02-10 23:01 UTC
Labels: feedback-reminder, waiting for feedback
