### ISSUE TITLE
TraceWebClientAutoConfiguration in M6 causes circular dependency when using Boot-provided RestTemplateBuilder

### ISSUE THREAD

**Issue by jkuipers** [spring-cloud/spring-cloud-sleuth#856] opened 2018-02-13 09:51 UTC
[circular-dependency-issue.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/1719417/circular-dependency-issue.zip)

See attached sample project: by simply defining a `RestTemplate` bean using an injected `RestTemplateBuilder` while enabling Sleuth support in the latest milestone, the `TraceWebClientAutoConfiguration$RestTemplateConfig` introduces a curcular dependency as it wants to be injected with all beans of type `RestTemplate`. 
I suggest to not rely on injection in that autonconfiguration to break the dependency: this is a blocking issue for us to update to this milestone.

**Comment by marcingrzejszczak** [comment] 2018-02-13 09:51
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/852

**Closed by marcingrzejszczak** 2018-02-13 09:51 UTC

**Comment by jkuipers** [comment] 2018-02-13 09:55
Ah, sorry for not finding the existing issue: I was only looking at the existing open issues, not realizing that this one had been closed already ;)
