### ISSUE TITLE
TraceId and SpanId are not present in logs when using Spring Flux and the async AWS SDK

### ISSUE THREAD

**Issue by jonathannaguin** [spring-cloud/spring-cloud-sleuth#1147] opened 2018-11-28 17:14 UTC
#### Bug report
Spring Boot: 2.1.0.RELEASE
Spring Cloud version: 2.1.0.M2
Sample project: https://github.com/jonathannaguin/sleuth-issue/tree/master

We are using Spring Flux with Spring Sleuth and we have noticed that sometimes the traceId and spanId are not been injected on the MDC/logs. In the test project linked, if you run the success query, you will see that they are not present here:
```
2018-11-28 17:08:54.767 DEBUG [-,87fc67cec7f44409,87fc67cec7f44409,false] 10658 --- [ctor-http-nio-5] org.springframework.sample.Controller    : Performing query against https://google.com
2018-11-28 17:08:54.893 DEBUG [-,,,] 10658 --- [ctor-http-nio-2] org.springframework.sample.Controller    : Success!
2018-11-28 17:08:54.895 DEBUG [-,,,] 10658 --- [ctor-http-nio-2] org.springframework.sample.Controller    : Request handled in 128 milliseconds
```
If you run the other query, they will be present.
```
2018-11-28 17:07:13.434 DEBUG [-,e80db99561823af6,e80db99561823af6,false] 10658 --- [ctor-http-nio-3] org.springframework.sample.Controller    : Performing query against https://doesnotexist.noop
2018-11-28 17:07:13.437  WARN [-,e80db99561823af6,e80db99561823af6,false] 10658 --- [ctor-http-nio-3] org.springframework.sample.Controller    : Error happened doesnotexist.noop: nodename nor servname provided, or not known
2018-11-28 17:07:13.439 DEBUG [-,e80db99561823af6,e80db99561823af6,false] 10658 --- [ctor-http-nio-3] org.springframework.sample.Controller    : Request handled in 5 milliseconds
```

**Comment by rmatec** [comment] 2018-12-17 14:06
Hi,

We have also had this problem in our code. Can I kindly ask to increase the priority?

**Comment by kurtharriger** [comment] 2018-12-17 17:33
I also have run into this issue and I think I understand the cause and workaround. 

In as of brave 4.19.0 newScope was replaced with maybeScope
https://github.com/openzipkin/brave/releases?after=release-4.19.1

maybeScope only calls maybeScope if the scope is not already set.
https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/CurrentTraceContext.java#L122

The current scope is stored in an InheritableThreadLocal and thus automatically copied between threads. 
https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/CurrentTraceContext.java#L178

This is fine if you use the BasicMDCAdapter in slf4j
https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java/org/slf4j/helpers/BasicMDCAdapter.java#L47

However if you are using logback a non-inheritable threadlocal is used.
https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/util/LogbackMDCAdapter.java#L55

Thus when using logback the scope is inherited and newScope is not called and since logback does not copy them, they are lost because the following newScope method is no longer called. 
https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jCurrentTraceContext.java#L80

My first thought was to open issue on logback to use inheritable thread local instead.  However it seems they have previously considered and rejected this.
https://issues.apache.org/jira/browse/LOG4J2-479

So here are some possible workarounds:
- Don't use logback
- Instruct zipkin to a non-inheritable context (inheritable is the default):

```
@Bean
@ConditionalOnProperty(value = "spring.sleuth.log.slf4j.enabled", matchIfMissing = true)
@ConditionalOnMissingBean
public CurrentTraceContext slf4jSpanLogger() {
    return Slf4jCurrentTraceContext.create(CurrentTraceContext.Default.create());
}
```

I think the ideal fix is probably for Slf4jCurrentTraceContext to override maybeScope to check if MDC properties exist otherwise copy from provided context

**Comment by jonathannaguin** [comment] 2018-12-18 17:45
Thanks @kurtharriger, I tried to add that bean to my app but after that I couldn't see any tracing at all on the logs, not sure if that is something that needs to be set inside Sleuth itself?

**Comment by kurtharriger** [comment] 2018-12-18 22:54
I think you also need to explicitly wrap executors using `tracing.currentTraceContext().executorService(...)`.  Perhaps this is not always necessary when using an inheritable context?

**Comment by jonathannaguin** [comment] 2018-12-19 10:05
No idea, to be honest, we may need some help from @marcingrzejszczak?

**Comment by marcingrzejszczak** [comment] 2018-12-19 10:09
You're creating web client manually `        WebClient webClient = WebClient.create(url);`. It must be injected as a bean.

**Comment by jonathannaguin** [comment] 2018-12-19 11:05
@marcingrzejszczak correct, sorry, if I define it as a Bean that small test would work. I had to change the sample test app again in order to reproduce the actual issue we are having. It seems the real problem is related to the new AWS SDK, after invoking it, Sleuth seems to lose its context:
```
2018-12-19 11:52:27.738 DEBUG [-,12eb13dd704d6c66,12eb13dd704d6c66,false] 4550 --- [ctor-http-nio-2] org.springframework.sample.Controller    : Performing query, mode 1
2018-12-19 11:52:29.019  WARN [-,,,] 4550 --- [nc-response-0-0] org.springframework.sample.Controller    : Error happened software.amazon.awssdk.services.ssm.model.ParameterNotFoundException: null (Service: Ssm, Status Code: 400, Request ID: 37dcbbf7-9a76-4d19-932b-f09747949f45)
2018-12-19 11:52:29.073 DEBUG [-,,,] 4550 --- [nc-response-0-0] org.springframework.sample.Controller    : Request handled in 1335 milliseconds
```

**Comment by devinsba** [comment] 2018-12-19 11:42
Your logger here confused things a bit for me when reading through this: https://github.com/jonathannaguin/sleuth-issue/blob/master/src/main/java/org/springframework/sample/Service.java#L11

Other than that, you will probably need to pull in: https://github.com/openzipkin/zipkin-aws/tree/master/brave-instrumentation/aws-java-sdk-v2-core in order to trace the new SDK with sleuth/brave

**Comment by jonathannaguin** [comment] 2018-12-19 13:24
@devinsba I've just fixed the logger for Service (it was a copy/paste mistake). Also, I added that module and setup the aws sdk client with that, it didn't make any difference to the problem, the code executed after the aws sdk call does not have any trace.

**Comment by marcingrzejszczak** [comment] 2018-12-19 14:32
```
         AwsSdkTracing awsSdkTracing = AwsSdkTracing.create(httpTracing);
          ClientOverrideConfiguration configuration = ClientOverrideConfiguration.builder()
.addExecutionInterceptor(awsSdkTracing.executionInterceptor())
```

what is this `awsSdkTracing.executionInterceptor()` ? Are you sure you're using this properly? It doesn't look like anything related to Sleuth really.

**Comment by jonathannaguin** [comment] 2018-12-19 14:35
I saw that provisioning on https://github.com/openzipkin/zipkin-aws/tree/master/brave-instrumentation/aws-java-sdk-v2-core as a way of enabling tracing for the new AWS SDK.

**Comment by marcingrzejszczak** [comment] 2018-12-19 14:37
Ok, so let me close this is issue in Sleuth, until you verify that indeed it's an issue with Sleuth.

**Comment by devinsba** [comment] 2018-12-19 15:36
I took the AWS tracing part out and still hit this issue. I tracked it within the sample to here:

```
Mono.fromFuture(ssmClient.getParameter(request))
```

I see that the `TraceContext` is present up until the point that NIO takes over the AWS request, which is to be expected. The part that puzzles me is that the `flatMap` call no longer has the context BUT once the execution returns to the calling class the context comes back. So something about the `CompletableFuture` the AWS sdk returns is not right, or the `Mono.fromFuture()` method is not being hooked correctly.

I enabled the console reporter and 100% sampling in the example and get the following spans (when AWS is not hooked):

```
{"traceId":"1f6863d12477a073","id":"1f6863d12477a073","kind":"CLIENT","name":"get","timestamp":1545233444941726,"duration":92636,"localEndpoint":{"serviceName":"default","ipv4":"10.128.208.81"},"tags":{"http.method":"GET","http.path":"","http.status_code":"301"}}
{"traceId":"5afba8d4c03c363d","id":"5afba8d4c03c363d","kind":"SERVER","name":"post /query","timestamp":1545233067368280,"duration":377728055,"localEndpoint":{"serviceName":"default","ipv4":"10.128.208.81"},"tags":{"http.method":"POST","http.path":"/query","mvc.controller.class":"Controller","mvc.controller.method":"q"}}
```

With AWS hooked I get:

```
{"traceId":"299f8abb371f2ab6","parentId":"5c256921020d6c2e","id":"51fca3e56821e016","kind":"CLIENT","name":"getparameter","timestamp":1545233681306281,"duration":12386552,"localEndpoint":{"serviceName":"default","ipv4":"10.128.208.81"},"remoteEndpoint":{"serviceName":"ssm"},"tags":{"http.method":"POST","http.path":"/"}}
{"traceId":"299f8abb371f2ab6","parentId":"299f8abb371f2ab6","id":"5c256921020d6c2e","name":"aws-sdk","timestamp":1545233680190083,"duration":14430802,"localEndpoint":{"serviceName":"default","ipv4":"10.128.208.81"},"tags":{"aws.operation":"GetParameter","aws.service_name":"Ssm"}}
{"traceId":"fd4239271680de66","id":"fd4239271680de66","kind":"CLIENT","name":"get","timestamp":1545233696064315,"duration":95819,"localEndpoint":{"serviceName":"default","ipv4":"10.128.208.81"},"tags":{"http.method":"GET","http.path":"","http.status_code":"301"}}
{"traceId":"299f8abb371f2ab6","id":"299f8abb371f2ab6","kind":"SERVER","name":"post /query","timestamp":1545233676795571,"duration":19409141,"localEndpoint":{"serviceName":"default","ipv4":"10.128.208.81"},"tags":{"http.method":"POST","http.path":"/query","mvc.controller.class":"Controller","mvc.controller.method":"q"}}
```

So the hook is not the problem, looks like a Reactor hook is not working correctly. I don't know reactor well enough to go much further

**Comment by marcingrzejszczak** [comment] 2018-12-19 17:10
@smaldini heeeeeelp

**Comment by jonathannaguin** [comment] 2019-01-15 11:54
Is there any updates on this problem?

**Comment by marcingrzejszczak** [comment] 2019-01-15 11:55
As you can see there is none

**Comment by marcingrzejszczak** [comment] 2019-02-21 12:38
Most likely it should be related to the bug in Sleuth and Reactor instrumentation. Please confirm that the problem is gone.

**Closed** 2019-02-21 12:37 UTC
Labels: waiting-for-triage
