### ISSUE TITLE
Zipkin HTTP client blows chunks if it can't connect to server

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#428] opened 2016-10-20 15:03 UTC
It would be better to just quietly log something. I think this used to be the case in Brixton.

**Comment by adriancole** [comment] 2016-10-24 02:26
by blow chunks, you mean uncaught exceptions dump and end up in the server log, I'm guessing?

**Comment by dsyer** [comment] 2016-10-24 06:06
It was even worse than that. All HTTP responses were changed (can't remember if it was all 500 or all empty 200).

**Comment by dsyer** [comment] 2016-10-24 06:07
No, wait. It's not that issue. The problem manifests as an app that won't start. Not good.

**Comment by adriancole** [comment] 2016-10-24 06:50
I just verified this again with latest sleuth, just to make sure. Can you please paste a stack trace with the failure you've seen as I can't reproduce it?

ex this example runs fine with zipkin down, and later when I bring zipkin up, it sends traces to it

https://github.com/openzipkin/sleuth-webmvc-example

The only thing I can think of is if somehow, flush is being called explicitly (when it certainly shouldn't) https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin/HttpZipkinSpanReporter.java#L53

**Comment by dsyer** [comment] 2016-10-24 08:59
We'd better ask @joshlong (I was just reporting a problem he had). We run his apps in our CI process and they work as well, so it's strange indeed.

**Comment by adriancole** [comment] 2016-10-25 19:00
the sender occurs on a separate thread, so if this is the case, then
something quite odd is happening. I routinely start sleuth before Zipkin in
demos (usually by accident)

**Comment by marcingrzejszczak** [comment] 2016-10-27 11:46
More info from @joshlong:

> If u create a client and add spring cloud starter zipkin and don't have a Zipkin server running then the logs get overrun with exceptions and the logging of trace / span info doesn't work

**Comment by marcingrzejszczak** [comment] 2016-10-28 09:25
@joshlong I've started an app with `Camden.BUILD-SNAPSHOT` and I have no Zipkin running. Everything works fine. I tried both with HTTP and via RabbitMQ. I think you'll have to show us a sample.

The only case when I'm flooded with logs (but the app starts fine) is when I'm not running RabbitMQ and Zipkin. Then I have AmqpConnectionExceptions which makes sense

**Comment by marcingrzejszczak** [comment] 2016-11-17 11:53
I'm closing this cause I haven't seen anything wrong here

**Closed by marcingrzejszczak** 2016-11-17 11:53 UTC
Labels: waiting for feedback
