### ISSUE TITLE
1.3.2  trace id conflict problem 

### ISSUE THREAD

**Issue by Jaware** [spring-cloud/spring-cloud-sleuth#936] opened 2018-04-12 04:46 UTC
most of the times,the id is ok,but sometimes  we can find conflict ids. 

    @Bean
	@ConditionalOnMissingBean
	public Random randomForSpanIds() {
		return new Random();
	}

i doubt that Random can be unique in distributed areas.

**Comment by Jaware** [comment] 2018-04-12 07:16
it is random,i do not know the details.but i am sure the random can not guarantee unique id in distributed areas.Maybe our apps' tps is  so large.maybe i shoud use zipkin v2 span,which traceId is string ,and i can use UUID to guarantee unique id

**Comment by adriancole** [comment] 2018-04-12 07:32
You can consider using the spring.sleuth.traceId128=true property


FYI Twitter still uses 64-bit trace ID by default, but likely they will
move to 128-bit trace IDs. I don't think you will have a problem in
practice and if you do why would be an interesting question.

**Comment by marcingrzejszczak** [comment] 2018-04-12 08:33
I'll close this issue until you get a sample that can reproduce an issue. Until then i don't see an issue here

**Closed by marcingrzejszczak** 2018-04-12 08:33 UTC

**Comment by Jaware** [comment] 2018-04-12 09:53
can Random really  guarantee unique id in distributed envs? @adriancole  traceId128 can not be spanid accoring the DefaultTracer

**Comment by adriancole** [comment] 2018-04-12 10:04
a trace ID is unique per operation.

So if your concern is about span ID, you believe there's a reasonable
chance of collision within the same operation.
If your random generator is working, I don't think most use cases this will
be a problem. This approach is used at large scale sites including google.

Issues lists aren't for hypothetical problems, rather for changes need to
the code. I hope some of the context helps, but this isn't a good place to
explore nuance of random generators.

**Comment by Jaware** [comment] 2018-04-13 03:54
maybe because of our methods tracing,the span counts are too large,so i think i have to use other techs like UUID to guarantee distributed unique ID

**Comment by adriancole** [comment] 2018-04-13 03:58
Sometimes when there is conflict it isnt because of random, rather a
propagation bug somewhere. For example a span id reused by accident due to
thread local problem. Could this be possible?

**Comment by marcingrzejszczak** [comment] 2018-04-18 07:41
If you have custom code please ensure that you're not leaving any spans unclosed. If you can't provide an example we can replicate the problem with then i don't think we'll be able to help you

**Comment by Jaware** [comment] 2018-04-18 10:13
the example is above, i close the span in finally block,i can not see any error in my  code above.

**Comment by marcingrzejszczak** [comment] 2018-04-18 10:14
No, above you have some snippet. I have no idea what it really does. AOP - AOP around what? What does `tracer()` do? What is `CommonUtil`?  This snippet doesn't help solve the problem at all. Please upload a sample of the whole project.

**Comment by Jaware** [comment] 2018-04-18 11:36
i think i have found the problem.
SpanContextHolder.java
static void close(SpanFunction spanFunction) {
		SpanContext current = CURRENT_SPAN.get();
		CURRENT_SPAN.remove();
		while (current != null) {
			current = current.parent;
			spanFunction.apply(current != null ? current.span : null);
			if (current != null) {
				if (!current.autoClose) {
					**CURRENT_SPAN.set(current);**
					current = null;
				}
			}
		}
	}

**Comment by Jaware** [comment] 2018-04-18 11:37
i use the close function,may be i shoud use detach

**Comment by marcingrzejszczak** [comment] 2018-04-18 11:51
I have no idea what you're doing. Also when you paste the code, please format it cause it's difficult to read.

**Comment by Jaware** [comment] 2018-04-19 02:33
sorry ,i have formatted them,by the way i mean maybe it is a sleuth's bug ,when using tracer's close function ,if current span have parent that is not autoClose,then CURRENT_SPAN become the parent.

**Comment by Jaware** [comment] 2018-04-20 11:49
our code is ok,we have found some span ids are same,so we will  use es id(we use es to store spans) to replace the random.the parent id is because our validating function had a bug and it droped some spans
