### ISSUE TITLE
HibernateJpaConfiguration constructions fails: Bean named 'transactionManager' is expected to be of type 'org.springframework.transaction.jta.JtaTransactionManager' but was actually of type 'org.springframework.cloud.sleuth.instrument.tx.TracePlatformTransactionManager'

### ISSUE THREAD

**Issue by thomasvich** [spring-cloud/spring-cloud-sleuth#2114] opened 2022-02-14 17:18 UTC
Hi, i am having issue with Sleuth changing my transactionalManager bean to a wrapped object which does not match originally requested type. I found this while working on SpringBoot upgrade 2.5.8 -> 2.6.2 (JBoss SPI removed) which forced me to review how and which transactionManager am i using.

In my case I am trying to fetch TransactionalManager via JNDI from JBoss and to prevent Spring from booting one via during hibernate autoconfiguration (Conditional on missing bean) i am running my configuration before HibernateJpaAutoConfiguration.

**HibernateJpaConfiguration construction** requests **ObjectProvider of JtaTransactionManager**
so in my configuration i wrap javax.transaction.TransactionManager jbossTm as *new JtaTransactionalManager*(jbossTm).
But then it goes wrong as **the JtaTransactionManager bean is gets wrapped by class TracePlatformTransactionManager.**
So **ObjectProvider of JtaTransactionManager then tries to provide the TracePlatformTransactionManager** which fails on not being JtaTransactionManager

The issue happens with custom definition of any JtaTransactionManager bean creating "valid enough" transaction manager before HibernateJpaAutoConfiguration kicks in.

I would say its similar issue as:
https://github.com/spring-projects/spring-boot/issues/29151
https://github.com/spring-cloud/spring-cloud-sleuth/issues/2100

Logs - spring boot start-up
```
2022-02-14 17:25:00,906 ERROR [][,][] [org.springframework.boot.SpringApplication] (ServerService Thread Pool -- 184) Application run failed: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'transactionManager' is expected to be of type 'org.springframework.transaction.jta.JtaTransactionManager' but was actually of type 'org.springframework.cloud.sleuth.instrument.tx.TracePlatformTransactionManager'
        at deployment.test-app.war//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
        at deployment.test-app.war//org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at deployment.test-app.war//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at deployment.test-app.war//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:410)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at deployment.test-app.war//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at deployment.test-app.war//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at deployment.test-app.war//org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
        at deployment.test-app.war//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
        at deployment.test-app.war//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at deployment.test-app.war//org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at deployment.test-app.war//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
        at deployment.test-app.war//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
        at deployment.test-app.war//org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at deployment.test-app.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
        at deployment.test-app.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
        at deployment.test-app.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
        at deployment.test-app.war//org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
        --- JBoss - Undertow deployment log lines removed ---
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'transactionManager' is expected to be of type 'org.springframework.transaction.jta.JtaTransactionManager' but was actually of type 'org.springframework.cloud.sleuth.instrument.tx.TracePlatformTransactionManager'
        at deployment.test-app.war//org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
        at deployment.test-app.war//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
        at deployment.test-app.war//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
        ... 50 more
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'transactionManager' is expected to be of type 'org.springframework.transaction.jta.JtaTransactionManager' but was actually of type 'org.springframework.cloud.sleuth.instrument.tx.TracePlatformTransactionManager'
        at deployment.test-app.war//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1399)
        at deployment.test-app.war//org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:2030)
        at deployment.test-app.war//org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.<init>(JpaBaseConfiguration.java:90)
        at deployment.test-app.war//org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.<init>(HibernateJpaConfiguration.java:96)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at deployment.test-app.war//org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
        ... 52 more
```

**Dependencies**
```
BOM spring-boot-dependencies 2.6.3
BOM spring-cloud-dependencies 2021.0.0
spring-boot
spring-boot-autoconfigure
spring-cloud-starter-sleuth
spring-boot-starter-data-jpa
```

Properties
`spring.datasource.jndi-name=java:jboss/jdbc/SomeDataSource`
-> so DataSourceAutoConfiguration and HibernateJpaAutoConfiguration kicks in

Configuration class to define custom JTA TM
```
@Configuration
@AutoConfigureBefore( value = { DataSourceAutoConfiguration.class, HibernateJpaAutoConfiguration.class } )
@EnableTransactionManagement
public class MyTransactionManagerAutoConfiguration {

    @Bean
    public JtaTransactionManager transactionManager() {
 // Get some JtaTransactionManager - I am getting one from JBoss via JNDI
    }

}
```

Thx for possibly solving this.

**Comment by marcingrzejszczak** [comment] 2022-02-14 17:34
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/2067

**Comment by thomasvich** [comment] 2022-02-21 10:59
Hi.
With Spring Cloud 2021.0.1 this problem is not fixed.

Just instead of 
`Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'transactionManager' is expected to be of type 'org.springframework.transaction.jta.JtaTransactionManager' but was actually of type 'org.springframework.cloud.sleuth.instrument.tx.TracePlatformTransactionManager'`
i get
`Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'jtaTransactionManager' is expected to be of type 'org.springframework.transaction.jta.JtaTransactionManager' but was actually of type 'com.sun.proxy.$Proxy842'`

**Comment by marcingrzejszczak** [comment] 2022-02-21 11:09
Thanks for the report. It would be much better to leverage snapshots to check if things got fixed rather than check a GA version and only then check if things got improved. Can you please create a simple sample that replicates this problem so that w can try to fix it?

**Comment by bvtk** [comment] 2022-02-24 08:31
We have the same Problem with a custom Datasource:

`Bean named 'readOnlyDataSource' is expected to be of type 'de.otto.cam.d2po.commons.jdbc.ReadOnlyDataSource' but was actually of type 'org.springframework.cloud.sleuth.instrument.jdbc.DataSourceWrapper'`

But if we disable Spring Sleuth for JDBC  `spring.sleuth.jdbc.enabled: false`

we get following Error: 

`Bean named 'readOnlyDataSource' is expected to be of type 'de.otto.cam.d2po.commons.jdbc.ReadOnlyDataSource' but was actually of type 'com.github.gavlyukovskiy.boot.jdbc.decorator.DecoratedDataSource'`

We are migration from Spring Boot 2.5.8 to 2.6.3. It seems to be the same issue that @thomasvich has with his TransactionManager

**Comment by marcingrzejszczak** [comment] 2022-02-24 08:34
Can someone please create a small sample that replicates this issue? It seems that you have Arthur's dependency (https://github.com/gavlyukovskiy/spring-boot-data-source-decorator) on the classpath too so you would have to disable it too.

**Comment by bvtk** [comment] 2022-02-24 13:57
After Removing all Dependencies from com.vladmihalcea.flexy-pool and com.github.gavlyukovskiy. But disabling / removing features / dependencies was only for analyzing purposes. We decided to get rid of our custom DataSource as solution.

**Comment by marcingrzejszczak** [comment] 2022-02-24 14:00
So I don't understand - is there any problem still or not?

**Comment by bvtk** [comment] 2022-02-28 07:17
Meanwhile, i don't think it is a bug. I think it is a diffent behavior copared to older Spring Sleuth Versions. For example we had the same Problem with our KafkaProducer Bean and Spring Sleuth.

This is from the Spring Sleuth Dokumentation:

'We decorate the Kafka clients (KafkaProducer and KafkaConsumer) to create a span for each event that is produced or consumed. You can disable this feature by setting the value of spring.sleuth.kafka.enabled to false.

You have to register the Producer or Consumer as beans in order for Sleuth’s auto-configuration to decorate them. When you then inject the beans, the expected type must be Producer or Consumer (and NOT e.g. KafkaProducer).'

**Comment by marcingrzejszczak** [comment] 2022-02-28 10:16
Ok I will close this issue until someone creates a reproducer. I will then reopen it.

**Comment by oburgosm** [comment] 2022-03-17 08:35
I have created a project that reproduce the same problem [here](https://github.com/oburgosm/sleuth-jta).

It has SB 2.6.4, Spring cloud 2021.0.1, spring data JPA and Atomikos as JtaTransactionManager.

If I set property `spring.sleuth.tx.enabled`  to _false_, the test in this application pass, but if I set it to _true_, the test fails loading context.

**Closed** 2022-04-13 10:09 UTC
Labels: bug

**Comment by marcingrzejszczak** [comment] 2022-04-13 10:10
The problem is that `AbstractPlatformTransactionManager` implements the `PlatformTransactionManager` interface however it makes all its methods final. That's why we're creating a JDK proxy that breaks everything :shrug: . So we've decided to NOT instrument those classes that extend the abstract class. It's better for the app to start and not instrument transactions then to break.
