### ISSUE TITLE
Spring cloud sleuth on PWS

### ISSUE THREAD

**Issue by Pirolf** [spring-cloud/spring-cloud-sleuth#468] opened 2016-12-09 23:27 UTC
Hello! @jadekler and I are trying out spring cloud sleuth on PWS and seeing some weirdness.

**Setup**
We have a simple spring app from https://start.spring.io which has `org.springframework.cloud:spring-cloud-starter-sleuth:1.1.0.RELEASE` and `springBootVersion = '1.4.2.RELEASE'`. We are running locally on a mac and remotely on PWS.

**Local experience**
With 2 instances of this same app (one talking to the other): when we curl the one (which sends a GET to the other), we see the downstream app have `X-B3-ParentSpanId` header (`899fd4c751edd354`) which corresponds to the upstream app's spanId (in the logs of the upstream app we see `INFO [tracer,2f7904aef2670061,899fd4c751edd354,false]`.

This matches what we expect - downstream parentSpanId == upstream spanId.

**PWS Experience**
With 2 instances of the app (one talking to the other): when we curl the one, we see downstream app have a totally random `X-B3-ParentSpanId` which does not exist in the upstream app logs. This neither matches our expectations nor what we see locally.

We suspect either gorouter problems or spring config problems.

**Comment by Pirolf** [comment] 2016-12-09 23:35
**Update**
We've added an interceptor to `RestTemplate`:

```
@Override
public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException {
    log.info("SENDING with headers:");
    request.getHeaders().entrySet().stream()
        .map(s -> s.getKey() + " : " + s.getValue())
        .forEach(log::info);

    ClientHttpResponse response = execution.execute(request, body);

    log.info("SENT");
    return response;
}
```

With this in place, we get more interesting results:

**Locally**

Everything is kosher EXCEPT we randomly get a new 'spanId' (`6097146db33364b0`) just after `ClientHttpResponse response = execution.execute(request, body);`. It never occurs again in the upstream app, BUT it is the spanId of the downstream app (why would the upstream app know about the downstream app's spanId??)

```
2016-12-09 15:14:41.917  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.SomeController               : 1 ENDPOINT
2016-12-09 15:14:41.917  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.SomeController               : traceId: null
2016-12-09 15:14:41.917  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.SomeController               : spanId: null
2016-12-09 15:14:41.918  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.SomeController               : parentSpanId: null
2016-12-09 15:14:41.918  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.SomeController               : sending request to http://localhost:8081/item-info
2016-12-09 15:14:41.932  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.LoggingInterceptHandler      : SENDING with headers:
2016-12-09 15:14:41.936  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.LoggingInterceptHandler      : Accept : [text/plain, application/json, application/*+json, */*]
2016-12-09 15:14:41.936  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.LoggingInterceptHandler      : Content-Length : [0]
2016-12-09 15:14:41.951  INFO [tracer,2f7904aef2670061,6097146db33364b0,false] 33934 --- [nio-8080-exec-1] com.metrics.LoggingInterceptHandler      : SENT
2016-12-09 15:14:41.954  INFO [tracer,2f7904aef2670061,899fd4c751edd354,false] 33934 --- [nio-8080-exec-1] com.metrics.SomeController               : sent request
```

**On PWS**

On PWS this additional logging reveals that the mystery downstream `parentSpanId` is in fact the anomalous `spanId` from the `SENT!` line right after `ClientHttpResponse response = execution.execute(request, body);`. This behavior is quite inconsistent with local behavior; notably that the downstream `spanId` is not seen anywhere in the upstream logs (which we expect!)

**Conclusion**

- Right after `RestTemplate` executes the request, it appears as though a new spanId is created and used in logs
- This spanId is not used in execution beyond the interceptor (even in the same thread)
- Locally, this spanId becomes the spanId of the downstream app (which is weird to us) and the other - 'normal' - spanId in the request becomes the parentSpanId of the downstream app (which seems correct)
- On PWS, the anomalous spanId - NOT the spanId of all the previous logs in this flow - becomes the parentSpanId of the downstream app (which is weird to us) and the downstream app generates its own spanId (which seems correct)

**Comment by Pirolf** [comment] 2016-12-09 23:36
@marcingrzejszczak @dsyer

**Comment by Pirolf** [comment] 2016-12-09 23:36
Additional note: we are also experimenting with a very simple node app that manually injects these headers itself. Everything seems to be working just as we would expect, which leads us to believe this is not a gorouter problem.

**Comment by dsyer** [comment] 2016-12-10 07:14
As far as I can tell the brewery is working in PWS (docs have a link to the running app), but I did notice something weird in the /trace endpoints: the x-b3-spanid and x-b3-traceid headers are duplicated (seems like that's probably a gorouter artifact?):

```
...
"x-b3-parentspanid": "056cf769eed72055",
"x-b3-sampled": [
"1",
"1"
],
"x-b3-spanid": "0df77eb55eefdb26",
"x-b3-traceid": [
"e17ecd285f2e2a74",
"e17ecd285f2e2a74"
],
...
```

**Comment by marcingrzejszczak** [comment] 2016-12-10 08:33
I'm still away from my laptop so can't debug this thoroughly but if what Dave days is true and I assume it is then in the Sleuth side are most likely throwing an exception cause we can't deserialize the header and we're generating a new id

**Comment by dsyer** [comment] 2016-12-10 10:51
Maybe. Note also that this

> downstream receives a X-B3-SpanId that has never occurred in upstream logs

is normal for PWS (the router starts a new span,  so it would never be seen in application logs upstream). So I'm not even sure what the problem is, as long as the traceid is preserved.

**Comment by dsyer** [comment] 2016-12-10 22:48
Here's a set of more complete logs from a simple sample that calls itself (the home page "/" calls back to "/hi"):

```
2016-12-10T22:37:44.93+0000 [APP/PROC/WEB/0]OUT 2016-12-10 22:37:44.931  INFO [sleuthSample,d46657c3fc2fb08b,84f6d2ae51051116,true] 13 --- [nio-8080-exec-3] demo.HiController                        : Hi
2016-12-10T22:37:44.87+0000 [APP/PROC/WEB/0]OUT 2016-12-10 22:37:44.871  INFO [sleuthSample,d46657c3fc2fb08b,3ad9a93065573113,true] 13 --- [nio-8080-exec-2] demo.HomeController                      : Home
2016-12-10T22:37:44.94+0000 [RTR/2]      OUT sleuthy.cfapps.io - [10/12/2016:22:37:44.921 +0000] "GET /hi HTTP/1.1" 200 0 2 "-" "Java/1.8.0_111" "10.10.2.26:14539" "10.10.147.127:61514" x_forwarded_for:"54.157.53.91" x_forwarded_proto:"http" vcap_request_id:"7c30a892-06cc-47a6-76d8-fc80390b3c30" response_time:0.026361218 app_id:"a498dc22-f9e5-4ad3-83dc-f5971c1a2426" app_index:"0" x_b3_traceid:"d46657c3fc2fb08b" x_b3_spanid:"e4d805fafde53674" x_b3_parentspanid:"b3eb94b8cfafd399"
2016-12-10T22:37:44.96+0000 [RTR/4]      OUT sleuthy.cfapps.io - [10/12/2016:22:37:44.647 +0000] "GET / HTTP/1.1" 200 0 5 "-" "curl/7.47.0" "10.10.2.26:60440" "10.10.147.127:61514" x_forwarded_for:"82.7.92.18" x_forwarded_proto:"http" vcap_request_id:"8f59de60-359e-4676-58c8-8af10221a743" response_time:0.319250809 app_id:"a498dc22-f9e5-4ad3-83dc-f5971c1a2426" app_index:"0" x_b3_traceid:"d46657c3fc2fb08b" x_b3_spanid:"d46657c3fc2fb08b" x_b3_parentspanid:"-"
```

You can see from the RTR logs that the incoming request to "/" has a traceid (and spanid) generated by the router. You can also see that the downstream request to "/hi" has the same traceid (so that's good) and also a parentspanid that we don't see anywhere else. I guess we need to explain that, or at least work out how to fill in the gaps in the logs.

The logs are from the "sleuth" sample at spring-cloud-samples/tests (and deployed at http://sleuthy.cfapps.io).

**Comment by dsyer** [comment] 2016-12-11 09:15
```
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.139 DEBUG [sleuthSample,8c6613e39aa3365c,d32b5e979c2d03ad,true] 13 --- [nio-8080-exec-2] o.s.c.s.i.web.TraceHandlerInterceptor    : Created new span [Trace: 8c6613e39aa3365c, Span: d32b5e979c2d03ad, Parent: 8c6613e39aa3365c, exportable:true] with name [home]
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.139 DEBUG [sleuthSample,8c6613e39aa3365c,d32b5e979c2d03ad,true] 13 --- [nio-8080-exec-2] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a method tag with value [home] to a span [Trace: 8c6613e39aa3365c, Span: d32b5e979c2d03ad, Parent: 8c6613e39aa3365c, exportable:true]
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.139 DEBUG [sleuthSample,8c6613e39aa3365c,d32b5e979c2d03ad,true] 13 --- [nio-8080-exec-2] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a class tag with value [HomeController] to a span [Trace: 8c6613e39aa3365c, Span: d32b5e979c2d03ad, Parent: 8c6613e39aa3365c, exportable:true]
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.140  INFO [sleuthSample,8c6613e39aa3365c,d32b5e979c2d03ad,true] 13 --- [nio-8080-exec-2] demo.HomeController                      : Home
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.140 DEBUG [sleuthSample,8c6613e39aa3365c,d32b5e979c2d03ad,true] 13 --- [nio-8080-exec-2] o.s.web.client.RestTemplate              : Created GET request for "http://sleuthy.cfapps.io/hi"
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.140 DEBUG [sleuthSample,8c6613e39aa3365c,d32b5e979c2d03ad,true] 13 --- [nio-8080-exec-2] o.s.web.client.RestTemplate              : Setting request Accept header to [text/plain, application/json, application/*+json, */*]
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.140 DEBUG [sleuthSample,8c6613e39aa3365c,5eb7f3d6d7cd1da9,true] 13 --- [nio-8080-exec-2] .w.c.AbstractTraceHttpRequestInterceptor : Starting new client span [[Trace: 8c6613e39aa3365c, Span: 5eb7f3d6d7cd1da9, Parent: d32b5e979c2d03ad, exportable:true]]
```

That's the upstream app creating the extra spans

`8c6613e39aa3365c` is the one from the incoming request (the gorouter added it)

`TraceHandlerInterceptor` creates another new one `d32b5e979c2d03ad` (why?) and `AbstractTraceHttpRequestInterceptor` creates another (for the downstream HTTP call) `5eb7f3d6d7cd1da9`

Downstream you see `5eb7f3d6d7cd1da9` as the parent and yet another new span (created by the gorouter I guess):

 ```
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.146 DEBUG [sleuthSample,8c6613e39aa3365c,5eb7f3d6d7cd1da9,true] 13 --- [nio-8080-exec-2] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@526f307e10 pairs: {GET /hi HTTP/1.1: null}{Accept: text/plain, application/json, application/*+json, */*}{X-B3-TraceId: 8c6613e39aa3365c}{X-B3-SpanId: 5eb7f3d6d7cd1da9}{X-B3-Sampled: 1}{X-Span-Name: http:/hi}{X-B3-ParentSpanId: d32b5e979c2d03ad}{User-Agent: Java/1.8.0_111}{Host: sleuthy.cfapps.io}{Connection: keep-alive}
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.148 DEBUG [sleuthSample,,,] 13 --- [8080-Acceptor-0] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8080-Acceptor-0] latch=2
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT 2016-12-11 09:01:34.148 DEBUG [sleuthSample,,,] 13 --- [nio-8080-exec-4] o.a.coyote.http11.Http11InputBuffer      : Received [GET /hi HTTP/1.1
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT Host: sleuthy.cfapps.io
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT User-Agent: Java/1.8.0_111
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT Accept: text/plain, application/json, application/*+json, */*
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-B3-Parentspanid: 5eb7f3d6d7cd1da9
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-B3-Sampled: 1
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-B3-Spanid: 6e97e1ffea683c88
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-B3-Traceid: 8c6613e39aa3365c
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Cf-Applicationid: a498dc22-f9e5-4ad3-83dc-f5971c1a2426
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Cf-Instanceid: c1eca56b-7fde-4e76-565f-46c5bf4a2928
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Forwarded-For: 54.157.53.91, 10.10.66.143
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Forwarded-Port: 80
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Forwarded-Proto: http
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Request-Start: 1481446894147
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Span-Name: http:/hi
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT X-Vcap-Request-Id: d4f1e008-37e3-426f-73a3-2f1224eab228
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT Connection: close
2016-12-11T09:01:34.14+0000 [APP/PROC/WEB/0]OUT ]
```

`6e97e1ffea683c88` is new

What would we want the gorouter to do? Seems like it's adding more than maybe we want it to do?

Should proxies by visible in a span? If so then they would need to add logs etc. to them, so that the cs/cr, sr/ss records match up. My guess is that's too much logic for a router and we need to rethink what it is doing.

**Comment by dsyer** [comment] 2016-12-12 14:16
Here's a log from that app in PWS:

```
2016-12-12T13:53:08.92+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:08.920  INFO [sleuthSample,,,] 13 --- [nio-8080-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2016-12-12T13:53:08.92+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:08.920  INFO [sleuthSample,,,] 13 --- [nio-8080-exec-3] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2016-12-12T13:53:09.01+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.009  INFO [sleuthSample,,,] 13 --- [nio-8080-exec-3] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 89 ms
2016-12-12T13:53:09.04+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.047 DEBUG [sleuthSample,,,] 13 --- [nio-8080-exec-3] o.s.c.sleuth.instrument.web.TraceFilter  : Received a request to uri [/] that should not be sampled [false]
2016-12-12T13:53:09.06+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.059 DEBUG [sleuthSample,,,] 13 --- [nio-8080-exec-3] o.s.c.sleuth.instrument.web.TraceFilter  : Found a parent span [Trace: 1619badb32569fdb, Span: 1619badb32569fdb, Parent: null, exportable:true] in the request
2016-12-12T13:53:09.06+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.063 DEBUG [sleuthSample,1619badb32569fdb,1619badb32569fdb,true] 13 --- [nio-8080-exec-3] o.s.c.sleuth.instrument.web.TraceFilter  : Parent span is [Trace: 1619badb32569fdb, Span: 1619badb32569fdb, Parent: null, exportable:true]
2016-12-12T13:53:09.10+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.100 DEBUG [sleuthSample,1619badb32569fdb,c24ddc35857187d4,true] 13 --- [nio-8080-exec-3] o.s.c.s.i.web.TraceHandlerInterceptor    : Created new span [Trace: 1619badb32569fdb, Span: c24ddc35857187d4, Parent: 1619badb32569fdb, exportable:true] with name [home]
2016-12-12T13:53:09.10+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.101 DEBUG [sleuthSample,1619badb32569fdb,c24ddc35857187d4,true] 13 --- [nio-8080-exec-3] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a method tag with value [home] to a span [Trace: 1619badb32569fdb, Span: c24ddc35857187d4, Parent: 1619badb32569fdb, exportable:true]
2016-12-12T13:53:09.10+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.106 DEBUG [sleuthSample,1619badb32569fdb,c24ddc35857187d4,true] 13 --- [nio-8080-exec-3] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a class tag with value [HomeController] to a span [Trace: 1619badb32569fdb, Span: c24ddc35857187d4, Parent: 1619badb32569fdb, exportable:true]
2016-12-12T13:53:09.12+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.120  INFO [sleuthSample,1619badb32569fdb,c24ddc35857187d4,true] 13 --- [nio-8080-exec-3] demo.HomeController                      : Home
2016-12-12T13:53:09.16+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.167 DEBUG [sleuthSample,1619badb32569fdb,7bbe713495b7c8b4,true] 13 --- [nio-8080-exec-3] .w.c.AbstractTraceHttpRequestInterceptor : Starting new client span [[Trace: 1619badb32569fdb, Span: 7bbe713495b7c8b4, Parent: c24ddc35857187d4, exportable:true]]
2016-12-12T13:53:09.20+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.200 DEBUG [sleuthSample,,,] 13 --- [nio-8080-exec-4] o.s.c.sleuth.instrument.web.TraceFilter  : Found a parent span [Trace: 1619badb32569fdb, Span: 731cf0c35f3af4c2, Parent: 7bbe713495b7c8b4, exportable:true] in the request
2016-12-12T13:53:09.20+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.206 DEBUG [sleuthSample,1619badb32569fdb,731cf0c35f3af4c2,true] 13 --- [nio-8080-exec-4] o.s.c.sleuth.instrument.web.TraceFilter  : Parent span is [Trace: 1619badb32569fdb, Span: 731cf0c35f3af4c2, Parent: 7bbe713495b7c8b4, exportable:true]
2016-12-12T13:53:09.24+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.248 DEBUG [sleuthSample,1619badb32569fdb,b1109d60ddaf33d5,true] 13 --- [nio-8080-exec-4] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a method tag with value [hi] to a span [Trace: 1619badb32569fdb, Span: b1109d60ddaf33d5, Parent: 731cf0c35f3af4c2, exportable:true]
2016-12-12T13:53:09.20+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.198 DEBUG [sleuthSample,,,] 13 --- [nio-8080-exec-4] o.s.c.sleuth.instrument.web.TraceFilter  : Received a request to uri [/hi] that should not be sampled [false]
2016-12-12T13:53:09.24+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.248 DEBUG [sleuthSample,1619badb32569fdb,b1109d60ddaf33d5,true] 13 --- [nio-8080-exec-4] o.s.c.s.i.web.TraceHandlerInterceptor    : Created new span [Trace: 1619badb32569fdb, Span: b1109d60ddaf33d5, Parent: 731cf0c35f3af4c2, exportable:true] with name [hi]
2016-12-12T13:53:09.25+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.250  INFO [sleuthSample,1619badb32569fdb,b1109d60ddaf33d5,true] 13 --- [nio-8080-exec-4] demo.HiController                        : Hi
2016-12-12T13:53:09.25+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.249 DEBUG [sleuthSample,1619badb32569fdb,b1109d60ddaf33d5,true] 13 --- [nio-8080-exec-4] o.s.c.s.i.web.TraceHandlerInterceptor    : Adding a class tag with value [HiController] to a span [Trace: 1619badb32569fdb, Span: b1109d60ddaf33d5, Parent: 731cf0c35f3af4c2, exportable:true]
2016-12-12T13:53:09.29+0000 [RTR/5]      OUT sleuthy.cfapps.io - [12/12/2016:13:53:09.196 +0000] "GET /hi HTTP/1.1" 200 0 2 "-" "Java/1.8.0_111" "10.10.2.227:5719" "10.10.155.26:62369" x_forwarded_for:"54.88.46.179" x_forwarded_proto:"http" vcap_request_id:"15882c53-9b1c-4522-5c90-60e92afb61da" response_time:0.099423976 app_id:"a498dc22-f9e5-4ad3-83dc-f5971c1a2426" app_index:"0" x_b3_traceid:"1619badb32569fdb" x_b3_spanid:"731cf0c35f3af4c2" x_b3_parentspanid:"7bbe713495b7c8b4"
2016-12-12T13:53:09.32+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.322 DEBUG [sleuthSample,1619badb32569fdb,1619badb32569fdb,true] 13 --- [nio-8080-exec-3] o.s.c.sleuth.instrument.web.TraceFilter  : Closing the span [Trace: 1619badb32569fdb, Span: 1619badb32569fdb, Parent: null, exportable:true] since the response was successful
2016-12-12T13:53:09.32+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.322 DEBUG [sleuthSample,1619badb32569fdb,1619badb32569fdb,true] 13 --- [nio-8080-exec-3] o.s.c.sleuth.instrument.web.TraceFilter  : Trying to send the parent span [Trace: 1619badb32569fdb, Span: 1619badb32569fdb, Parent: null, exportable:true] to Zipkin
2016-12-12T13:53:09.29+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.296 DEBUG [sleuthSample,1619badb32569fdb,b1109d60ddaf33d5,true] 13 --- [nio-8080-exec-4] o.s.c.s.i.web.TraceHandlerInterceptor    : Closing span [Trace: 1619badb32569fdb, Span: b1109d60ddaf33d5, Parent: 731cf0c35f3af4c2, exportable:true]
2016-12-12T13:53:09.30+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.307 DEBUG [sleuthSample,1619badb32569fdb,731cf0c35f3af4c2,true] 13 --- [nio-8080-exec-4] o.s.c.sleuth.instrument.web.TraceFilter  : Trying to send the parent span [Trace: 1619badb32569fdb, Span: 731cf0c35f3af4c2, Parent: 7bbe713495b7c8b4, exportable:true] to Zipkin
2016-12-12T13:53:09.30+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.309 DEBUG [sleuthSample,1619badb32569fdb,731cf0c35f3af4c2,true] 13 --- [nio-8080-exec-4] o.s.c.sleuth.instrument.web.TraceFilter  : Closing the span [Trace: 1619badb32569fdb, Span: 731cf0c35f3af4c2, Parent: 7bbe713495b7c8b4, exportable:true] since the response was successful
2016-12-12T13:53:09.32+0000 [APP/PROC/WEB/0]OUT 2016-12-12 13:53:09.321 DEBUG [sleuthSample,1619badb32569fdb,c24ddc35857187d4,true] 13 --- [nio-8080-exec-3] o.s.c.s.i.web.TraceHandlerInterceptor    : Closing span [Trace: 1619badb32569fdb, Span: c24ddc35857187d4, Parent: 1619badb32569fdb, exportable:true]
2016-12-12T13:53:09.31+0000 [RTR/3]      OUT sleuthy.cfapps.io - [12/12/2016:13:53:08.876 +0000] "GET / HTTP/1.1" 200 0 5 "-" "curl/7.47.0" "10.10.66.170:24308" "10.10.155.26:62369" x_forwarded_for:"82.7.92.18" x_forwarded_proto:"http" vcap_request_id:"7eb88cee-3ebf-48cd-4348-5449f68f2123" response_time:0.443192554 app_id:"a498dc22-f9e5-4ad3-83dc-f5971c1a2426" app_index:"0" x_b3_traceid:"1619badb32569fdb" x_b3_spanid:"1619badb32569fdb" x_b3_parentspanid:"-"
```

There are 5 spans, and only 4 locally (should be 2 IMO, but that's a different problem):

1 - 1619badb32569fdb - incoming from request
2- c24ddc35857187d4 - new span for the Controller (Interceptor)
3 - 7bbe713495b7c8b4 - rest template client
4 - 731cf0c35f3af4c2 - have no idea what this is. It’s parent is `7bbe713495b7c8b4`
5 - b1109d60ddaf33d5 - new span for the Controller (interceptor)

That looks good apart from `731cf0c35f3af4c2`. Trace filter sees that `731cf0c35f3af4c2` came with the request

**Comment by dsyer** [comment] 2016-12-12 14:35
You can test it by sending in a traceid and spanid and seeing the logs from the router

```
$ curl sleuthy.cfapps.io/hi -H "X-B3-TraceId: 6e97e1ffea683c88" -H "X-B3-SpanId: 6e97e1ffea683c88"
```

```
2016-12-12T14:31:45.41+0000 [RTR/0]      OUT sleuthy.cfapps.io - [12/12/2016:14:31:45.395 +0000] "GET /hi HTTP/1.1" 200 0 2 "-" "curl/7.47.0" "10.10.2.227:52070" "10.10.155.26:62369" x_forwarded_for:"82.7.92.18" x_forwarded_proto:"http" vcap_request_id:"57d9eda2-ce8a-40e3-52f8-a3e54e502832" response_time:0.014604874 app_id:"a498dc22-f9e5-4ad3-83dc-f5971c1a2426" app_index:"0" x_b3_traceid:"6e97e1ffea683c88" x_b3_spanid:"e937b5630338a6ff" x_b3_parentspanid:"6e97e1ffea683c88"
```

And the `TraceFilter` reports `e937b5630338a6ff` as the current span (of course). But that one has appeared out of thin air. The only place it could have come from is the router.

**Comment by dsyer** [comment] 2016-12-12 14:49
See: https://github.com/cloudfoundry/gorouter/issues/157

**Comment by jadekler** [comment] 2016-12-12 16:55
Fantastic - thanks @dsyer

**Comment by marcingrzejszczak** [comment] 2016-12-20 17:26
So I assume that we can close this?

**Comment by Pirolf** [comment] 2016-12-20 19:42
@marcingrzejszczak yes, thanks!

**Closed** 2016-12-20 19:42 UTC
Labels: waiting for feedback
