### ISSUE TITLE
gRPC context not propaged

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-sleuth#1749] opened 2020-10-02 02:52 UTC
I've this application with a gRPC server (A) that calls a gRPC client (B) that calls an external gRPC service. It all starts with a `ServerInterceptor` injecting a user id in the `Context` that is required by the service `A`; since `A` doesn't have access to the headers, context is the only way to propagate metadata from the client.
The `ServerInterceptor` ends with:
```
return Contexts.interceptCall(ctx.withValue(AppGlobal.USER_ID_CONTEXT_KEY, userId), call, headers, next)
```
It is ordered `LOWEST_PREFERENCE` such that `TracingServerInterceptor` runs first, and it does.
I can see the brave gRPC headers while in the `ServerInterceptor`. However, once in the service `A`, a log statement doesn't print any trace or span, and obviously neither does any downstream code. The log is correctly configured, and logs trace and span in the `ServerInterceptor`.

I've read Sleuth and Brave's documentation on gRPC instrumentation, but didn't see anything that discusses modification of context in a `ServerInterceptor`. I also didn't find any documentation on manually propagating Sleuth context for gRPC.

It's not clear where Sleuth looks for trace and span ids. If in the headers, then those are not modified and the trace should be visible in service `A`, but it isn't.

FWIW, the `ServerInterceptor` and service `A` are running on different threads. I didn't configure them to do so, so must be the gRPC library.

Using [grpc-kotlin](https://github.com/grpc/grpc-kotlin) v0.1.5, Spring Cloud Hoxton.SR6 and Brave 5.12.4.

**Comment by marcingrzejszczak** [comment] 2020-10-02 07:14
I think this might be an issue in brave-grpc module. Sleuth is just setting up the autoconfiguration for whatever Brave provides.

**Comment by asarkar** [comment] 2020-10-02 07:20
@marcingrzejszczak Can you offer a workaround? Is there a way to manually propagate the context? AFAIC, the gRPC support is completely broken.

**Comment by marcingrzejszczak** [comment] 2020-10-02 07:24
Nothing that comes to my mind. You can always disable the support if it breaks your production GRPC code `spring.sleuth.grpc.enabled=false`.

**Comment by asarkar** [comment] 2020-10-02 11:01
Not in Prod yet, but ironically, having distributed logging is a requirement to go to Prod.
If not Sleuth/Brave, I’ll have to find another library that can do the tracing.

**Comment by asarkar** [comment] 2020-10-06 00:18
Tried to use OpenTelemetry, but they don't have a Java library for gRPC yet. Filed https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1313, discussion ongoing, but I'm not holding my breath.

@marcingrzejszczak could this issue be related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1748?

**Comment by marcingrzejszczak** [comment] 2020-10-06 04:57
I don't think so. If i were you i would file an issue in the brave project first.

**Comment by OlgaMaciaszek** [comment] 2020-10-12 14:12
Closing in favour of openzipkin/brave#1257. We'll reopen it if it appears the issue is in Sleuth and not Brave.

**Closed by OlgaMaciaszek** 2020-10-12 14:12 UTC
Labels: feedback-provided
