### ISSUE TITLE
Failed to start application with spring.zipkin.enabled=false

### ISSUE THREAD

**Issue by mziemba** [spring-cloud/spring-cloud-sleuth#1197] opened 2019-01-28 09:51 UTC
Spring Boot version: 2.1.2
Spring Cloud version: Greenwich.RELEASE

Issue: with spring.zipkin.enabled=false application fails to start with given error message:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method spanBytesEncoder in org.springframework.cloud.sleuth.zipkin2.ZipkinBackwardsCompatibilityAutoConfiguration required a bean of type 'org.springframework.cloud.sleuth.zipkin2.ZipkinProperties' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.cloud.sleuth.zipkin2.ZipkinProperties' in your configuration.
```

Steps to reproduce:
1. Create a new application from start.spring.io using 'Sleuth' and 'Zipkin Client' dependencies
2. Add the following to application.properties:

```
spring.application.name=test
spring.zipkin.enabled=false
```

3. Run using `./gradlew clean bootRun`

**Comment by marcingrzejszczak** [comment] 2019-01-28 09:51
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/1191

**Closed by marcingrzejszczak** 2019-01-28 09:51 UTC
