### ISSUE TITLE
Integrate STOMP exceptions

### ISSUE THREAD

**Issue by kissings** [spring-cloud/spring-cloud-sleuth#1732] opened 2020-09-04 01:40 UTC
The following exceptions occur when integrating STOMP protocol for webSocket implementation,
org.springframework.cloud.sleuth.instrument.messaging.TracingChannelInterceptor#preSend
org.springframework.cloud.sleuth.instrument.messaging.MessageHeaderPropagation#removeAnyTraceHeaders
org.springframework.messaging.support.NativeMessageHeaderAccessor#removeNativeHeader
org.springframework.messaging.MessageDeliveryException: Failed to send message to ExecutorSubscribableChannel[clientOutboundChannel]; nested exception is java.lang.UnsupportedOperationException
![image](https://user-images.githubusercontent.com/48820729/92189844-40526900-ee92-11ea-857f-0a44ea96f77e.png)
![image](https://user-images.githubusercontent.com/48820729/92189811-329ce380-ee92-11ea-9b6d-d17f42967d14.png)

**Comment by rstoyanchev** [comment] 2020-09-29 09:12
@marcingrzejszczak I believe this is a duplicate of https://github.com/spring-projects/spring-framework/issues/25821 so you can close it for now. @kissings if you could please subscribe to referenced issue and give the fix a try when it is available.

**Closed** 2020-10-13 06:22 UTC
Labels: bug
