### ISSUE TITLE
The tracing chain is not complete when Spring Cloud Zuul enable okhttp3

### ISSUE THREAD

**Issue by weiwunb** [spring-cloud/spring-cloud-sleuth#1142] opened 2018-11-22 15:20 UTC
Question

The tracing chain is not complete when Spring Cloud Zuul enable okhttp3.

- spring-boot.version: `2.0.3.RELEASE`
- spring-cloud.version: `Finchley.RELEASE`

In our test scenario, we call the `test-demo-api` through spring cloud zuul and want to get the tracing data from zipkin. Here is the zipkin configuration:
```
spring:
  application:
    name: ccf-gateway-app
  zipkin:
    enabled: true
    sender:
      type: web
    base-url: http://xxx.xxx.xxx.xxx:9411
  sleuth:
    sampler:
      probability: 1.0
```

---

Here is the tracing chain when we use **apache http client**:

```
application.yaml
--------
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 1000
  httpclient:
    enabled: true
  okhttp:
    enabled: false
```

<img src="https://user-images.githubusercontent.com/28476370/48910736-ae8b8e80-eeab-11e8-95b5-d7eb0f61b046.png">

---

Here is the tracing chain when we use **okhttp3**:

```
pom.xml
---
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-zipkin</artifactId>
</dependency>
```

```
application.yaml
--------
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 1000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
```

<img width="792" alt="wechatimg814" src="https://user-images.githubusercontent.com/28476370/48910929-3c677980-eeac-11e8-86e4-c3268c441558.png">

---

As you see, the tracing data miss the test-demo-api part when we enable okhttp3.

We found this link [brave-instrumentation-okhttp3](https://github.com/openzipkin/brave/tree/master/instrumentation/okhttp3), is this a bug in `spring-cloud-starter-zipkin`?

**Comment by hsoftxl** [comment] 2018-12-28 10:38
i have same issue

**Comment by hsoftxl** [comment] 2018-12-29 03:47
import 


        <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-okhttp3</artifactId>
            <version>5.6.0</version>
        </dependency>



add source : 

@Bean
    public OkHttpClient.Builder okhttpBuilder(Tracing trace) {
        return new OkHttpClient.Builder().addNetworkInterceptor(TracingInterceptor.create(trace));
    }

**Comment by marcingrzejszczak** [comment] 2019-01-07 10:06
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-01-15 19:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-01-21 10:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-01-21 10:10 UTC
