### ISSUE TITLE
Spring Cloud 2021.0.0 Upgrade results in "java.lang.ClassCastException: class reactor.core.publisher.MonoPeekTerminal cannot be cast to class reactor.core.publisher.Flux"

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-sleuth#2077] opened 2021-12-13 15:57 UTC
**Describe the bug**
When Upgrading from Spring Boot 2.5 -> 2.6.1 and Spring Cloud 2020.0.4 -> 2021.0.0 for a spring cloud stream consumer I get the error

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ClassCastException: class reactor.core.publisher.MonoPeekTerminal cannot be cast to class reactor.core.publisher.Flux (reactor.core.publisher.MonoPeekTerminal and reactor.core.publisher.Flux are in unnamed module of loader 'app')
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[spring-boot-2.6.1.jar:2.6.1]
	at example.MyApplication.main(MyApplication.java:10) ~[classes/:na]
Caused by: java.lang.ClassCastException: class reactor.core.publisher.MonoPeekTerminal cannot be cast to class reactor.core.publisher.Flux (reactor.core.publisher.MonoPeekTerminal and reactor.core.publisher.Flux are in unnamed module of loader 'app')
	at org.springframework.cloud.sleuth.instrument.messaging.TraceFunctionAroundWrapper.reactorFluxStream(TraceFunctionAroundWrapper.java:187) ~[spring-cloud-sleuth-instrumentation-3.1.0.jar:3.1.0]
	at org.springframework.cloud.sleuth.instrument.messaging.TraceFunctionAroundWrapper.reactorStream(TraceFunctionAroundWrapper.java:120) ~[spring-cloud-sleuth-instrumentation-3.1.0.jar:3.1.0]
	at org.springframework.cloud.sleuth.instrument.messaging.TraceFunctionAroundWrapper.doApply(TraceFunctionAroundWrapper.java:97) ~[spring-cloud-sleuth-instrumentation-3.1.0.jar:3.1.0]
	at org.springframework.cloud.function.context.catalog.FunctionAroundWrapper.apply(FunctionAroundWrapper.java:47) ~[spring-cloud-function-context-3.2.1.jar:3.2.1]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$1.doApply(SimpleFunctionRegistry.java:256) ~[spring-cloud-function-context-3.2.1.jar:3.2.1]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:550) ~[spring-cloud-function-context-3.2.1.jar:3.2.1]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.bindFunctionToDestinations(FunctionConfiguration.java:512) ~[spring-cloud-stream-3.2.1.jar:3.2.1]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.afterPropertiesSet(FunctionConfiguration.java:418) ~[spring-cloud-stream-3.2.1.jar:3.2.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.13.jar:5.3.13]
	... 16 common frames omitted
```
I can get rid of this error in two ways
1) downgrade to spring cloud 2020
2) turn of sleuth function using spring.sleuth.function.enabled=false

My consumer is of the form

```
  @Bean
  public Function<Flux<Message<AvroFxRateEvent>>, Mono<Void>> fxRates() {
    return events -> events.flatMapSequential(event -> {
      System.out.println("***" + event + "***");
      return Mono.empty();
    }, 1).then();
  }
```

**Sample**
See https://github.com/davidmelia/spring-boot-webflux-avro-sink-only

Simply start - you don't actually need the kafka topic because it fails on bootstrap.

**Comment by marcingrzejszczak** [comment] 2021-12-13 15:59
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/2068 ? Can you try the latest snapshots?

**Comment by davidmelia** [comment] 2021-12-13 16:28
Sorry @marcingrzejszczak  I didn't find that one for some reason however I can confirm the latest snapshot fixes this issue.

Thanks :-)

**Comment by davidmelia** [comment] 2021-12-16 12:00
@marcingrzejszczak  sorry but this is still broke as I left _spring.sleuth.function.enabled=false_ on by mistake 

I have updated my prototype https://github.com/davidmelia/spring-boot-webflux-avro-sink-only to 2021.0.1-SNAPSHOT and **can confirm it's still broken :-(**

**Comment by adamsmith118** [comment] 2021-12-22 09:45
Hi @marcingrzejszczak - We have the same problem as @davidmelia.

Any chance we could get this issue re-opened?

**Closed** 2022-01-17 10:14 UTC
Labels: bug
