### ISSUE TITLE
Span.Events are not being reported when using servlet filters

### ISSUE THREAD

**Issue by mhoshi-vm** [spring-cloud/spring-cloud-sleuth#2025] opened 2021-09-18 06:58 UTC
**Describe the bug**
I am trying to add a span.event via servlet filters but haven't been successful. 
Using wavefront integrations, this part always reports "Logs 0".

https://github.com/mhoshi-vm/spring-petclinic/blob/main/src/main/java/org/springframework/samples/petclinic/system/AddSpanTagsToServlet.java#L53

I have already confirmed this currently is only seen using servlet filters, as for example I have seen the following was able to report the span event.

https://github.com/mhoshi-vm/spring-petclinic/blob/main/src/main/java/org/springframework/samples/petclinic/system/AddSpansToRepository.java#L43

To test further I overwritten the TracerFilter and forcefully added a tag and span event.
Wavefront integration is also enabled so running this will also trigger a freemium account creation

https://github.com/mhoshi-vm/spring-petclinic/blob/tracingfilter-test/src/main/java/org/springframework/cloud/sleuth/instrument/web/servlet/TracingFilter.java#L68-L69

The result is the following.
•  I see the span tag "aaa: bbb" added to all spans.
• However span.events are not being preserved and reports "Logs 0"
![image](https://user-images.githubusercontent.com/67083789/133879386-87fb159b-a0c9-4646-962d-9934d28b7448.png)

**Sample**
Use the following code.  
https://github.com/mhoshi-vm/spring-petclinic/tree/tracingfilter-test

```
mvn clean
mvn spring-boot:run
```

Then access http://localhost:8080/oups.
After that go into wavefront traces.

**Comment by mhoshi-vm** [comment] 2021-09-20 05:01
As a comparison, this line which adds spans using AOP, has no issues showing the span events

https://github.com/mhoshi-vm/spring-petclinic/blob/e4632f9559abcdac4473cd689708968b16809c5f/src/main/java/org/springframework/samples/petclinic/system/AddSpansToRepository.java#L33

![image](https://user-images.githubusercontent.com/67083789/133958718-52ecbc6d-da96-4b3d-b825-1aa30ca33d5b.png)

Traces can be generated for example accessing http://localhost:8080/owners?lastName=d

**Comment by marcingrzejszczak** [comment] 2021-09-23 09:49
I have confirmed that the problem is there in Wavefront. The Wavefront team is working on it. Once they have it resolved I will comment on this issue. Until then I'll close it.

**Closed by marcingrzejszczak** 2021-09-23 09:49 UTC
Labels: in progress
