### ISSUE TITLE
Correlation scope misaligned error in a Spring Cloud Gateway application

### ISSUE THREAD

**Issue by ntuveri** [spring-cloud/spring-cloud-sleuth#2026] opened 2021-09-22 11:31 UTC
**Use case**
I'm trying to integrate Spring Cloud Sleuth in a Spring Cloud Gateway application. My final goal is to add a custom field to the trace context to be propagated to downstream services and to log that custom field in logs though MDC.

**Describe the bug**
When the application receives an HTTP request, an assertion error is thrown and the application returns 500:
```2021-09-22 13:19:02.115 ERROR [mdc-span-misaligned,4329a911636eb5fd,4329a911636eb5fd] 2436 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [e30b2d64-1]  500 Server Error for HTTP GET "/get?customId=1"

java.lang.AssertionError: Misalignment: popped updateScope false !=  expected false
        at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:86) ~[brave-5.13.2.jar!/:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ? org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain]
        |_ checkpoint ? HTTP GET "/get?customId=1" [ExceptionHandlingWebHandler]
Stack trace:
                at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:86) ~[brave-5.13.2.jar!/:na]
                at brave.baggage.CorrelationFlushScope.close(CorrelationFlushScope.java:37) ~[brave-5.13.2.jar!/:na]
                at brave.baggage.CorrelationUpdateScope$Multiple.close(CorrelationUpdateScope.java:108) ~[brave-5.13.2.jar!/:na]
                at org.springframework.cloud.sleuth.brave.bridge.BraveScope.close(BraveCurrentTraceContext.java:99) ~[spring-cloud-sleuth-brave-3.0.3.jar!/:3.0.3]
                at org.springframework.cloud.sleuth.instrument.web.TraceWebFilter$MonoWebFilterTrace.subscribe(TraceWebFilter.java:185) ~[spring-cloud-sleuth-instrumentation-3.0.3.jar!/:3.0.3]
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.9.jar!/:3.4.9]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.9.jar!/:3.4.9]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4338) ~[reactor-core-3.4.9.jar!/:3.4.9]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255) ~[reactor-core-3.4.9.jar!/:3.4.9]
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.4.9.jar!/:3.4.9]
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) [reactor-core-3.4.9.jar!/:3.4.9]
                at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:915) ~[reactor-netty-http-1.0.10.jar!/:1.0.10]
                at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:654) ~[reactor-netty-core-1.0.10.jar!/:1.0.10]
                at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:478) ~[reactor-netty-core-1.0.10.jar!/:1.0.10]
                at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:517) ~[reactor-netty-http-1.0.10.jar!/:1.0.10]
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) ~[reactor-netty-core-1.0.10.jar!/:1.0.10]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:208) ~[reactor-netty-http-1.0.10.jar!/:1.0.10]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.67.Final.jar!/:4.1.67.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.67.Final.jar!/:4.1.67.Final]
                at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_201]
```
The error seems to occur when `spring.sleuth.reactor.instrumentation-type=decorate_queues` and when the application is configured to flush to MDC on field updates.
The error does not occur when `spring.sleuth.reactor.instrumentation-type=decorate_on_each`.

**Sample**
A test case is provided in this repo: https://github.com/ntuveri/mdc-scope-misaligned
The error can be reproduced with the following commands:
1. ` .\gradlew.bat bootJar`
2. ` java -enableassertions -jar .\build\libs\mdc-scope-misaligned-0.0.1-SNAPSHOT.jar`
3. Request the URL http://localhost:8080/get?customId=1

I will be glad to provide further information

**Comment by marcingrzejszczak** [comment] 2021-10-13 08:42
> With decorate_queues we achieve automatic instrumentation of both framework and user code, with good performance, but we have to accept that some spans may pollute thread locals. I don't know if keeping assertions disabled may hide some unexpected behavior due to those spans left in thread locals.

That's correct and you should be fine with those spans in thread locals. Nobody has complained about this until now.

> With manual we get best performance but we have to manually instrument code and we are limited to user code only.

Not necessarily. If you're not doing flatmaps it should work fine due to this instrumentation: 

https://github.com/spring-cloud/spring-cloud-sleuth/blob/v3.0.4/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/web/client/TraceWebClientAutoConfiguration.java#L106-L123

If you're doing flatmaps you need to pass the spans between the Reactor operators yourself.

> With decorate_on_each we achieve automatic instrumentation of both framework and user code and proper clean up of no longer used spans, but we have to accept the worst performance.

Worst performance is an understatement. You can check some older issues that reference this problem. On queue wrapping has a minimal impact cause it creates the wrapping only for the last operator.

**Comment by szberes** [comment] 2022-03-09 12:28
Hi @marcingrzejszczak @ntuveri ,
We had a similar issue and managed to reduce the code to only a few classes. Basically we tried to add a new BaggageField to the MDC and we have not changed the default instrumentation type. If I remove the MDC decorator bean, the error disappears (and the new field from the MDC as well).
code: https://github.com/szberes/sleuth-scope-misalignment
To reproduce the error, run `./gradlew test`

Do you think it is the same issue?

The error message looks similar:
```
   2022-03-09 11:37:02.094     ERROR traceid-test:local [test-trace-id,1d702f178f684407,1d702f178f684407] 60681 --- [parallel-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

    java.lang.AssertionError: Misalignment: popped updateScope false !=  expected false
        at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:86) ~[brave-5.13.7.jar:na]
        at brave.baggage.CorrelationFlushScope.close(CorrelationFlushScope.java:37) ~[brave-5.13.7.jar:na]
        at brave.baggage.CorrelationUpdateScope$Multiple.close(CorrelationUpdateScope.java:108) ~[brave-5.13.7.jar:na]
        at brave.Tracer$SpanInScope.close(Tracer.java:621) ~[brave-5.13.7.jar:na]
        at org.springframework.cloud.sleuth.brave.bridge.BraveSpanInScope.close(BraveTracer.java:153) ~[spring-cloud-sleuth-brave-3.1.1.jar:3.1.1]
        at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$21(ReactorSleuth.java:487) ~[spring-cloud-sleuth-instrumentation-3.1.1.jar:3.1.1]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:163) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:146) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:166) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.4.15.jar:3.4.15]
        at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:324) ~[spring-cloud-sleuth-instrumentation-3.1.1.jar:3.1.1]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.4.15.jar:3.4.15]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

    2022-03-09 11:37:02.095     ERROR traceid-test:local [test-trace-id,1d702f178f684407,1d702f178f684407] 60681 --- [parallel-1] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

    java.util.NoSuchElementException: null
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363) ~[na:na]
        at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:594) ~[na:na]
        at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:85) ~[brave-5.13.7.jar:na]
        at brave.baggage.CorrelationFlushScope.close(CorrelationFlushScope.java:37) ~[brave-5.13.7.jar:na]
        at brave.baggage.CorrelationUpdateScope$Multiple.close(CorrelationUpdateScope.java:108) ~[brave-5.13.7.jar:na]
        at org.springframework.cloud.sleuth.brave.bridge.BraveScope.close(BraveCurrentTraceContext.java:99) ~[spring-cloud-sleuth-brave-3.1.1.jar:3.1.1]
        at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:325) ~[spring-cloud-sleuth-instrumentation-3.1.1.jar:3.1.1]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.4.15.jar:3.4.15]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.4.15.jar:3.4.15]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by marcingrzejszczak** [comment] 2022-03-09 12:31
Yeah that's possible. I'll try to look into that ASAP. The Reactor instrumentation is... problematic :grimacing:

**Comment by fredrik-corneliusson** [comment] 2022-03-18 09:43
Maybe it's implied but just as a warning to others affected by this issue, This issue caused quite severe memory leak in our application.

**Comment by spring-cloud-issues** [comment] 2022-04-06 12:20
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by m-hofmann** [comment] 2022-04-06 15:25
Please re-open the issue, we too have been hit by the memory leak mentioned above using v3.1.1. Definitely an issue.

**Comment by spring-cloud-issues** [comment] 2022-04-06 15:55
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by spring-cloud-issues** [comment] 2022-04-06 16:30
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by marawan31** [comment] 2022-05-25 12:42
Hello, we have the exact same problem (even with `decorate_on_each`). We have a couple of baggage fields with `flushOnUpdate` enabled. After some debugging, we found out the problem happens in `TraceHandlerFunction`. Basically we can see that a scope is created there in a `doFirst`, then it's closed in a `doFinally`. The problem is that the doFinally doesn't always execute at the end of the call since it's using mono. This sometimes results in the calling scope closing before this one which causes the wrong scope to be popped in `CorrelationFlushScope`. If we override this behaviour by creating our own bean of `TraceHandlerFunctionAdapterPostProcessor`, the problem doesn't happen anymore.

**Comment by marcingrzejszczak** [comment] 2022-05-25 13:22
Can you show me how your own bean looks like then?

**Comment by marcingrzejszczak** [comment] 2022-05-26 12:23
I've been investigating this for the past couple of days and I don't see any meaningful solution for now. I have some ideas but IMO until now as a workaround you should consider disabling Sleuth. Sleuth + Reactor = problems :( I will do my best to provide some better workarounds or fixes of course

**Comment by marcingrzejszczak** [comment] 2022-05-30 09:43
OK I have good and bad news... The good is that I know what would be the suggested approach that "should always work fine" :tm: . The bad news is that requires switch to fully manual mode.

.application.yaml
```yaml
spring:
  application:
    name: traceid-test
  config:
    import:
      - classpath:/logging.properties
  sleuth:
    baggage:
      local-fields: additionalTraceId
      correlation-fields: additionalTraceId
    reactor:
      # Switch to manual mode
      instrumentation-type: manual
```

.configuration code
```java
package com.java.tracing.sleuthissuereprodction;

import brave.baggage.BaggageField;
import brave.baggage.CorrelationScopeConfig;
import brave.context.slf4j.MDCScopeDecorator;
import brave.propagation.CurrentTraceContext;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class TracingConfiguration {

	private static final String ADDITIONAL_TRACE_ID = "additionalTraceId";

	@Bean
	BaggageField tescoTraceIdField() {
		return BaggageField.create(ADDITIONAL_TRACE_ID);
	}

	// todo: this bean causes the issue!! if you comment out line 21 the issue disappears
	@Bean
	CurrentTraceContext.ScopeDecorator mdcScopeDecorator() {
		return MDCScopeDecorator.newBuilder()
				.clear()
				.add(CorrelationScopeConfig.SingleCorrelationField.newBuilder(tescoTraceIdField())
						.flushOnUpdate()
						.build())
				.build();
	}
}
```

.application code
```java
package com.java.tracing.sleuthissuereprodction;

import javax.annotation.PostConstruct;

import lombok.RequiredArgsConstructor;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;
import reactor.util.Logger;
import reactor.util.Loggers;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.cloud.sleuth.BaggageInScope;
import org.springframework.cloud.sleuth.Span;
import org.springframework.cloud.sleuth.TraceContext;
import org.springframework.cloud.sleuth.Tracer;
import org.springframework.cloud.sleuth.instrument.web.WebFluxSleuthOperators;
import org.springframework.stereotype.Component;

@EnableConfigurationProperties
@RequiredArgsConstructor
@SpringBootApplication
public class SleuthIssueReproductionApplication {

	public static void main(String[] args) {
		SpringApplication.run(SleuthIssueReproductionApplication.class, args);
	}

	private static final Logger logger = Loggers.getLogger(SleuthIssueReproductionApplication.class);

	private final TestBean testBean;

	@PostConstruct
	void init() {

		logger.info("FOO");

		testBean.testFlux().subscribe();

		logger.info("BAR");

		testBean.testFlux().subscribe();

		logger.info("BAZ");

		testBean.testFlux().subscribe();
	}

	@Component
	@RequiredArgsConstructor
	public static class TestBean {

		private final Tracer tracer;

		public Flux<String> testFlux() {
			// Create a new Span in the main thread
			Span span = tracer.nextSpan();
			// Create or retrieve baggage in the main thread. Remember to always pass the `TraceContext` when retrieving and setting the baggage
			BaggageInScope baggageInScope = tracer.getBaggage(span.context(), "additionalTraceId").set(span.context(), "test-trace-id");
			return Flux
						.deferContextual(contextView -> Flux.just("testFluxData")
								// Use the WebFluxSleuthOperators where you pass the context view that contains the TraceContext
								.doOnNext(data -> WebFluxSleuthOperators.withSpanInScope(contextView, () -> logger.warn("Baggage value here {}", baggageInScope.get())))
								.doOnNext(data -> WebFluxSleuthOperators.withSpanInScope(contextView, () -> logger.warn("Start testFlux")))
								.flatMap(this::testFlux2)
								.doOnNext(cmdMsg -> WebFluxSleuthOperators.withSpanInScope(contextView, () -> logger.warn("my custom message")))
								.subscribeOn(Schedulers.parallel())
								// Since you're controlling the flux flow you ensure that trace information gets propagated to new threads via the Reactor Context
								.doOnNext(success -> WebFluxSleuthOperators.withSpanInScope(contextView, () -> logger.info("data at the end: " + success)))
								// If you want to read baggage you need to pass the Span's Trace Context
								.doOnNext(s -> WebFluxSleuthOperators.withSpanInScope(contextView, () -> logger.info("Baggage value at the end:  " + tracer.getBaggage(span.context(), "additionalTraceId").get())))
								.doOnError(error -> WebFluxSleuthOperators.withSpanInScope(contextView, () -> logger.error("Error: {}", error.getMessage())))
								.doOnSubscribe(subscription1 -> WebFluxSleuthOperators.withSpanInScope(contextView, () -> logger.warn("subscribed to testFlux"))))

							// !!! For this flux you're setting the original Span and TraceContext in the Reactor Context 
							.contextWrite(context -> context.put(Span.class, span).put(TraceContext.class, span.context()));
		}

		private Flux<String> testFlux2(String param) {
			return Flux.just(param).map(String::toUpperCase);
		}
	}
}
```

Unfortunately due to the fact that Reactor is changing threads we are not able at this point to guarantee that the tracing information will be properly cleared. If you go with the manual mode it's much faster and you control where and how the tracing information gets propagated.

**Comment by spring-cloud-issues** [comment] 2022-06-06 09:45
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by TheBestPessimist** [comment] 2022-06-07 10:55
Is the resolution: "do it manually"?

**Comment by marcingrzejszczak** [comment] 2022-06-07 11:06
Unless the `on each` or `on queue wrapping` instrumentation works ok for you the solution for now would be to go with manual instrumentation

**Comment by jorgegueyer** [comment] 2022-06-07 18:41
Hi @marcingrzejszczak First, thank you for your time with this problem!
I have a question:
I am using Spring GraphQL together with Spring Cloud Sleuth (do_on_each instrumentation in Spring Boot 2.7.0 and Spring Cloud 2021.0.3). In my solution, I am developing a SDL Directive for reactive controllers using reactor streams. I have some problems with our friend **Misalignment**:

```java
Suppressed: java.lang.AssertionError: Misalignment: popped updateScope false !=  expected false
		at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:86)
		at brave.baggage.CorrelationFlushScope.close(CorrelationFlushScope.java:37)
		at org.springframework.cloud.sleuth.brave.bridge.BraveScope.close(BraveCurrentTraceContext.java:99)
		at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:104)
		... 9 more
	Suppressed: java.util.NoSuchElementException
		at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
		at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:593)
		at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:85)
		at brave.baggage.CorrelationFlushScope.close(CorrelationFlushScope.java:37)
		at org.springframework.cloud.sleuth.brave.bridge.BraveScope.close(BraveCurrentTraceContext.java:99)
		at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:325)
		... 7 more
```

It seems that the instrumentation is trying to remove more CorrelationUpdateScope instances from stack than are actually there. Finally a NoSuchElementException is thrown because java.util.ArrayDeque is empty and removeFirst(...) function fails.

**Ok, no problem!**. I know that Sleuth Reactor instrumentation is problematic, but I would like to understand the following Sleuth class:

```java
public class TraceHandlerFunction implements HandlerFunction {

	private final HandlerFunction<?> delegate;

	private final BeanFactory beanFactory;

	private CurrentTraceContext currentTraceContext;

	public TraceHandlerFunction(HandlerFunction<?> delegate, BeanFactory beanFactory) {
		this.delegate = delegate;
		this.beanFactory = beanFactory;
	}

	@Override
	public Mono<?> handle(ServerRequest serverRequest) {
		AtomicReference<CurrentTraceContext.Scope> scope = new AtomicReference<>();
		return Mono.just(scope)
				.doFirst(() -> serverRequest.attribute(TraceWebFilter.TRACE_REQUEST_ATTR)
						.ifPresent(span -> scope.set(currentTraceContext().maybeScope(((Span) span).context()))))
				.flatMap(r -> this.delegate.handle(serverRequest)).doFinally(signalType -> {
					CurrentTraceContext.Scope spanInScope = scope.get();
					if (spanInScope != null) {
						spanInScope.close();
					}
				});
	}

	private CurrentTraceContext currentTraceContext() {
		if (this.currentTraceContext == null) {
			this.currentTraceContext = this.beanFactory.getBean(CurrentTraceContext.class);
		}
		return this.currentTraceContext;
	}

}
```
Why is it necessary to set the current span in scope in the doFirst(...) operator and after close the scope using a doFinally(...) operator, wrapping the rest of the stream?
My problems comes from this implementation. I have sustituted this for my own implementation and the error desappears. Simply I have changed the implementation of the handle method by this:

```java
@Override
public Mono<?> handle(ServerRequest serverRequest) {
	Optional<Object> spanOptional = serverRequest.attribute(TRACE_REQUEST_ATTR);
	if (spanOptional.isEmpty()) {
		return this.delegate.handle(serverRequest);
	}
	return
		Mono.justOrEmpty(spanOptional)
			.cast(Span.class)
			.flatMap((Span span) -> {
				try (CurrentTraceContext.Scope scope = currentTraceContext().maybeScope(span.context())) {
					return this.delegate.handle(serverRequest);
				}
			});
}
```
Ok, this implementation may or may not make sense, but is it really necessary to set the current span in scope with a HandlerFunction? Shouldn't this be done by ScopePassingSpanSubscriber instrumentation? Do you see any problem with solution?

Thanks!

**Comment by marcingrzejszczak** [comment] 2022-06-08 13:08
> Why is it necessary to set the current span in scope in the doFirst(...) operator and after close the scope using a doFinally(...) operator, wrapping the rest of the stream?

Most likely this was written before I wrote the proper reactor instrumentation and I've forgotten to remove this. Can you file a PR with a fix? We would see if things are still working fine.

**Comment by jorgegueyer** [comment] 2022-06-09 08:23
Thanks @marcingrzejszczak! Yes, I can file a PR with the solution between now and tomorrow.

**Comment by fredrik-corneliusson** [comment] 2022-06-14 20:40
Great to see progress on this.
Just curious, would the change @jorgegueyer suggested be likely to fix memory leak issue and make decorate_queues instrumentation a valid alternative to the conversion to "manual"-instrumentation previously suggested?
Thanks for your efforts!

**Closed** 2022-06-15 09:07 UTC
Labels: bug, feedback-provided
