### ISSUE TITLE
Spring Cloud Sleuth not adding configured baggage to the MDC (Spring Integration)

### ISSUE THREAD

**Issue by dsibilio** [spring-cloud/spring-cloud-sleuth#2065] opened 2021-11-29 09:33 UTC
**Describe the bug**
 I was testing out the `spring.sleuth.baggage.remote-fields` and `spring.sleuth.baggage.correlation-fields` properties in order to insert custom fields into the MDC automatically. It works well with HTTP requests as it extracts the header automatically from the request and copies that into the MDC, but when I tested it by sending a Spring Integration message to a channel it didn't do anything.

My setup is as simple as it gets, it's a basic https://start.spring.io project with **Sleuth 3.1.0-RC1** and Web dependencies.
Two headers are configured to be exported to the MDC, as follows:

```yml
spring:
  sleuth:
    sampler:
      probability: 1.0
    baggage:
      remote-fields:
        - http-custom-header
        - event-custom-header
      correlation-fields:
        - http-custom-header
        - event-custom-header
```

One single HTTP endpoint is exposed (`http://localhost:8080/demo`), which in turn writes a message *(including the `event-custom-header`)* to a Spring Integration channel.

If I log the MDC, either in the HTTP controller or downstream, the `http-custom-header` is present _(if sent at request time)_.
If I log the MDC in the `@ServiceActivator` annotated method that is handling the Spring Integration message, the `event-custom-header` is not present, no matter what.

Example logs:

```
2021-11-29 10:27:20.432  INFO [,434e31eeb73dfb2b,434e31eeb73dfb2b] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : HTTP MDC: traceId => 434e31eeb73dfb2b
2021-11-29 10:27:20.432  INFO [,434e31eeb73dfb2b,434e31eeb73dfb2b] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : HTTP MDC: spanId => 434e31eeb73dfb2b
2021-11-29 10:27:20.432  INFO [,434e31eeb73dfb2b,434e31eeb73dfb2b] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : HTTP MDC: http-custom-header => http-header-value
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Message Headers: b3 => 434e31eeb73dfb2b-7c82682a1539ef3f-0
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Message Headers: nativeHeaders => {http-custom-header=[http-header-value]}
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Message Headers: id => 10c2fb00-ec06-d6b2-32aa-db36e87979d1
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Message Headers: event-custom-header => test-event-header
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Message Headers: http-custom-header => http-header-value
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Message Headers: timestamp => 1638178040433
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Event MDC: traceId => 434e31eeb73dfb2b
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Event MDC: spanId => 70334542a17c7884
2021-11-29 10:27:20.433  INFO [,434e31eeb73dfb2b,70334542a17c7884] 10564 --- [nio-8080-exec-3] com.example.demo.web.DemoController      : Event MDC: http-custom-header => http-header-value
```

**Sample**

[Here is the link to the sample](https://github.com/dsibilio/sleuth-baggage-demo/tree/repro), you can simulate the explained behaviour by sending an HTTP request like the following:

```sh
curl -H "http-custom-header: http-header-value" http://localhost:8080/demo
```

**Comment by marcingrzejszczak** [comment] 2022-04-13 07:40
I've updated your sample to the latest version of sleuth and I get the following.

```
2022-04-13 09:37:12.710  INFO [,4289eabb4f31d9d9,4289eabb4f31d9d9] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : HTTP MDC: traceId => 4289eabb4f31d9d9
2022-04-13 09:37:12.711  INFO [,4289eabb4f31d9d9,4289eabb4f31d9d9] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : HTTP MDC: spanId => 4289eabb4f31d9d9
2022-04-13 09:37:12.711  INFO [,4289eabb4f31d9d9,4289eabb4f31d9d9] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : HTTP MDC: build-number => 12345
2022-04-13 09:37:12.711  INFO [,4289eabb4f31d9d9,4289eabb4f31d9d9] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : HTTP MDC: http-custom-header => http sleuth baggage
Disconnected from the target VM, address: '127.0.0.1:59945', transport: 'socket'
2022-04-13 09:38:02.251  INFO [,4289eabb4f31d9d9,f6bbeb85bd9392cf] 347751 --- [nio-8080-exec-1] o.s.i.h.s.MessagingMethodInvokerHelper   : Overriding default instance of MessageHandlerMethodFactory with provided one.
2022-04-13 09:38:02.252  INFO [,4289eabb4f31d9d9,f6bbeb85bd9392cf] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: traceId => 4289eabb4f31d9d9
2022-04-13 09:38:02.252  INFO [,4289eabb4f31d9d9,f6bbeb85bd9392cf] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: spanId => f6bbeb85bd9392cf
2022-04-13 09:38:02.252  INFO [,4289eabb4f31d9d9,f6bbeb85bd9392cf] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: build-number => 12345
2022-04-13 09:38:02.252  INFO [,4289eabb4f31d9d9,f6bbeb85bd9392cf] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: event-custom-header => test-event-header
2022-04-13 09:38:02.252  INFO [,4289eabb4f31d9d9,f6bbeb85bd9392cf] 347751 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: http-custom-header => http sleuth baggage
```

I see the `event-custom-header` in the `Event MDC` part. Can you double check that the problem still persists?

**Comment by dsibilio** [comment] 2022-04-13 18:05
Hi @marcingrzejszczak, I tried again today after updating `spring-boot-starter-parent` to `2.6.6` and `spring-cloud-dependencies` to `2021.0.1` which in turn lets the project pull `spring-cloud-sleuth:3.1.1`, but the problem is still there (the `event-custom-header` is missing):

```
2022-04-13 19:55:27.985  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Message Headers: b3 => 1bb806328c362b69-d5c9bd844c3d3c05-0
2022-04-13 19:55:27.985  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Message Headers: nativeHeaders => {http-custom-header=[http-header-value]}
2022-04-13 19:55:27.986  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Message Headers: id => 6f57a08c-bba7-7f06-35a1-13b2e34c5151    
2022-04-13 19:55:27.986  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Message Headers: event-custom-header => test-event-header      
2022-04-13 19:55:27.986  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Message Headers: http-custom-header => http-header-value       
2022-04-13 19:55:27.987  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Message Headers: timestamp => 1649872527972
2022-04-13 19:55:27.987  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: traceId => 1bb806328c362b69
2022-04-13 19:55:27.987  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: spanId => 72ed898636ea8297
2022-04-13 19:55:27.988  INFO [,1bb806328c362b69,72ed898636ea8297] 10020 --- [nio-8080-exec-1] com.example.demo.web.DemoController      : Event MDC: http-custom-header => http-header-value
```

**Did you remember to switch to the `repro` branch before performing your test?** The `main` branch on that demo project has a custom solution (a [GlobalChannelInterceptor](https://github.com/dsibilio/sleuth-baggage-demo/blob/main/src/main/java/com/example/demo/config/SleuthBaggageChannelInterceptor.java#L24-L30)) in place to compensate for the issue that I described here, so that might be why you see it there. I just now realize I provided a link to the `repro` branch when sharing the sample, but that's easy to overlook.

**Comment by marcingrzejszczak** [comment] 2022-04-13 18:20
I haven't changed the branch, this might be the reason why i couldn't reproduce it 😬

**Comment by marcingrzejszczak** [comment] 2022-04-15 09:03
OK I think I understand what's going on. So your custom solution is really the proper solution IMO. Brave works in such a way that even though the correlation field might have changed the value you not necessarily will see its updated version. That's why you need to do the flush on update (the way you do it in your custom solution). We describe this [here](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-baggage) in the docs. I don't see this being a bug really.

**Comment by dsibilio** [comment] 2022-04-15 11:06
It would've been ideal if this kind of baggage propagation to the MDC worked out of the box, but I understand. I'm fine with the custom solution that I have in place 👍 Feel free to close then.

**Comment by marcingrzejszczak** [comment] 2022-04-15 11:07
We will think about changing this in Spring Framework 6, Spring Boot 3 and Micrometer Tracing. I'm closing this until then.

**Closed by marcingrzejszczak** 2022-04-15 11:07 UTC
Labels: waiting for feedback
