### ISSUE TITLE
zipkin client has no load balance strategy, only get the first server.

### ISSUE THREAD

**Issue by LittleShrimp1987** [spring-cloud/spring-cloud-sleuth#754] opened 2017-10-19 11:39 UTC
@Configuration
	@ConditionalOnClass(DiscoveryClient.class)
	static class DiscoveryClientZipkinUrlExtractorConfiguration {

		@Autowired(required = false) DiscoveryClient discoveryClient;

		@Bean
		ZipkinUrlExtractor zipkinUrlExtractor() {
			final DiscoveryClient discoveryClient = this.discoveryClient;
			return new ZipkinUrlExtractor() {
				@Override
				public URI zipkinUrl(ZipkinProperties zipkinProperties) {
					if (discoveryClient != null) {
						URI uri = URI.create(zipkinProperties.getBaseUrl());
						String host = uri.getHost();
						List<ServiceInstance> instances = discoveryClient.getInstances(host);
						if (!instances.isEmpty()) {
							return instances.get(0).getUri();
						}
					}
					return URI.create(zipkinProperties.getBaseUrl());
				}
			};
		}
	}

**Comment by marcingrzejszczak** [comment] 2017-10-19 11:40
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/pull/743

**Closed by marcingrzejszczak** 2017-10-19 11:40 UTC
