### ISSUE TITLE
jdbc instrumentation: TraceListenerStrategySpanCustomizer does not work

### ISSUE THREAD

**Issue by alex-kormukhin** [spring-cloud/spring-cloud-sleuth#2251] opened 2023-01-18 18:59 UTC
**Describe the bug**
Sleuth 3.1.5.

First: injection points for subj lists ([datasource-proxy](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java#L105) and [p6spy](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/P6SpyConfiguration.java#L74)) declare list of subj of ? super CommonDataSource, but by spring generics injection rules no any matching subj implementations. All implementations is ? extends CommonDataSource.

customizers.getIfAvailable(ArrayList::new) always return empty list.

customizers type must be `ObjectProvider<List<TraceListenerStrategySpanCustomizer<? extends CommonDataSource>>>` or `ObjectProvider<List<TraceListenerStrategySpanCustomizer>>`.

Second: for [TraceHikariListenerStrategySpanCustomizer.isApplicable](https://github.com/spring-cloud/spring-cloud-sleuth/blob/3.1.x/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceHikariListenerStrategySpanCustomizer.java#L50) dataSource parameter never be instance of HikariDataSource - there will be proxy or wrapper for HikariDataSource which must be unwrapped (not downcasted) to HikariDataSource.

**Comment by marcingrzejszczak** [comment] 2023-02-16 12:31
do you have a reproducer of the problem? a test or a project?

cc @ttddyy

**Comment by spring-cloud-issues** [comment] 2023-02-23 12:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-03-02 12:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed as completed by spring-cloud-issues** 2023-03-02 12:31 UTC
