### ISSUE TITLE
Questions about Span Data as Messages

### ISSUE THREAD

**Issue by Ethanlin013** [spring-cloud/spring-cloud-sleuth#457] opened 2016-11-24 05:21 UTC
Hi,

We're trying to implement a customized span message consumer with Spring-Cloud-Sleuth-Stream to trace the micro services we have built.  We tried to learn from the examples you provided: 
(1)We used https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-stream as the span data producer; 
(2)We used RabbitMQ which we installed on the Mac; 
(3)And we built a Spring boot application using the snippet you provided in the "custom" consumer part on the web http://cloud.spring.io/spring-cloud-sleuth/1.0.x/#_span_data_as_messages as the consumers to . When we visited the URL http://localhost:3379/traced, the web gave us the span and trace data, however, the console for the consumer boot application showed the span data yet threw an Exception :
```
org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException, which
Caused by: org.springframework.messaging.MessageHandlingException: nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 8): Method call: Method sink(java.lang.String) cannot be found on com.example.ConsumerApplication$$EnhancerBySpringCGLIB$$48122ddc type
```

We are new to Spring, but we searched the web, looked through your documents again and again, and tried several ways to troubleshoot: merging those two spring boot applications into one; Declaring different methods declared with `@ServiceActivator(inputChannel = SleuthSink.INPUT)` in the consumer class, removing commented out some code in the consumer class... But they don't work. Any idea about the problem or some ways we can work around this problem? Thanks!!

**Here is the code in the ConsumerApplication.java, which is the only java file in the Spring boot application.**

```
@EnableBinding(SleuthSink.class)
@SpringBootApplication(exclude = SleuthStreamAutoConfiguration.class)
@MessageEndpoint
public class ConsumerApplication {
	
	private static final Log log = LogFactory.getLog(ConsumerApplication.class);
	public static void main(String[] args) {
		SpringApplication.run(ConsumerApplication.class, args);
	}
	
	@ServiceActivator(inputChannel = SleuthSink.INPUT)
    public void sink(Spans input) throws Exception {
       log.info("from sink:" + input);
    }
	
}
```

**Here's the POM.xml for the Span Data input:**

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>spring.test.com.example</groupId>
	<artifactId>spring.sleuth.stream.example</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>spring.sleuth.stream.example</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.2.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-sleuth-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-stream-rabbit -->
		<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Camden.SR2</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

**Here's the Pom.xml for ConsumerApplication:**
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>spring.sleuth.stram.example.receiver</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.2.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-sleuth-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-stream-rabbit -->
		<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Camden.SR2</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

```
**Detailed console info from the consumer application:**
2016-11-23 21:00:51.753  WARN [-,,,] 27346 --- [sleuth.sleuth-1] o.s.c.s.i.m.MessagingSpanExtractor       : Deprecated trace headers detected. Please upgrade Sleuth to 1.1 or start sending headers present in the TraceMessageHeaders class
2016-11-23 21:00:51.843  INFO [-,,,] 27346 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2016-11-23 21:00:51.847  INFO [-,,,] 27346 --- [           main] com.example.ConsumerApplication          : Started ConsumerApplication in 15.534 seconds (JVM running for 16.312)
2016-11-23 21:00:52.773  WARN [-,,,] 27346 --- [sleuth.sleuth-1] o.s.c.s.i.m.MessagingSpanExtractor       : Deprecated trace headers detected. Please upgrade Sleuth to 1.1 or start sending headers present in the TraceMessageHeaders class
2016-11-23 21:00:54.782  WARN [-,,,] 27346 --- [sleuth.sleuth-1] o.s.c.s.i.m.MessagingSpanExtractor       : Deprecated trace headers detected. Please upgrade Sleuth to 1.1 or start sending headers present in the TraceMessageHeaders class
2016-11-23 21:00:54.792  WARN [-,,,] 27346 --- [sleuth.sleuth-1] o.s.a.r.r.RejectAndDontRequeueRecoverer  : Retries exhausted for message (Body:'{"host":{"serviceName":"testSleuthApp","address":"172.29.92.241","port":3379},"spans":[{"begin":1479963619882,"end":1479963619901,"name":"call","traceId":-9195259525389586355,"parents":[4089610043521544862],"spanId":-8053188648366167405,"exportable":true,"tags":{"mvc.controller.class":"SampleController","mvc.controller.method":"call","callable-sleep-millis":"352"},"logs":[],"durationMicros":19460},{"begin":1479963619871,"end":1479963620305,"name":"http:/call","traceId":-9195259525389586355,"parents":[6405173713038580563],"spanId":4089610043521544862,"remote":true,"exportable":true,"logs":[{"timestamp":1479963619871,"event":"sr"},{"timestamp":1479963620305,"event":"ss"}],"durationMicros":433904},{"begin":1479963619850,"end":1479963620308,"name":"http:/call","traceId":-9195259525389586355,"parents":[6405173713038580563],"spanId":4089610043521544862,"exportable":true,"tags":{"http.path":"/call","http.url":"http://localhost:3379/call","http.method":"GET","http.host":"localhost"},"logs":[{"timestamp":1479963619854,"event":"cs"},{"timestamp":1479963620308,"event":"cr"}],"durationMicros":458077},{"begin":1479963619033,"end":1479963620308,"name":"http:customTraceEndpoint","traceId":-9195259525389586355,"parents":[7425186976143559630],"spanId":6405173713038580563,"exportable":true,"tags":{"random-sleep-millis":"766"},"logs":[],"durationMicros":1274420},{"begin":1479963619022,"end":1479963620309,"name":"traced","traceId":-9195259525389586355,"parents":[-9195259525389586355],"spanId":7425186976143559630,"exportable":true,"tags":{"mvc.controller.method":"traced","mvc.controller.class":"SampleController"},"logs":[],"durationMicros":1287240},{"begin":1479963618939,"end":1479963620309,"name":"http:/traced","traceId":-9195259525389586355,"spanId":-9195259525389586355,"exportable":true,"logs":[{"timestamp":1479963618943,"event":"sr"},{"timestamp":1479963620309,"event":"ss"}],"durationMicros":1371329}]}' MessageProperties [headers={spanTraceId=a127f84df4126347, spanId=a127f84df4126347, X-B3-SpanId=a127f84df4126347, currentSpan=[Trace: a127f84df4126347, Span: a127f84df4126347, Parent: null, exportable:false], X-B3-Sampled=0, X-Message-Sent=true, X-B3-TraceId=a127f84df4126347, messageSent=true, X-Current-Span=[Trace: a127f84df4126347, Span: a127f84df4126347, Parent: null, exportable:false], spanSampled=0, contentType=text/plain, originalContentType=application/json;charset=UTF-8}, timestamp=null, messageId=null, userId=null, receivedUserId=null, appId=null, clusterId=null, type=null, correlationId=null, correlationIdString=null, replyTo=null, contentType=text/plain, contentEncoding=null, contentLength=0, deliveryMode=null, receivedDeliveryMode=PERSISTENT, expiration=null, priority=0, redelivered=false, receivedExchange=sleuth, receivedRoutingKey=sleuth, receivedDelay=null, deliveryTag=1, messageCount=0, consumerTag=amq.ctag-4rt7Ia0KYEcsNn4qTUJCIg, consumerQueue=sleuth.sleuth])

org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:871) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:781) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:701) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:99) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:191) ~[spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74) ~[spring-retry-1.1.4.RELEASE.jar!/:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276) [spring-retry-1.1.4.RELEASE.jar!/:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:172) [spring-retry-1.1.4.RELEASE.jar!/:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:98) [spring-retry-1.1.4.RELEASE.jar!/:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at com.sun.proxy.$Proxy108.invokeListener(Unknown Source) [na:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1213) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:682) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1191) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1175) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1200(SimpleMessageListenerContainer.java:99) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1338) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: org.springframework.messaging.MessageHandlingException: nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 8): Method call: Method sink(java.lang.String) cannot be found on com.example.ConsumerApplication$$EnhancerBySpringCGLIB$$48122ddc type
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:96) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:89) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:423) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:292) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:212) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:129) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) ~[spring-messaging-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) ~[spring-messaging-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) ~[spring-messaging-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:171) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$400(AmqpInboundChannelAdapter.java:45) ~[spring-integration-amqp-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$1.onMessage(AmqpInboundChannelAdapter.java:95) ~[spring-integration-amqp-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:778) [spring-rabbit-1.6.5.RELEASE.jar!/:na]
	... 24 common frames omitted
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 8): Method call: Method sink(java.lang.String) cannot be found on com.example.ConsumerApplication$$EnhancerBySpringCGLIB$$48122ddc type
	at org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:211) ~[spring-expression-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:125) ~[spring-expression-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49) ~[spring-expression-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347) ~[spring-expression-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88) ~[spring-expression-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131) ~[spring-expression-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330) ~[spring-expression-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:169) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:317) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93) ~[spring-integration-core-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	... 50 common frames omitted
```

**Comment by marcingrzejszczak** [comment] 2016-12-03 09:26
I guess the problem is related to parsing of messages. We're using Spring Cloud Stream to send and receive messages. Please check out this section of the documentation - http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR1/reference/htmlsingle/#_using_streamlistener_for_automatic_content_type_handling 

What we do in Sleuth is this: https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/StreamEnvironmentPostProcessor.java#L51

So I guess you could consider doing the same either from code or via properties. It's not working for you out of the box cause you're excluding the `SleuthStreamAutoConfiguration`.

Am I right @mbogoevici ?

**Comment by Ethanlin013** [comment] 2016-12-03 14:10
Yes, after your response from Gitter,we implemented with @StreamListener  and @import a configuration with @Bean(name = StreamSpanReporter.POLLER) annotation. Now we can consume the message properly from RabbitMQ. Thank you so much! 
And I am sorry that I forgot to close this issue.. Can I close the issue right now or wait for Marius' response?

**Comment by marcingrzejszczak** [comment] 2016-12-03 14:37
Nah - we can close it. I've completely forgotten that we had this chat ;)

**Closed by marcingrzejszczak** 2016-12-03 14:37 UTC
Labels: in progress, waiting for feedback
