### ISSUE TITLE
'X-B3-TraceId' header value is duplicated in the access log

### ISSUE THREAD

**Issue by shaunthomas999** [spring-cloud/spring-cloud-sleuth#795] opened 2017-11-27 14:26 UTC
Hi,

I am using spring-cloud to setup a microservice architecture where http calls are routed through api-gateway to experience API microservices (xp-api) and to capability API microservice (c-api):

api-gatway -> xp-api -> c-api

Netflix Zuul is used for routing & filtering and sleuth is enabled for tracing.

I want to print 'X-B3-TraceId' in the access log for which I am using following properties in application.yml file.

```
server:
  maxHttpHeaderSize: 65536
  tomcat:
    basedir:
    accesslog:
      enabled: true
      prefix: access
      pattern: '%h %t "%r" %s %b %D "%{Referer}i" "%{User-agent}i" "%{X-B3-TraceId}i"'
```

In the xp-api access logs, the value of 'X-B3-TraceId' header is duplicated. For e.g. `"0ff6b1beb3245e03,0ff6b1beb3245e03"`. While in c-api, the value appear only once. For e.g. `"0ff6b1beb3245e03"`. 

How can we avoid having duplicate values for 'X-B3-TraceId' header in xp-api?

**Comment by marcingrzejszczak** [comment] 2017-11-27 14:27
> "0ff6b1beb3245e03,0ff6b1beb3245e03"

this means that this is the root span. That's perfectly normal. I would however assume that this entry is present in the `api-gateway`

BTW which version of Sleuth are you using?

**Comment by shaunthomas999** [comment] 2017-11-27 14:38
I am expecting only one value in this case. Let 'X-B3-TraceId' and 'X-B3-SpanId' have the same value, but 'X-B3-TraceId' value should not be duplicated. I think this is the best approach.

I am using Sleuth version `1.2.4`

**Comment by marcingrzejszczak** [comment] 2017-11-27 14:39
> I am expecting only one value in this case. Let 'X-B3-TraceId' and 'X-B3-SpanId' have the same value, but 'X-B3-TraceId' value should not be duplicated. I think this is the best approach.

can you type exactly where a concrete value of which traceid /spanid is set? Also can you check if the problem is there with `1.2.5.RELEASE` ?

**Comment by shaunthomas999** [comment] 2017-11-27 14:44
I am not setting TraceId/SpanId explicitly. Sleuth package is automatically giving me the values.

I will test my application with Sleuth version `1.2.5.RELEASE`

**Comment by marcingrzejszczak** [comment] 2017-11-27 14:46
> I am not setting TraceId/SpanId explicitly. Sleuth package is automatically giving me the values.

I wrote :

> can you type exactly where a concrete value of which traceid /spanid is set? Also can you check if the problem is there with 1.2.5.RELEASE ?

so I assumed that Sleuth sets it. I'm not asking about the values you set, but the values Sleuth has set

**Comment by shaunthomas999** [comment] 2017-11-27 16:02
I tried my application with version `1.2.5.RELEASE` and `1.3.0.RELEASE`. Result is the same.

> so I assumed that Sleuth sets it. I'm not asking about the values you set, but the values Sleuth has set

Yes, you are write. The value set by Sleuth vary from request to request (i.e. it's random). I can give you some sample values from the logs. Will that help?

**Comment by marcingrzejszczak** [comment] 2017-11-27 16:07
> Yes, you are right. Value set by Sleuth vary from request to request (i.e. it's random). I can give you some sample values from the logs. Will that help?

Yes, that will help.

**Comment by shaunthomas999** [comment] 2017-11-28 06:11
Sample values

> "2aa14fcd431138ee,2aa14fcd431138ee"
> "ed0d572e03999270,ed0d572e03999270"

**Comment by marcingrzejszczak** [comment] 2017-11-28 09:35
Please paste the whole logs. What can i do with these values?

**Comment by shaunthomas999** [comment] 2017-11-28 16:50
I doubted the same. That's why I explicitly asked about it. But no worries. Please find the logs below:

api-gateway > [application logs](https://gist.github.com/shaunthomas999/66afeb6d137b7801fffaef91b60f572f)

xp-api > access log `"%{X-B3-TraceId}i"` values
> "bd810d9443f7bedb,bd810d9443f7bedb"

xp-api > [application log](https://gist.github.com/shaunthomas999/4e1382f0ac3362ee8cc794408aadbcf8)

c-api > access log `"%{X-B3-TraceId}i"` values
> "bd810d9443f7bedb"

**Comment by tmack8001** [comment] 2017-11-28 17:04
I remember recently there were issues with having multiple headers added to the outgoing gateway/Zuul request.

See following issues reported:
https://github.com/spring-cloud/spring-cloud-sleuth/issues/755

https://github.com/spring-cloud/spring-cloud-sleuth/issues/586

**Comment by marcingrzejszczak** [comment] 2017-11-28 17:04
@shaunthomas999 can you try the latest Edgware release?

**Comment by marcingrzejszczak** [comment] 2017-11-28 17:06
BTW I don't understand these logs. ARe you saying that the same value of TraceID got applied to a new request? THat's most likely related to a bug where we didn't reuse a `random` bean but created a new `Random` object each time. It got fixed in Edgware for sure (not sure if we've done a Dalston release in the meantime)

**Comment by shaunthomas999** [comment] 2017-11-30 10:33
@tmack8001 - I will check and see whether Zuul is actually adding the header 2 times. Thanks for your suggestion

@marcingrzejszczak - The issue I raised is for TraceId having double (duplicate) value, not for re-usage of same TraceId.

I will test with Edgware to check whether the issue still exists. If yes, I will create a small application where you can run and see the issue yourself.

**Comment by marcingrzejszczak** [comment] 2017-11-30 11:32
> @marcingrzejszczak - The issue I raised is for TraceId having double (duplicate) value, not for re-usage of same TraceId.

I think I've already explained it to you that it means that this is a root span. That's a perfectly valid situation

**Closed** 2018-02-01 10:31 UTC
Labels: waiting for feedback
