### ISSUE TITLE
Trace information is missing when Exception is thrown from RabbitListener methods

### ISSUE THREAD

**Issue by goober** [spring-cloud/spring-cloud-sleuth#1660] opened 2020-06-01 14:56 UTC
**Describe the bug**
When an exception is thrown from a method annotated with `@RabbitListener` all trace information is lost when it reaches the `ConditionalRejectingErrorHandler`

**Sample**
I have created a minimal application that reproduces the issue with a little more context that can be found here:
https://github.com/goober/spring-sleuth-rabbit-bug

**Comment by goober** [comment] 2020-06-01 14:57
Could it be the same cause as #1659 ?

**Comment by jonatan-ivanov** [comment] 2020-12-12 01:21
@goober Thank you for the sample project, I was able to repro the issue locally (I deleted your consumer class, since you have another consumer already and updated a few things: spring-boot 2.3.7.RELEASE and spring-coud Hoxton.SR9).

It seems the issue you are seeing is caused by the followings:
- Brave is closing the span in [`TracingRabbitListenerAdvice`](https://github.com/openzipkin/brave/blob/master/instrumentation/spring-rabbit/src/main/java/brave/spring/rabbit/TracingRabbitListenerAdvice.java#L115) right after it catches the exception thrown by the listener
- This will cause closing the [`CorrelationUpdateScope`](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/baggage/CorrelationUpdateScope.java#L110) that updates the `context` and sets its fields to `null`
- The `context` here is an [`MDCScopeDecorator$MDCContext`](https://github.com/openzipkin/brave/blob/master/context/slf4j/src/main/java/brave/context/slf4j/MDCScopeDecorator.java#L99) instance that removes the `MDC` entries
- After the `MDC` is empty, [ConditionalRejectingErrorHandler](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/ConditionalRejectingErrorHandler.java#L132) logs out the exception

The whole thing is orchestrated by [AbstractMessageListenerContainer](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java#L1461-L1498).
It seems `TracingRabbitListenerAdvice` wraps only the [invocation](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java#L1538-L1540) of the listener not the invocation **and** the [error handling](https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer.java#L1436). I think it should wrap both.

@marcingrzejszczak @adriancole What do you think?

**Comment by adriancole** [comment] 2020-12-12 01:59
if there's a way for the error handler to be wrapped in `currentTraceContext.maybeScope(contextOfListenerSpan)`, it should. This might be related to an old issue so you can follow-up here. https://github.com/openzipkin/brave/issues/815

Feel free to raise a pull request in brave, including an integration test so that it stays fixed. I won't personally have time for a while as doing job interviews, but if you raise a PR I will try to help review it.

**Comment by jonatan-ivanov** [comment] 2020-12-12 02:17
@adriancole Thanks, I'm going to look into this deeper later and get back to this thread but right now I feel that the change to wrap both the invocation and the error handling logic should happen in the `AbstractMessageListenerContainer` in `spring-amqp`, it should be "just" changing the scope/target of the AOP Proxy.

**Comment by jonatan-ivanov** [comment] 2020-12-18 01:09
Fyi: I have a fix for this: https://github.com/spring-projects/spring-amqp/pull/1287
I asked for feedback, let's see if this can be merged. :)

**Comment by garyrussell** [comment] 2020-12-21 18:54
The `@RabbitListener` has error handlers at two levels - the container error handler is invoked outside the scope of the advice chain.

If you use a `RabbitListenerErrorHandler` instead...

```java
	/**
	 * Set an
	 * {@link org.springframework.amqp.rabbit.listener.api.RabbitListenerErrorHandler} to
	 * invoke if the listener method throws an exception. A simple String representing the
	 * bean name. If a Spel expression (#{...}) is provided, the expression must
	 * evaluate to a bean name or a
	 * {@link org.springframework.amqp.rabbit.listener.api.RabbitListenerErrorHandler}
	 * instance.
	 * @return the error handler.
	 * @since 2.0
	 */
	String errorHandler() default "";
```
```java
@FunctionalInterface
public interface RabbitListenerErrorHandler {

	/**
	 * Handle the error. If an exception is not thrown, the return value is returned to
	 * the sender using normal {@code replyTo/@SendTo} semantics.
	 * @param amqpMessage the raw message received.
	 * @param message the converted spring-messaging message.
	 * @param exception the exception the listener threw, wrapped in a
	 * {@link ListenerExecutionFailedException}.
	 * @return the return value to be sent to the sender.
	 * @throws Exception an exception which may be the original or different.
	 */
	Object handleError(Message amqpMessage, org.springframework.messaging.Message<?> message,
			ListenerExecutionFailedException exception) throws Exception; // NOSONAR

}
```

It is invoked within the scope of the advice.

It provides access to the original spring-amqp `Message` as well as the spring-messaging `Message<?>` that was converted from it.

```java
@FunctionalInterface
public interface RabbitListenerErrorHandler {

	/**
	 * Handle the error. If an exception is not thrown, the return value is returned to
	 * the sender using normal {@code replyTo/@SendTo} semantics.
	 * @param amqpMessage the raw message received.
	 * @param message the converted spring-messaging message.
	 * @param exception the exception the listener threw, wrapped in a
	 * {@link ListenerExecutionFailedException}.
	 * @return the return value to be sent to the sender.
	 * @throws Exception an exception which may be the original or different.
	 */
	Object handleError(Message amqpMessage, org.springframework.messaging.Message<?> message,
			ListenerExecutionFailedException exception) throws Exception; // NOSONAR

}
```

If you re-thrown the exception after processing the error, it will be handled by the container error handler, as before.

**Comment by garyrussell** [comment] 2020-12-21 19:13
Changing the sample app to...

```java
@SpringBootApplication
@EnableScheduling
public class SleuthRabbitDemoApplication {

    Logger log = LoggerFactory.getLogger(SleuthRabbitDemoApplication.class);

    @Autowired
    private RabbitTemplate rabbitTemplate;

    public static void main(String[] args) {
        SpringApplication.run(SleuthRabbitDemoApplication.class, args);
    }

    @RabbitListener(queues = {RabbitConfiguration.queueName}, errorHandler = "leh")
    public void handler() {
        log.info("Received message");
        throw new AmqpRejectAndDontRequeueException("The message should be rejected");
    }

    @Scheduled(fixedRate = 10000)
    public void publish() {
        log.info("Publish message");
        rabbitTemplate.convertAndSend( RabbitConfiguration.topicExchangeName, "", "test");
    }
}

@Component("leh")
class LEH implements RabbitListenerErrorHandler {

    Logger log = LoggerFactory.getLogger(LEH.class);

    @Override
    public Object handleError(Message amqpMessage, org.springframework.messaging.Message<?> message, ListenerExecutionFailedException exception) throws Exception {
        log.info("failed");
        throw exception;
    }

}
```

We get

```
2020-12-21 14:12:09.466  INFO [,3db982c58f87634c,3db982c58f87634c,true] 33014 --- [   scheduling-1] c.g.g.s.SleuthRabbitDemoApplication      : Publish message
2020-12-21 14:12:09.483  INFO [,3db982c58f87634c,7cc9c0e5b9b62a69,true] 33014 --- [ntContainer#0-1] c.g.g.s.SleuthRabbitDemoApplication      : Received message
2020-12-21 14:12:09.483  INFO [,3db982c58f87634c,7cc9c0e5b9b62a69,true] 33014 --- [ntContainer#0-1] com.github.goober.sleuthrabbitdemo.LEH   : failed
2020-12-21 14:12:09.486  WARN [,,,] 33014 --- [ntContainer#0-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
```

**Comment by jonatan-ivanov** [comment] 2021-02-09 21:47
Closing in favor of https://github.com/spring-projects/spring-amqp/issues/1306

**Closed by jonatan-ivanov** 2021-02-09 21:47 UTC
Labels: bug

**Comment by ionel-sirbu-crunch** [comment] 2022-06-07 14:52
> Changing the sample app to...
> 
> ```java
> @SpringBootApplication
> @EnableScheduling
> public class SleuthRabbitDemoApplication {
> 
>     Logger log = LoggerFactory.getLogger(SleuthRabbitDemoApplication.class);
> 
>     @Autowired
>     private RabbitTemplate rabbitTemplate;
> 
>     public static void main(String[] args) {
>         SpringApplication.run(SleuthRabbitDemoApplication.class, args);
>     }
> 
>     @RabbitListener(queues = {RabbitConfiguration.queueName}, errorHandler = "leh")
>     public void handler() {
>         log.info("Received message");
>         throw new AmqpRejectAndDontRequeueException("The message should be rejected");
>     }
> 
>     @Scheduled(fixedRate = 10000)
>     public void publish() {
>         log.info("Publish message");
>         rabbitTemplate.convertAndSend( RabbitConfiguration.topicExchangeName, "", "test");
>     }
> }
> 
> @Component("leh")
> class LEH implements RabbitListenerErrorHandler {
> 
>     Logger log = LoggerFactory.getLogger(LEH.class);
> 
>     @Override
>     public Object handleError(Message amqpMessage, org.springframework.messaging.Message<?> message, ListenerExecutionFailedException exception) throws Exception {
>         log.info("failed");
>         throw exception;
>     }
> 
> }
> ```
> 
> We get
> 
> ```
> 2020-12-21 14:12:09.466  INFO [,3db982c58f87634c,3db982c58f87634c,true] 33014 --- [   scheduling-1] c.g.g.s.SleuthRabbitDemoApplication      : Publish message
> 2020-12-21 14:12:09.483  INFO [,3db982c58f87634c,7cc9c0e5b9b62a69,true] 33014 --- [ntContainer#0-1] c.g.g.s.SleuthRabbitDemoApplication      : Received message
> 2020-12-21 14:12:09.483  INFO [,3db982c58f87634c,7cc9c0e5b9b62a69,true] 33014 --- [ntContainer#0-1] com.github.goober.sleuthrabbitdemo.LEH   : failed
> 2020-12-21 14:12:09.486  WARN [,,,] 33014 --- [ntContainer#0-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
> ```

Hi guys, apologies for replying this late after the issue has been closed!

Bumped into the `Reply received after timeout` error again today & started digging these old tickets, which led me to try the proposed workaround above (updated sample app [here](https://github.com/ionel-sirbu-crunch/zipkin-rabbit-test)). However, it doesn't actually work with the particular scenario that I've described in ticket #1825 - the custom error handler never kicks in. 
Could this mean that the 2 issues aren't in fact the same? #1825 was closed as a duplicate - shall I reopen it?

Either way, tracing information could really help identify those slow consumers. At the moment logs provide absolutely no clue whatsoever. Any chance this could get looked into?

Thank you very much!

**Comment by garyrussell** [comment] 2022-06-07 15:00
See https://github.com/spring-cloud/spring-cloud-sleuth/issues/1660#issuecomment-776265734
