### ISSUE TITLE
spring-cloud `Hoxton.Release`. java.lang.NoClassDefFoundError: org/springframework/kafka/config/StreamsBuilderFactoryBean

### ISSUE THREAD

**Issue by asgarj** [spring-cloud/spring-cloud-sleuth#1537] opened 2020-01-24 22:07 UTC
I have upgraded to spring-boot `2.2.4.Release` and spring-cloud `Hoxton.Release` (tried `Hoxton.SR1` too) and spring application context fails to load in tests with the following error:
Note: the application is not using any kafka.

```
Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/kafka/config/StreamsBuilderFactoryBean
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 114 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/kafka/config/StreamsBuilderFactoryBean
	at org.springframework.cloud.sleuth.instrument.messaging.KafkaStreamsBuilderFactoryBeanPostProcessor.postProcessAfterInitialization(SleuthKafkaStreamsConfiguration.java:98)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	... 133 more
```

Is this like one of those bugs where `@ConditionalOnClass` is not correctly used and results in such `NoClassDefFoundError` in the runtime?

**Comment by marcingrzejszczak** [comment] 2020-01-24 22:57
Yeah most likely. We had that code for some time now and there was no problem. That's interesting. Do you have a sample that replicates this? As a workaround you can disable kafka tracing in sleuth

**Comment by asgarj** [comment] 2020-01-27 10:32
I downgraded spring-cloud to `Greenwich.SR4` and that worked fine. Is this something can be fixed in `Hoxton.SR2`?

This occurred only in tests that context failed to load. However, when running the app in a container, it loads fine.

**Comment by marcingrzejszczak** [comment] 2020-01-27 10:34
As I said, I have no idea what you're doing and how your build is setup. I don't even know what to fix cause I can't replicate it. You're the first person to mention this issue so there is some probability that your setup is wrong.

**Comment by asgarj** [comment] 2020-01-27 11:26
what's the flag to disable kafka tracing in sleuth?

**Comment by marcingrzejszczak** [comment] 2020-01-27 11:55
Please read the docs https://cloud.spring.io/spring-cloud-sleuth/reference/html/#spring-kafka or https://cloud.spring.io/spring-cloud-sleuth/reference/html/appendix.html

**Comment by asgarj** [comment] 2020-01-27 12:20
What causes it to fail is the presence of wiremock dependency from spring-cloud in my test dependencies. That's why it fails only for tests.

I think it's still a bug to put `@ConditionalOnClass(KafkaStreams.class)` in `SleuthKafkaStreamsConfiguration`. The string value of the class name needs to be used for the `@ConditionalOnClass`.
There was once similar bug in `Finchley.Release` about opentracing which was fixed in `Greenwich`.

**Comment by marcingrzejszczak** [comment] 2020-01-27 12:22
> I think it's still a bug to put @ConditionalOnClass(KafkaStreams.class) in SleuthKafkaStreamsConfiguration. The string value of the class name needs to be used for the @ConditionalOnClass.

You're incorrect, if you read the javadocs you'll see this:

> * A {@link #value()} can be safely specified on {@code @Configuration} classes as the
 * annotation metadata is parsed by using ASM before the class is loaded. Extra care is
 * required when placed on {@code @Bean} methods, consider isolating the condition in a
 * separate {@code Configuration} class, in particular if the return type of the method
 * matches the {@link #value target of the condition}.

You shouldn't use the `class` bit when you're doing it on a method.

Anyways, still I can't help you without a sample that reproduces this problem.

**Comment by spring-issuemaster** [comment] 2020-02-07 04:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-02-14 04:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-02-14 04:47 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by wabrit** [comment] 2020-02-18 12:18
I hit the same error (in a simple Spring Context loading test) with a new Spring Boot project with pom containing:

```      
        <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.4.RELEASE</version>
		<relativePath /> 
	</parent>

        ...

        <dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Hoxton.SR1</</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

Adding the following maven test-scoped dependency cleared the issue:

```
                <dependency>
		    <groupId>org.springframework.kafka</groupId>
		    <artifactId>spring-kafka</artifactId>
		    <scope>test</scope>
		</dependency>
```

**Comment by texnewmex** [comment] 2020-09-23 03:24
This fixed our tests! Thanks!

> To block this feature, set spring.sleuth.messaging.jms.enabled to false.

https://cloud.spring.io/spring-cloud-sleuth/reference/html/#spring-kafka-streams

**Comment by krishanbaghel** [comment] 2021-04-16 16:02
Hello Team i am also getting the same issue 
i added this dependency
Hello Team 
we added Spring sleuth dependency in our project 
 ```
<spring-cloud.version>Hoxton.SR1</spring-cloud.version>

 <dependency>
     <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency> 
```
```

<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
gettiing this error 

```
{"timestamp":"2021-04-16T15:47:02.170Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker","log_level":"INFO","log_type":"msg","message":"Bean 'defaultSampler' of type [brave.sampler.Sampler$1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)"}
{"timestamp":"2021-04-16T15:47:02.180Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker","log_level":"INFO","log_type":"msg","message":"Bean 'errorParser' of type [brave.ErrorParser] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)"}
{"timestamp":"2021-04-16T15:47:02.188Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker","log_level":"INFO","log_type":"msg","message":"Bean 'noOpSpanReporter' of type [zipkin2.reporter.Reporter$1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)"}
{"timestamp":"2021-04-16T15:47:02.493Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker","log_level":"INFO","log_type":"msg","message":"Bean 'tracing' of type [brave.Tracing$Default] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)"}
{"timestamp":"2021-04-16T15:47:02.524Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker","log_level":"INFO","log_type":"msg","message":"Bean 'kafkaStreamsTracing' of type [brave.kafka.streams.KafkaStreamsTracing] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)"}
{"timestamp":"2021-04-16T15:47:02.548Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext","log_level":"WARN","log_type":"msg","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryConfiguration$EmbeddedTomcat': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/kafka/config/StreamsBuilderFactoryBean"}
{"timestamp":"2021-04-16T15:47:02.574Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener","log_level":"INFO","log_type":"msg","message":"\r\n\r\nError starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled."}
{"timestamp":"2021-04-16T15:47:02.599Z","trace":{"X-B3-TraceId":"","X-B3-SpanId":"","X-Span-Export":"","X-Correlation-Id":""},"logger":"org.springframework.boot.SpringApplication","log_level":"ERROR","log_type":"msg","message":"Application run failed"}

Process finished with exit code 1
```

**Comment by marcingrzejszczak** [comment] 2021-04-19 06:46
Please use the latest cloud version `Hoxton.SR10` with the latest `2.3.x` boot version.

**Comment by sixcorners** [comment] 2021-09-15 07:41
@marcingrzejszczak 
This reproduces it.
[demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/7167833/demo.zip)
It's a demo project from https://start.spring.io/ generated with spring cloud stream and sleuth plus the latest spring-cloud-stream-binder-kinesis added to it (2.2.0). The spring cloud stream dependency isn't actually needed just the binder. Run `mvn test` to see the error.
