### ISSUE TITLE
Sleuth not working with Spring Boot 3.0.0

### ISSUE THREAD

**Issue by schoeffm** [spring-cloud/spring-cloud-sleuth#2239] opened 2022-12-11 12:08 UTC
**Describe the bug**
I have a Spring Boot 3.0.0 based application where I tried to integrate Spring Sleuth with Spring Kafka - unfortunately without much success. In simulating that issue I've came up with a minimal example that's basically based on the Spring Sleuth [Getting Started](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/getting-started.html#getting-started-first-application-pom) section. The resulting application doesn't generate traces/spans and doesn't log 'em as [described in the docs](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/getting-started.html#getting-started-first-application-run).

<img width="1590" alt="Bildschirmfoto 2022-12-11 um 11 30 39" src="https://user-images.githubusercontent.com/2795468/206902120-53b86d53-0414-4006-a740-5e80995effbc.png">

I'm also not able to inject instances of `Tracer` into my Beans (as described [here](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/using.html#using-span-lifecycle)) since there is apparently no bean of that type configured:
```bash
2022-12-11T13:03:59.041+01:00 ERROR [sleuth-test,,] 2551 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field tracer in de.bender.sleuth.sleuthdemo.SleuthController required a bean of type 'org.springframework.cloud.sleuth.Tracer' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.springframework.cloud.sleuth.Tracer' in your configuration.
```

**Notice**: When changing the version of `spring-boot-starter-parent` from `3.0.0` to i.e. `2.6.6` the same example produces:
<img width="1574" alt="Bildschirmfoto 2022-12-11 um 11 28 50" src="https://user-images.githubusercontent.com/2795468/206902236-fcbf4e16-695c-4657-920c-5fe3a90e1f1e.png">

**Sample**
I've added the sample-project that produces the output from above. Just change the version of `spring-boot-starter-parent` from `3.0.0` to `2.6.6` to simulate my output.

[sleuth-demo.zip](https://github.com/spring-cloud/spring-cloud-sleuth/files/10202134/sleuth-demo.zip)

**Comment by marcingrzejszczak** [comment] 2022-12-11 12:31
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/2235

**Closed as not planned** 2022-12-11 12:31 UTC
