### ISSUE TITLE
Zipkin spans show up with the wrong service tag in UI

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-sleuth#23] opened 2015-08-13 08:34 UTC
The data looks OK to me. But look at the screenshot below: the top waterfall bar in the background says "testSleuthZipkin", but you can see from the popup that it originates in "testSleuthRibbon".

![screenshot](https://cdn.pbrd.co/images/2Gs5Hk18.png)

**Comment by marcingrzejszczak** [comment] 2015-09-20 07:04
It's repetitive we had the same case during the VoxxedDays conference:
![zipkin](https://cloud.githubusercontent.com/assets/3297437/9979629/7feec186-5f76-11e5-95da-e10c00d62996.png)

**Comment by kontarmac** [comment] 2015-09-29 08:09
Hi,

we have the same problem. It seems that the first service is not displaying in a right way. We are using Spring Cloud Sleuth to send the spans to the zipkin collector.

![image](https://cloud.githubusercontent.com/assets/14886085/10158408/27d0be0a-6692-11e5-8093-6f929e820427.png)

**Comment by dsyer** [comment] 2015-09-29 08:48
Since the data looks OK I would encourage you to raise or follow issues in openzipkin/zipkin.

**Comment by marcingrzejszczak** [comment] 2016-01-26 14:11
Closing since the issue is on the openzipkin side

**Closed by marcingrzejszczak** 2016-01-26 14:11 UTC
