### ISSUE TITLE
Slf4jSpanReporter

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-cloud/spring-cloud-sleuth#575] opened 2017-04-22 23:03 UTC
I wanted to report the `Span`s to logs instead of Zipkin, so I came up with a couple of very simple (and not yet finished) classes which can solve the problem:

```java
@Slf4j
@AllArgsConstructor
@Component
public class Slf4jSpanReporter implements SpanReporter {
    private final SpanConverter converter;

    @Override
    public void report(Span span) {
        log.trace(converter.apply(span));
    }
}
```

```java
public interface SpanConverter extends Function<Span, String> {
}
```

```java
@Component
public class DefaultSpanConverter implements SpanConverter {
    @Override
    public String apply(Span span) {
        StringBuilder sb = new StringBuilder(128);

        // appending the fields  of the Span in a key="value" format

        return sb.toString();
    }
}
```

What do you think, does this worth a PR?

**Comment by adriancole** [comment] 2017-04-23 11:21
Seems like you could just do it yourself for now, until others start asking
for this. It doesnt look like a lot of code.

In other projects there is a logging reporter that doesnt allow any
configuration. I would hestitate before guessing what sort of options are
wanted in what is usually a test option.

**Comment by jonatan-ivanov** [comment] 2017-04-23 20:16
I'm doing it right now, I don't need this to be in this project, I just thought that it would be handy for everyone to be able to report `Span`s to logs not just to Zipkin.
Btw, I think others have already asked for something similar: #466.

I think making this configurable (`SpanConverter`) is vital here.
You don't need to guess, if somebody wants this feature, they can implement their own converter. A default implementation is not necessary here just a nice to have.

**Comment by adriancole** [comment] 2017-04-24 05:21
The key point is that if there's an extension point intended for others,
that others verify it works for them. One way is to ask directly others who
have asked for something similar. That's what I meant by guessing.. instead
of guessing what others will want for extension, ask them.

**Comment by marcingrzejszczak** [comment] 2017-04-24 09:38
Let's close it for now and if more people are interested in this we'll reopen the ticket.

**Closed by marcingrzejszczak** 2017-04-24 09:38 UTC
Labels: waiting for feedback

**Comment by jonatan-ivanov** [comment] 2017-04-24 16:33
How many other users do you need to consider accepting a PR for this?

**Comment by FlorianLautenschlager** [comment] 2017-04-25 07:24
I implemented the `ZipkinSpanReporter` interface and used the `Encoder` from Zipkin.

```JAVA
@Override
public void report(Span span) {
    byte[] spanAsBytes;
    if (useJson) {
        spanAsBytes = Encoder.JSON.encode(span);
     } else {
         spanAsBytes = Encoder.THRIFT.encode(span);
     }
     logger.info(new String(spanAsBytes));
    }
```

**Comment by adriancole** [comment] 2017-04-25 08:18
[rule-of-three](http://blog.codinghorror.com/rule-of-three/) is a good start. Note that wanting something abstractly is different than wanting a particular implementation. So, make sure folks are able to use an impl (otherwise, they still need custom code!)

**Comment by jramsdale** [comment] 2017-04-25 15:29
We implemented this same feature (directly, though, without the `SpanConverter` concept) and I'm on the fence as to whether Sleuth would benefit from providing a logging implementation. I lean a little towards "yes" because it would be an easy way for new Sleuth users to try Sleuth out and for debugging. We did need to customize our output (we have to render trace and span IDs as UUIDs). The counter argument is that it's so little code (about 12 lines of actual logic) it may not be necessary. Lowering the bar to entry does have its own benefits, though.

**Comment by jramsdale** [comment] 2017-04-25 15:48
@jonatan-ivanov I think you'll want an `isExportable` check in your `report` method. Also, we need to have these posted at `INFO` level. That might need to be a configurable feature.

**Comment by marcingrzejszczak** [comment] 2017-04-26 07:30
I had a chat with @adriancole about this feature and this is my opinion on this.

@jramsdale @jonatan-ivanov and @FlorianLautenschlager are using this feature. From what I see all of you are using the feature in different ways.

- @jonatan-ivanov is using a `StringBuilder` and logs stuff on the `TRACE` severity level
- @jramsdale is converting the Span's ids to UUID before outputting them
- @FlorianLautenschlager is using `Zipkin` encoder to use either use JSON or Thrift to output stuff to the logs on the `INFO` severity level

So basically all of you do the same but in a completely different way. The same == put stuff into logs. That reminds me of a similar problem that I had in one of my previous jobs. We had a `FraudDetection` microservice to write. Every country has  a personal identification number. All countries have rules to analyze whether that number is fake - so you could think of doing an abstraction right? But the problem is that for each country the number structure is different and the rules are different too. So the only common part is "check if the personal identification number is ok". So we ended up with a similar API but the internals were completely different and not shared. The DRY rule is not always the best idea and I think this is also the same situation.

Here in order to make all the options configurable (logging level, format of output - we can't use Zipkin's API cause we would have to put this into Sleuth core were there's no notion of Zipkin) + verify if stuff is exportable would take more code than the string producing code itself. In your cases you have to pass sth like 10-15 lines of code to achieve exactly what your company needs.

So I'd vote for not putting this stuff to core cause it differs between requirements so much that instead for the user to register a bean with ~15 lines of code we will have to produce a lot of code that will have to get customized anyways.

**Comment by jramsdale** [comment] 2017-04-26 15:22
It seems to me that this feature requires two characteristics: 1) The ability to set the log level (per Span, or just once, at startup?), and 2) The ability to take a Span and format it as a String. So I think the question is whether these can be implemented in such a way that they provide value by reducing the amount of code the user is required to write. As well, I think there's value in having an out-of-the-box experience for a user, with a default log message structure.

I totally get your point, @marcingrzejszczak, about having such a generic feature that it's not providing any value. On the other hand, I think all 3 of us are essentially doing the same thing: turn a Span into a String. My gut tells me that should be an achievable abstraction. Providing a default Sl4jSpanReporter that users can duplicate and modify for their own purposes may be acceptable. Either way, I think it would be a nice addition to the project.

**Comment by jonatan-ivanov** [comment] 2017-04-26 19:39
@marcingrzejszczak The code I posted originally is just a very rough example in order to find out if this is something that worth to discuss, and create a PR with the appropriate changes (definitely not the ones above).

I highly agree with @jramsdale what all of us are doing is converting a span to a string and log it.
I'm not really concerned about the log level as long as it is reasonable (i.e.: trace, debug, info) or it is configurable. In my example, I used trace because that's the level what I saw in [Slf4jSpanLogger](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jSpanLogger.java#L96-L98).
I think a default implementation of a `SpanConverter` is not a must here, just a nice to have.
What I think would be very useful is an `Slf4jSpanReporter` and a `SpanConverter` interface.
